In [1]:
# -*- coding: utf-8 -*-
import json
from itertools import count

import pandas as pd
import requests
from pathlib import Path
from tabulate import tabulate
from pprint import pprint

In [2]:
# Assign spreadsheet filename to `file`
file = './data/Сводный перечень текущих работ для графиков.xlsx'

# Load spreadsheet
xl = pd.ExcelFile(file)

# Print the sheet names
sheet_names = xl.sheet_names
print(sheet_names)

# Load a sheet into a DataFrame by name: df1
df1 = xl.parse(sheet_names[0])

['ПЕРЕЧЕНЬ ГЗ - 2025']

In [3]:
print(df1.shape)
df1

(207, 19)

,Шифр работы,№,Вид \nработы,Наименование проекта,Курирующий зам. пред. МКА,Руководитель отраслевого управления,Администрат\nУКПД,ГЗК/ГП/ЛД о подготовке,Ссылка на верхнеуровневый график,Ссылка на расширенный график,Месяц \nутверждения,Курирующий Зам. Директора,Руководитель\nподразделения,Рук проекта,СМАРТ,Согласовано Генплан\nСмарт,Согласовано Управление МКА\nСмарт,Согласовано Курирующим Зам\nСмарт,Unnamed: 18
0,6-20/133-26,NaN,ППТ,Подготовка проекта планировки территории по ад...,Ильин А.Ю.,Шабалдина Е.А.,Белоусова Т.С.,от 26 марта 2020 г. № 9 п. 5\nот 03 февраля 20...,Прииостановлено.\nГрафик будет подготовлен пос...,Прииостановлено.\nГрафик будет подготовлен пос...,NaT,Иванова А.А.,Агафонкина А.В.,Лапина О.И.,NaN,NaN,NaN,NaN,NaN
1,41-21/153-26,NaN,ППТ,"Проект планировки территории, ограниченной Пер...",Ильин А.Ю.,Шабалдина Е.А.,Белоусова Т.С.,п.4 №12 от 01.04.2021,Прииостановлено.\nГрафик будет подготовлен пос...,Прииостановлено.\nГрафик будет подготовлен пос...,NaT,Иванова А.А.,Агафонкина А.В.,Соловьянова Е.А.,NaN,NaN,NaN,NaN,NaN
2,6-22/162-26,1,ППТ,Подготовка проекта планировки территории Киевс...,Ильин А.Ю.,Шабалдина Е.А.,Белоусова Т.С.,Протокол № 8 п. 17 от 10.03.2022,https://docs.google.com/spreadsheets/d/1BIG1oo...,https://docs.google.com/spreadsheets/d/1BIG1oo...,NaT,Иванова А.А.,Глушко М.М.,Асатрян А.А.,NaN,Подписано,График направлен в МКА 12.03.2025,NaN,NaN
3,23/224-26,NaN,ППТ,Подготовка проекта планировки территории посел...,Ильин А.Ю.,Шабалдина Е.А.,Владимиров А.А.,Протокол от 26.10.2023 №32 п. 15,"Прииостановлено, нет согласовонного варианта\n...","Прииостановлено, нет согласовонного варианта\n...",NaT,Иванова А.А.,Агафонкина А.В.,Соловьянова Е.А.,NaN,NaN,NaN,NaN,NaN
4,6-24/196-26,2,ППТ,"Подготовка проекта планировки территории, огра...",Ильин А.Ю.,Шабалдина Е.А.,Владимиров А.А.,Протокол от 29.05.2024 № 18 п.72,https://docs.google.com/spreadsheets/d/1BIG1oo...,https://docs.google.com/spreadsheets/d/1BIG1oo...,NaT,Иванова А.А.,Агафонкина А.В.,Лапина О.И.,NaN,Подписано,График направлен в МКА 12.03.2025,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,NaN,6,ППТ ЛО,Подготовка проекта планировки территории линей...,NaN,Конюкова А.А.,Шпынев В.А.,от 14.11.2024 №39 п.10,https://docs.google.com/spreadsheets/d/1BwkwUa...,https://docs.google.com/spreadsheets/d/1BwkwUa...,NaT,И.А. Бахирев,НПО РУДС / С.С. Сигаев,Исмаилов А.А.,NaN,NaN,NaN,NaN,NaN
203,NaN,7,ППТ ЛО,Подготовка проекта планировки территории линей...,NaN,Конюкова А.А.,Шпынев В.А.,от 14.11.2024 №39 п.10,https://docs.google.com/spreadsheets/d/14gkaV3...,https://docs.google.com/spreadsheets/d/14gkaV3...,NaT,И.А. Бахирев,НПО РУДС / С.С. Сигаев,Исмаилов А.А.,NaN,NaN,NaN,NaN,NaN
204,NaN,NaN,10% ППТ ЛО УДС,Подготовка проекта внесения изменений в постан...,NaN,Конюкова А.А.,Иванова М.С.,NaN,Объекты ЛО (М.Е. Кандыбайло),"Делаем верхнеуровневый, \n объект на утверждении",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,NaN,NaN,10% ППТ ЛО УДС,Подготовка проекта внесения изменений в Постан...,NaN,Конюкова А.А.,Иванова М.С.,NaN,Объекты ЛО (М.Е. Кандыбайло),"Делаем верхнеуровневый, \n объект на утверждении",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,NaN,NaN,10% ППТ ЛО УДС,Подготовка проекта изменений в постановление П...,NaN,Конюкова А.А.,Иванова М.С.,NaN,Объекты ЛО (М.Е. Кандыбайло),"Делаем верхнеуровневый, \n объект на утверждении",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# удалим строки, в которых все значения NaN
df1.dropna(axis=0, how='all', inplace=True)
print(df1.shape)
print(df1.dtypes)
df1

(196, 19)
Шифр работы                                    object
№                                              object
Вид \nработы                                   object
Наименование проекта                           object
Курирующий зам. пред. МКА                      object
Руководитель отраслевого управления            object
Администрат\nУКПД                              object
ГЗК/ГП/ЛД о подготовке                         object
Ссылка на верхнеуровневый график               object
Ссылка на расширенный график                   object
Месяц \nутверждения                    datetime64[ns]
Курирующий Зам. Директора                      object
Руководитель\nподразделения                    object
Рук проекта                                    object
 СМАРТ                                        float64
Согласовано Генплан\nСмарт                     object
Согласовано Управление МКА\nСмарт              object
Согласовано Курирующим Зам\nСмарт              object
Unnamed: 18                                    object
dtype: object

,Шифр работы,№,Вид \nработы,Наименование проекта,Курирующий зам. пред. МКА,Руководитель отраслевого управления,Администрат\nУКПД,ГЗК/ГП/ЛД о подготовке,Ссылка на верхнеуровневый график,Ссылка на расширенный график,Месяц \nутверждения,Курирующий Зам. Директора,Руководитель\nподразделения,Рук проекта,СМАРТ,Согласовано Генплан\nСмарт,Согласовано Управление МКА\nСмарт,Согласовано Курирующим Зам\nСмарт,Unnamed: 18
0,6-20/133-26,NaN,ППТ,Подготовка проекта планировки территории по ад...,Ильин А.Ю.,Шабалдина Е.А.,Белоусова Т.С.,от 26 марта 2020 г. № 9 п. 5\nот 03 февраля 20...,Прииостановлено.\nГрафик будет подготовлен пос...,Прииостановлено.\nГрафик будет подготовлен пос...,NaT,Иванова А.А.,Агафонкина А.В.,Лапина О.И.,NaN,NaN,NaN,NaN,NaN
1,41-21/153-26,NaN,ППТ,"Проект планировки территории, ограниченной Пер...",Ильин А.Ю.,Шабалдина Е.А.,Белоусова Т.С.,п.4 №12 от 01.04.2021,Прииостановлено.\nГрафик будет подготовлен пос...,Прииостановлено.\nГрафик будет подготовлен пос...,NaT,Иванова А.А.,Агафонкина А.В.,Соловьянова Е.А.,NaN,NaN,NaN,NaN,NaN
2,6-22/162-26,1,ППТ,Подготовка проекта планировки территории Киевс...,Ильин А.Ю.,Шабалдина Е.А.,Белоусова Т.С.,Протокол № 8 п. 17 от 10.03.2022,https://docs.google.com/spreadsheets/d/1BIG1oo...,https://docs.google.com/spreadsheets/d/1BIG1oo...,NaT,Иванова А.А.,Глушко М.М.,Асатрян А.А.,NaN,Подписано,График направлен в МКА 12.03.2025,NaN,NaN
3,23/224-26,NaN,ППТ,Подготовка проекта планировки территории посел...,Ильин А.Ю.,Шабалдина Е.А.,Владимиров А.А.,Протокол от 26.10.2023 №32 п. 15,"Прииостановлено, нет согласовонного варианта\n...","Прииостановлено, нет согласовонного варианта\n...",NaT,Иванова А.А.,Агафонкина А.В.,Соловьянова Е.А.,NaN,NaN,NaN,NaN,NaN
4,6-24/196-26,2,ППТ,"Подготовка проекта планировки территории, огра...",Ильин А.Ю.,Шабалдина Е.А.,Владимиров А.А.,Протокол от 29.05.2024 № 18 п.72,https://docs.google.com/spreadsheets/d/1BIG1oo...,https://docs.google.com/spreadsheets/d/1BIG1oo...,NaT,Иванова А.А.,Агафонкина А.В.,Лапина О.И.,NaN,Подписано,График направлен в МКА 12.03.2025,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,NaN,6,ППТ ЛО,Подготовка проекта планировки территории линей...,NaN,Конюкова А.А.,Шпынев В.А.,от 14.11.2024 №39 п.10,https://docs.google.com/spreadsheets/d/1BwkwUa...,https://docs.google.com/spreadsheets/d/1BwkwUa...,NaT,И.А. Бахирев,НПО РУДС / С.С. Сигаев,Исмаилов А.А.,NaN,NaN,NaN,NaN,NaN
203,NaN,7,ППТ ЛО,Подготовка проекта планировки территории линей...,NaN,Конюкова А.А.,Шпынев В.А.,от 14.11.2024 №39 п.10,https://docs.google.com/spreadsheets/d/14gkaV3...,https://docs.google.com/spreadsheets/d/14gkaV3...,NaT,И.А. Бахирев,НПО РУДС / С.С. Сигаев,Исмаилов А.А.,NaN,NaN,NaN,NaN,NaN
204,NaN,NaN,10% ППТ ЛО УДС,Подготовка проекта внесения изменений в постан...,NaN,Конюкова А.А.,Иванова М.С.,NaN,Объекты ЛО (М.Е. Кандыбайло),"Делаем верхнеуровневый, \n объект на утверждении",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,NaN,NaN,10% ППТ ЛО УДС,Подготовка проекта внесения изменений в Постан...,NaN,Конюкова А.А.,Иванова М.С.,NaN,Объекты ЛО (М.Е. Кандыбайло),"Делаем верхнеуровневый, \n объект на утверждении",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,NaN,NaN,10% ППТ ЛО УДС,Подготовка проекта изменений в постановление П...,NaN,Конюкова А.А.,Иванова М.С.,NaN,Объекты ЛО (М.Е. Кандыбайло),"Делаем верхнеуровневый, \n объект на утверждении",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df1.columns

Index(['Шифр работы', '№', 'Вид \nработы', 'Наименование проекта',
       'Курирующий зам. пред. МКА', 'Руководитель отраслевого управления',
       'Администрат\nУКПД', 'ГЗК/ГП/ЛД о подготовке',
       'Ссылка на верхнеуровневый график', 'Ссылка на расширенный график',
       'Месяц \nутверждения', 'Курирующий Зам. Директора',
       'Руководитель\nподразделения', 'Рук проекта', ' СМАРТ',
       'Согласовано Генплан\nСмарт', 'Согласовано Управление МКА\nСмарт',
       'Согласовано Курирующим Зам\nСмарт', 'Unnamed: 18'],
      dtype='object')

In [6]:
list_of_dicts = df1.to_dict(orient='records')
print(type(list_of_dicts))
list_of_dicts
# for record in list_of_dicts:
#     print(json.dumps(obj=record, indent=4))

<class 'list'>

[{'Шифр работы': '6-20/133-26',
  '№': nan,
  'Вид \nработы': 'ППТ ',
  'Наименование проекта': 'Подготовка проекта планировки территории по адресу: \n3-й Силикатный пр., влд. 10',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'от 26 марта 2020 г. № 9 п. 5\nот 03 февраля 2022 г. № 4, п.2',
  'Ссылка на верхнеуровневый график': 'Прииостановлено.\nГрафик будет подготовлен после решения о продолжении работы ',
  'Ссылка на расширенный график': 'Прииостановлено.\nГрафик будет подготовлен после решения о продолжении работы',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Лапина О.И.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': nan,
  'Согласовано Управление МКА\nСмарт': nan,
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': '41-21/153-26',
  '№': nan,
  'Вид \nработы': 'ППТ ',
  'Наименование проекта': 'Проект планировки территории, ограниченной Пермской улицей, Тагильской улицей, улицей Николая Химушина, Монтажной улицей, Щелковским шоссе, Большой Черкизовской улицей, границей объекта природного комплекса Восточного административного округа города Москвы № 20 «Черкизовский парк», Тюменской улицей, Открытым шоссе, Малым кольцом Московской железной дороги',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'п.4 №12 от 01.04.2021',
  'Ссылка на верхнеуровневый график': 'Прииостановлено.\nГрафик будет подготовлен после решения о продолжении работы',
  'Ссылка на расширенный график': 'Прииостановлено.\nГрафик будет подготовлен после решения о продолжении работы',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Соловьянова Е.А.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': nan,
  'Согласовано Управление МКА\nСмарт': nan,
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': '6-22/162-26',
  '№': 1,
  'Вид \nработы': 'ППТ',
  'Наименование проекта': 'Подготовка проекта планировки территории Киевского вокзала',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'Протокол № 8 п. 17 от 10.03.2022',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=526740403#gid=526740403\nЖдем концепцию развития территории КРТ от Инвестора',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=569099005#gid=569099005\nЖдем концепцию развития территории КРТ от Инвестора',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Глушко М.М.',
  'Рук проекта': 'Асатрян А.А.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': 'Подписано',
  'Согласовано Управление МКА\nСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': '23/224-26',
  '№': nan,
  'Вид \nработы': 'ППТ',
  'Наименование проекта': 'Подготовка проекта планировки территории поселения Воскресенское, части поселка подсобного хозяйства Воскресенское',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Владимиров А.А.',
  'ГЗК/ГП/ЛД о подготовке': 'Протокол от 26.10.2023 №32 п. 15',
  'Ссылка на верхнеуровневый график': 'Прииостановлено, нет согласовонного варианта\nГрафик будет подготовлен после выбора варианта',
  'Ссылка на расширенный график': 'Прииостановлено, нет согласовонного варианта\nГрафик будет подготовлен после выбора варианта',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Соловьянова Е.А.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': nan,
  'Согласовано Управление МКА\nСмарт': nan,
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': '6-24/196-26',
  '№': 2,
  'Вид \nработы': 'ППТ',
  'Наименование проекта': 'Подготовка проекта планировки территории, ограниченной улицей Нижегородской, полосой отвода железной дороги, Южнопортовой улицей, Москвой рекой',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Владимиров А.А.',
  'ГЗК/ГП/ЛД о подготовке': 'Протокол от 29.05.2024 № 18 п.72',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=526740403#gid=526740403',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=670102455#gid=670102455',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Лапина О.И.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': 'Подписано',
  'Согласовано Управление МКА\nСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': '3-25/21-26',
  '№': 3,
  'Вид \nработы': 'ППТ',
  'Наименование проекта': 'Подготовка проекта планировки\nтерритории вблизи деревни\nКрасная Пахра района Троицк города Москвы',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'Протокол от 29.01.2025 № 3 п.3',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=526740403#gid=526740403',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=362904608#gid=362904608',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Глушко М.М.',
  'Рук проекта': 'Логинов А.Л.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': 'Подписано',
  'Согласовано Управление МКА\nСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': nan,
  '№': 3,
  'Вид \nработы': 'ППТ',
  'Наименование проекта': 'Подготовка проекта планировки территории, ограниченной шоссе Энтузиастов, шоссе Фрезер, Горьковским направлением железной дороги, улицей Подъемной',
  'Курирующий зам. пред. МКА': nan,
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Владимиров А.А.',
  'ГЗК/ГП/ЛД о подготовке': nan,
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=526740403#gid=526740403',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=1807994811#gid=1807994811',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Лапина О.И.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': 'Подписано',
  'Согласовано Управление МКА\nСмарт': 'График направлен в МКА 14.03.2025',
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': nan,
  '№': nan,
  'Вид \nработы': '10% ППТ',
  'Наименование проекта': 'Подготовка проекта внесения изменений в постановление Правительства Москвы \nот 29 февраля 2024 г. № 394-ПП «Об утверждении проекта планировки территории между Аминьевским шоссе и Рябиновой улицей»',
  'Курирующий зам. пред. МКА': nan,
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Ломакина Е.А,',
  'ГЗК/ГП/ЛД о подготовке': nan,
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1yBQ6dCzx2W4jtxffRjmhDaw7MAjyeu06yGGHqbYHoiw/edit?gid=1991169065#gid=1991169065',
  'Ссылка на расширенный график': nan,
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': nan,
  'Руководитель\nподразделения': nan,
  'Рук проекта': nan,
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': nan,
  'Согласовано Управление МКА\nСмарт': nan,
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': nan,
  '№': nan,
  'Вид \nработы': '10% ППТ',
  'Наименование проекта': 'Внесение изменений в ППМ от 28.09.2021 № 1501-ПП проект планировки территории, прилегающей к Московским центральным диаметрам: МЦД-1 "Одинцово-Лобня", участок от МКАД до границ города Москвы',
  'Курирующий зам. пред. МКА': nan,
  'Руководитель отраслевого управления': 'Петров С.А.',
  'Администрат\nУКПД': 'Иванова М.С.',
  'ГЗК/ГП/ЛД о подготовке': nan,
  'Ссылка на верхнеуровневый график': 'ГРАФИК 10% ППТ МЦД пеш.переход Одинцово-Лобня',
  'Ссылка на расширенный график': 'не требуется',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': nan,
  'Руководитель\nподразделения': nan,
  'Рук проекта': nan,
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': 'Дата заявки 08.04.\nГрафик в разработке. Идет согласование с генпроектировщиком.',
  'Согласовано Управление МКА\nСмарт': nan,
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': '3-24/218-26',
  '№': 1,
  'Вид \nработы': 'Град. потенциал\nВЛЭП',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала освобождаемых от ВЛЭП территорий в городе Москве по адресу: \nПятницкое шоссе, вл. 4-6, СЗАО',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=355278683#gid=355278683',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Глушко М.М.',
  'Рук проекта': 'Цуканова И.Б.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': 'Подписано',
  'Согласовано Управление МКА\nСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': '3-24/215-26',
  '№': 2,
  'Вид \nработы': 'Град. потенциал\nВЛЭП',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала освобождаемых от ВЛЭП территорий в городе Москве по адресу: \nТерритория ВЛЭП вдоль 2-го Нагатинского проезда, ЮАО',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=516568795#gid=516568795',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Глушко М.М.',
  'Рук проекта': 'Логинов А.Л.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': 'Подписано',
  'Согласовано Управление МКА\nСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': '6-24/237-26',
  '№': 3,
  'Вид \nработы': 'Град. потенциал\nВЛЭП',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала освобождаемых от ВЛЭП территорий в городе Москве по адресу: \nТерритория ВЛЭП от Волжского бульвара вдоль Аллеи Кремлевских курсантов до улицы Чагинской, ЮВАО',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1897185067#gid=1897185067',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Глушко М.М.',
  'Рук проекта': 'Цуканова И.Б.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': 'Подписано',
  'Согласовано Управление МКА\nСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': '3-24/276-26',
  '№': 4,
  'Вид \nработы': 'Град. потенциал\nВЛЭП',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала освобождаемых от ВЛЭП территорий в городе Москве по адресу: территория ВЛЭП вдоль Филевской линии метрополитена от станции «Фили» до бульвара Солдатенкова, ЗАО',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=774182060#gid=774182060',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Глушко М.М.',
  'Рук проекта': 'Логинов А.Л.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': 'Подписано',
  'Согласовано Управление МКА\nСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': '3-23/204-26',
  '№': 5,
  'Вид \nработы': 'Град. потенциал\nТиНАО\nОбщая 2024',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала развития территории по адресу: г. Москва, пос. Михайлово-Ярцевское, вблизи пос. Шишкин лес (ТиНАО) ',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Смутчук Б.В.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': nan,
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Каземирова Л.Р.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': 'Подписано',
  'Согласовано Управление МКА\nСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': '6-24/116-26',
  '№': 6,
  'Вид \nработы': 'Град. потенциал\nТиНАО\nОбщая 2024',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала развития территории, ограниченной МКАД, Калужским шоссе, ул. Адмирала Корнилова и Троицким лесопарком ',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Смутчук Б.В.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'Одобрено на Штабе КРТ',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Каземирова Л.Р.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': 'Подписано',
  'Согласовано Управление МКА\nСмарт': nan,
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': '6-24/180-26',
  '№': 7,
  'Вид \nработы': 'Град. потенциал\nТиНАО\nОбщая 2024',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала развития территории, прилегающей к улице Адмирала Корнилова, ТиНАО',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Смутчук Б.В.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'Одобрено на Штабе КРТ',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Каземирова Л.Р.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': 'Подписано',
  'Согласовано Управление МКА\nСмарт': nan,
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': '6-24/181-26',
  '№': 8,
  'Вид \nработы': 'Град. потенциал\nТиНАО\nОбщая 2024',
  'Наименование проекта': 'Разработка градостроительного потенциала развития территории напротив ТК «ФУД-СИТИ» у ст.м. «Корниловская»',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Смутчук Б.В.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'Одобрено на Штабе КРТ',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Каземирова Л.Р.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': 'Подписано',
  'Согласовано Управление МКА\nСмарт': nan,
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': '3-24/191-26',
  '№': 6,
  'Вид \nработы': 'Град. потенциал\nТиНАО\nОбщая 2024',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала комплексного развития территории по адресу: г. Москва, пос. Птичное, ул. Центральная, с определением границ и объемов подготовки градостроительного потенциала развития территории',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Смутчук Б.В.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=31303565#gid=31303565',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Глушко М.М.',
  'Рук проекта': 'Логинов А.Л.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': 'Подписано',
  'Согласовано Управление МКА\nСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': '3-24/224-26',
  '№': 7,
  'Вид \nработы': 'Град. потенциал\nТиНАО\nОбщая 2024',
  'Наименование проекта': 'Разработка материалов предварительной оценки градостроительного потенциала территории по адресу: г. Москва, пос. Вороновское, дер. Львово',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',

In [7]:
# преобразуем все колонки к строковому типу
df1 = df1.astype(str)
df1 = df1.replace({'nan': 'None', 'NaT': 'None'})
# df1 = df1.where('nan', 'None')
# df1 = df1.where('NaT', 'None')
# заменим nan значения на 'None' (или вовсе удалим?)
# df1.fillna('None', inplace=True)
# Убираем ведущие и завершающие пробелы из названий колонок
df1.columns = df1.columns.str.strip()
# Удаляем символы перехода на новую строку из названий колонок
df1.columns = df1.columns.str.replace('\n', ' ', regex=False)
list_of_dicts = df1.to_dict(orient='records')
list_of_dicts

[{'Шифр работы': '6-20/133-26',
  '№': 'None',
  'Вид работы': 'ППТ ',
  'Наименование проекта': 'Подготовка проекта планировки территории по адресу: \n3-й Силикатный пр., влд. 10',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'от 26 марта 2020 г. № 9 п. 5\nот 03 февраля 2022 г. № 4, п.2',
  'Ссылка на верхнеуровневый график': 'Прииостановлено.\nГрафик будет подготовлен после решения о продолжении работы ',
  'Ссылка на расширенный график': 'Прииостановлено.\nГрафик будет подготовлен после решения о продолжении работы',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Лапина О.И.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'None',
  'Согласовано Управление МКАСмарт': 'None',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': '41-21/153-26',
  '№': 'None',
  'Вид работы': 'ППТ ',
  'Наименование проекта': 'Проект планировки территории, ограниченной Пермской улицей, Тагильской улицей, улицей Николая Химушина, Монтажной улицей, Щелковским шоссе, Большой Черкизовской улицей, границей объекта природного комплекса Восточного административного округа города Москвы № 20 «Черкизовский парк», Тюменской улицей, Открытым шоссе, Малым кольцом Московской железной дороги',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'п.4 №12 от 01.04.2021',
  'Ссылка на верхнеуровневый график': 'Прииостановлено.\nГрафик будет подготовлен после решения о продолжении работы',
  'Ссылка на расширенный график': 'Прииостановлено.\nГрафик будет подготовлен после решения о продолжении работы',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Соловьянова Е.А.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'None',
  'Согласовано Управление МКАСмарт': 'None',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': '6-22/162-26',
  '№': '1',
  'Вид работы': 'ППТ',
  'Наименование проекта': 'Подготовка проекта планировки территории Киевского вокзала',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'Протокол № 8 п. 17 от 10.03.2022',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=526740403#gid=526740403\nЖдем концепцию развития территории КРТ от Инвестора',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=569099005#gid=569099005\nЖдем концепцию развития территории КРТ от Инвестора',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Глушко М.М.',
  'Рук проекта': 'Асатрян А.А.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'Подписано',
  'Согласовано Управление МКАСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': '23/224-26',
  '№': 'None',
  'Вид работы': 'ППТ',
  'Наименование проекта': 'Подготовка проекта планировки территории поселения Воскресенское, части поселка подсобного хозяйства Воскресенское',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Владимиров А.А.',
  'ГЗК/ГП/ЛД о подготовке': 'Протокол от 26.10.2023 №32 п. 15',
  'Ссылка на верхнеуровневый график': 'Прииостановлено, нет согласовонного варианта\nГрафик будет подготовлен после выбора варианта',
  'Ссылка на расширенный график': 'Прииостановлено, нет согласовонного варианта\nГрафик будет подготовлен после выбора варианта',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Соловьянова Е.А.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'None',
  'Согласовано Управление МКАСмарт': 'None',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': '6-24/196-26',
  '№': '2',
  'Вид работы': 'ППТ',
  'Наименование проекта': 'Подготовка проекта планировки территории, ограниченной улицей Нижегородской, полосой отвода железной дороги, Южнопортовой улицей, Москвой рекой',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Владимиров А.А.',
  'ГЗК/ГП/ЛД о подготовке': 'Протокол от 29.05.2024 № 18 п.72',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=526740403#gid=526740403',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=670102455#gid=670102455',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Лапина О.И.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'Подписано',
  'Согласовано Управление МКАСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': '3-25/21-26',
  '№': '3',
  'Вид работы': 'ППТ',
  'Наименование проекта': 'Подготовка проекта планировки\nтерритории вблизи деревни\nКрасная Пахра района Троицк города Москвы',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'Протокол от 29.01.2025 № 3 п.3',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=526740403#gid=526740403',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=362904608#gid=362904608',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Глушко М.М.',
  'Рук проекта': 'Логинов А.Л.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'Подписано',
  'Согласовано Управление МКАСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': 'None',
  '№': '3',
  'Вид работы': 'ППТ',
  'Наименование проекта': 'Подготовка проекта планировки территории, ограниченной шоссе Энтузиастов, шоссе Фрезер, Горьковским направлением железной дороги, улицей Подъемной',
  'Курирующий зам. пред. МКА': 'None',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Владимиров А.А.',
  'ГЗК/ГП/ЛД о подготовке': 'None',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=526740403#gid=526740403',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=1807994811#gid=1807994811',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Лапина О.И.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'Подписано',
  'Согласовано Управление МКАСмарт': 'График направлен в МКА 14.03.2025',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': 'None',
  '№': 'None',
  'Вид работы': '10% ППТ',
  'Наименование проекта': 'Подготовка проекта внесения изменений в постановление Правительства Москвы \nот 29 февраля 2024 г. № 394-ПП «Об утверждении проекта планировки территории между Аминьевским шоссе и Рябиновой улицей»',
  'Курирующий зам. пред. МКА': 'None',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Ломакина Е.А,',
  'ГЗК/ГП/ЛД о подготовке': 'None',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1yBQ6dCzx2W4jtxffRjmhDaw7MAjyeu06yGGHqbYHoiw/edit?gid=1991169065#gid=1991169065',
  'Ссылка на расширенный график': 'None',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'None',
  'Руководительподразделения': 'None',
  'Рук проекта': 'None',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'None',
  'Согласовано Управление МКАСмарт': 'None',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': 'None',
  '№': 'None',
  'Вид работы': '10% ППТ',
  'Наименование проекта': 'Внесение изменений в ППМ от 28.09.2021 № 1501-ПП проект планировки территории, прилегающей к Московским центральным диаметрам: МЦД-1 "Одинцово-Лобня", участок от МКАД до границ города Москвы',
  'Курирующий зам. пред. МКА': 'None',
  'Руководитель отраслевого управления': 'Петров С.А.',
  'АдминистратУКПД': 'Иванова М.С.',
  'ГЗК/ГП/ЛД о подготовке': 'None',
  'Ссылка на верхнеуровневый график': 'ГРАФИК 10% ППТ МЦД пеш.переход Одинцово-Лобня',
  'Ссылка на расширенный график': 'не требуется',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'None',
  'Руководительподразделения': 'None',
  'Рук проекта': 'None',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'Дата заявки 08.04.\nГрафик в разработке. Идет согласование с генпроектировщиком.',
  'Согласовано Управление МКАСмарт': 'None',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': '3-24/218-26',
  '№': '1',
  'Вид работы': 'Град. потенциал\nВЛЭП',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала освобождаемых от ВЛЭП территорий в городе Москве по адресу: \nПятницкое шоссе, вл. 4-6, СЗАО',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=355278683#gid=355278683',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Глушко М.М.',
  'Рук проекта': 'Цуканова И.Б.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'Подписано',
  'Согласовано Управление МКАСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': '3-24/215-26',
  '№': '2',
  'Вид работы': 'Град. потенциал\nВЛЭП',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала освобождаемых от ВЛЭП территорий в городе Москве по адресу: \nТерритория ВЛЭП вдоль 2-го Нагатинского проезда, ЮАО',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=516568795#gid=516568795',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Глушко М.М.',
  'Рук проекта': 'Логинов А.Л.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'Подписано',
  'Согласовано Управление МКАСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': '6-24/237-26',
  '№': '3',
  'Вид работы': 'Град. потенциал\nВЛЭП',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала освобождаемых от ВЛЭП территорий в городе Москве по адресу: \nТерритория ВЛЭП от Волжского бульвара вдоль Аллеи Кремлевских курсантов до улицы Чагинской, ЮВАО',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1897185067#gid=1897185067',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Глушко М.М.',
  'Рук проекта': 'Цуканова И.Б.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'Подписано',
  'Согласовано Управление МКАСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': '3-24/276-26',
  '№': '4',
  'Вид работы': 'Град. потенциал\nВЛЭП',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала освобождаемых от ВЛЭП территорий в городе Москве по адресу: территория ВЛЭП вдоль Филевской линии метрополитена от станции «Фили» до бульвара Солдатенкова, ЗАО',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=774182060#gid=774182060',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Глушко М.М.',
  'Рук проекта': 'Логинов А.Л.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'Подписано',
  'Согласовано Управление МКАСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': '3-23/204-26',
  '№': '5',
  'Вид работы': 'Град. потенциал\nТиНАО\nОбщая 2024',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала развития территории по адресу: г. Москва, пос. Михайлово-Ярцевское, вблизи пос. Шишкин лес (ТиНАО) ',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Смутчук Б.В.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'None',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Каземирова Л.Р.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'Подписано',
  'Согласовано Управление МКАСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': '6-24/116-26',
  '№': '6',
  'Вид работы': 'Град. потенциал\nТиНАО\nОбщая 2024',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала развития территории, ограниченной МКАД, Калужским шоссе, ул. Адмирала Корнилова и Троицким лесопарком ',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Смутчук Б.В.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'Одобрено на Штабе КРТ',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Каземирова Л.Р.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'Подписано',
  'Согласовано Управление МКАСмарт': 'None',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': '6-24/180-26',
  '№': '7',
  'Вид работы': 'Град. потенциал\nТиНАО\nОбщая 2024',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала развития территории, прилегающей к улице Адмирала Корнилова, ТиНАО',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Смутчук Б.В.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'Одобрено на Штабе КРТ',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Каземирова Л.Р.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'Подписано',
  'Согласовано Управление МКАСмарт': 'None',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': '6-24/181-26',
  '№': '8',
  'Вид работы': 'Град. потенциал\nТиНАО\nОбщая 2024',
  'Наименование проекта': 'Разработка градостроительного потенциала развития территории напротив ТК «ФУД-СИТИ» у ст.м. «Корниловская»',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Смутчук Б.В.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'Одобрено на Штабе КРТ',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Каземирова Л.Р.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'Подписано',
  'Согласовано Управление МКАСмарт': 'None',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': '3-24/191-26',
  '№': '6',
  'Вид работы': 'Град. потенциал\nТиНАО\nОбщая 2024',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала комплексного развития территории по адресу: г. Москва, пос. Птичное, ул. Центральная, с определением границ и объемов подготовки градостроительного потенциала развития территории',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Смутчук Б.В.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=31303565#gid=31303565',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Глушко М.М.',
  'Рук проекта': 'Логинов А.Л.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'Подписано',
  'Согласовано Управление МКАСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': '3-24/224-26',
  '№': '7',
  'Вид работы': 'Град. потенциал\nТиНАО\nОбщая 2024',
  'Наименование проекта': 'Разработка материалов предварительной оценки градостроительного потенциала территории по адресу: г. Москва, пос. Вороновское, дер. Львово',

In [8]:
for record in list_of_dicts:
    print(json.dumps(obj=record, indent=4, ensure_ascii=False))

{
    "Шифр работы": "6-20/133-26",
    "№": "None",
    "Вид работы": "ППТ ",
    "Наименование проекта": "Подготовка проекта планировки территории по адресу: \n3-й Силикатный пр., влд. 10",
    "Курирующий зам. пред. МКА": "Ильин А.Ю.",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Белоусова Т.С.",
    "ГЗК/ГП/ЛД о подготовке": "от 26 марта 2020 г. № 9 п. 5\nот 03 февраля 2022 г. № 4, п.2",
    "Ссылка на верхнеуровневый график": "Прииостановлено.\nГрафик будет подготовлен после решения о продолжении работы ",
    "Ссылка на расширенный график": "Прииостановлено.\nГрафик будет подготовлен после решения о продолжении работы",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "Иванова А.А.",
    "Руководительподразделения": "Агафонкина А.В.",
    "Рук проекта": "Лапина О.И.",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "None",
    "Согласовано Управление МКАСмарт": "None",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "41-21/153-26",
    "№": "None",
    "Вид работы": "ППТ ",
    "Наименование проекта": "Проект планировки территории, ограниченной Пермской улицей, Тагильской улицей, улицей Николая Химушина, Монтажной улицей, Щелковским шоссе, Большой Черкизовской улицей, границей объекта природного комплекса Восточного административного округа города Москвы № 20 «Черкизовский парк», Тюменской улицей, Открытым шоссе, Малым кольцом Московской железной дороги",
    "Курирующий зам. пред. МКА": "Ильин А.Ю.",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Белоусова Т.С.",
    "ГЗК/ГП/ЛД о подготовке": "п.4 №12 от 01.04.2021",
    "Ссылка на верхнеуровневый график": "Прииостановлено.\nГрафик будет подготовлен после решения о продолжении работы",
    "Ссылка на расширенный график": "Прииостановлено.\nГрафик будет подготовлен после решения о продолжении работы",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "Иванова А.А.",
    "Руководительподразделения": "Агафонкина А.В.",
    "Рук проекта": "Соловьянова Е.А.",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "None",
    "Согласовано Управление МКАСмарт": "None",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "6-22/162-26",
    "№": "1",
    "Вид работы": "ППТ",
    "Наименование проекта": "Подготовка проекта планировки территории Киевского вокзала",
    "Курирующий зам. пред. МКА": "Ильин А.Ю.",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Белоусова Т.С.",
    "ГЗК/ГП/ЛД о подготовке": "Протокол № 8 п. 17 от 10.03.2022",
    "Ссылка на верхнеуровневый график": "https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=526740403#gid=526740403\nЖдем концепцию развития территории КРТ от Инвестора",
    "Ссылка на расширенный график": "https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=569099005#gid=569099005\nЖдем концепцию развития территории КРТ от Инвестора",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "Иванова А.А.",
    "Руководительподразделения": "Глушко М.М.",
    "Рук проекта": "Асатрян А.А.",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "Подписано",
    "Согласовано Управление МКАСмарт": "График направлен в МКА 12.03.2025",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "23/224-26",
    "№": "None",
    "Вид работы": "ППТ",
    "Наименование проекта": "Подготовка проекта планировки территории поселения Воскресенское, части поселка подсобного хозяйства Воскресенское",
    "Курирующий зам. пред. МКА": "Ильин А.Ю.",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Владимиров А.А.",
    "ГЗК/ГП/ЛД о подготовке": "Протокол от 26.10.2023 №32 п. 15",
    "Ссылка на верхнеуровневый график": "Прииостановлено, нет согласовонного варианта\nГрафик будет подготовлен после выбора варианта",
    "Ссылка на расширенный график": "Прииостановлено, нет согласовонного варианта\nГрафик будет подготовлен после выбора варианта",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "Иванова А.А.",
    "Руководительподразделения": "Агафонкина А.В.",
    "Рук проекта": "Соловьянова Е.А.",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "None",
    "Согласовано Управление МКАСмарт": "None",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "6-24/196-26",
    "№": "2",
    "Вид работы": "ППТ",
    "Наименование проекта": "Подготовка проекта планировки территории, ограниченной улицей Нижегородской, полосой отвода железной дороги, Южнопортовой улицей, Москвой рекой",
    "Курирующий зам. пред. МКА": "Ильин А.Ю.",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Владимиров А.А.",
    "ГЗК/ГП/ЛД о подготовке": "Протокол от 29.05.2024 № 18 п.72",
    "Ссылка на верхнеуровневый график": "https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=526740403#gid=526740403",
    "Ссылка на расширенный график": "https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=670102455#gid=670102455",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "Иванова А.А.",
    "Руководительподразделения": "Агафонкина А.В.",
    "Рук проекта": "Лапина О.И.",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "Подписано",
    "Согласовано Управление МКАСмарт": "График направлен в МКА 12.03.2025",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "3-25/21-26",
    "№": "3",
    "Вид работы": "ППТ",
    "Наименование проекта": "Подготовка проекта планировки\nтерритории вблизи деревни\nКрасная Пахра района Троицк города Москвы",
    "Курирующий зам. пред. МКА": "Ильин А.Ю.",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Белоусова Т.С.",
    "ГЗК/ГП/ЛД о подготовке": "Протокол от 29.01.2025 № 3 п.3",
    "Ссылка на верхнеуровневый график": "https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=526740403#gid=526740403",
    "Ссылка на расширенный график": "https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=362904608#gid=362904608",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "Иванова А.А.",
    "Руководительподразделения": "Глушко М.М.",
    "Рук проекта": "Логинов А.Л.",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "Подписано",
    "Согласовано Управление МКАСмарт": "График направлен в МКА 12.03.2025",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "None",
    "№": "3",
    "Вид работы": "ППТ",
    "Наименование проекта": "Подготовка проекта планировки территории, ограниченной шоссе Энтузиастов, шоссе Фрезер, Горьковским направлением железной дороги, улицей Подъемной",
    "Курирующий зам. пред. МКА": "None",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Владимиров А.А.",
    "ГЗК/ГП/ЛД о подготовке": "None",
    "Ссылка на верхнеуровневый график": "https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=526740403#gid=526740403",
    "Ссылка на расширенный график": "https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=1807994811#gid=1807994811",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "Иванова А.А.",
    "Руководительподразделения": "Агафонкина А.В.",
    "Рук проекта": "Лапина О.И.",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "Подписано",
    "Согласовано Управление МКАСмарт": "График направлен в МКА 14.03.2025",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "None",
    "№": "None",
    "Вид работы": "10% ППТ",
    "Наименование проекта": "Подготовка проекта внесения изменений в постановление Правительства Москвы \nот 29 февраля 2024 г. № 394-ПП «Об утверждении проекта планировки территории между Аминьевским шоссе и Рябиновой улицей»",
    "Курирующий зам. пред. МКА": "None",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Ломакина Е.А,",
    "ГЗК/ГП/ЛД о подготовке": "None",
    "Ссылка на верхнеуровневый график": "https://docs.google.com/spreadsheets/d/1yBQ6dCzx2W4jtxffRjmhDaw7MAjyeu06yGGHqbYHoiw/edit?gid=1991169065#gid=1991169065",
    "Ссылка на расширенный график": "None",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "None",
    "Руководительподразделения": "None",
    "Рук проекта": "None",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "None",
    "Согласовано Управление МКАСмарт": "None",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "None",
    "№": "None",
    "Вид работы": "10% ППТ",
    "Наименование проекта": "Внесение изменений в ППМ от 28.09.2021 № 1501-ПП проект планировки территории, прилегающей к Московским центральным диаметрам: МЦД-1 \"Одинцово-Лобня\", участок от МКАД до границ города Москвы",
    "Курирующий зам. пред. МКА": "None",
    "Руководитель отраслевого управления": "Петров С.А.",
    "АдминистратУКПД": "Иванова М.С.",
    "ГЗК/ГП/ЛД о подготовке": "None",
    "Ссылка на верхнеуровневый график": "ГРАФИК 10% ППТ МЦД пеш.переход Одинцово-Лобня",
    "Ссылка на расширенный график": "не требуется",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "None",
    "Руководительподразделения": "None",
    "Рук проекта": "None",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "Дата заявки 08.04.\nГрафик в разработке. Идет согласование с генпроектировщиком.",
    "Согласовано Управление МКАСмарт": "None",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "3-24/218-26",
    "№": "1",
    "Вид работы": "Град. потенциал\nВЛЭП",
    "Наименование проекта": "Подготовка материалов предварительной оценки градостроительного потенциала освобождаемых от ВЛЭП территорий в городе Москве по адресу: \nПятницкое шоссе, вл. 4-6, СЗАО",
    "Курирующий зам. пред. МКА": "Ильин А.Ю.",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Белоусова Т.С.",
    "ГЗК/ГП/ЛД о подготовке": "Не требуется",
    "Ссылка на верхнеуровневый график": "https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271",
    "Ссылка на расширенный график": "https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=355278683#gid=355278683",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "Иванова А.А.",
    "Руководительподразделения": "Глушко М.М.",
    "Рук проекта": "Цуканова И.Б.",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "Подписано",
    "Согласовано Управление МКАСмарт": "График направлен в МКА 12.03.2025",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "3-24/215-26",
    "№": "2",
    "Вид работы": "Град. потенциал\nВЛЭП",
    "Наименование проекта": "Подготовка материалов предварительной оценки градостроительного потенциала освобождаемых от ВЛЭП территорий в городе Москве по адресу: \nТерритория ВЛЭП вдоль 2-го Нагатинского проезда, ЮАО",
    "Курирующий зам. пред. МКА": "Ильин А.Ю.",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Белоусова Т.С.",
    "ГЗК/ГП/ЛД о подготовке": "Не требуется",
    "Ссылка на верхнеуровневый график": "https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271",
    "Ссылка на расширенный график": "https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=516568795#gid=516568795",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "Иванова А.А.",
    "Руководительподразделения": "Глушко М.М.",
    "Рук проекта": "Логинов А.Л.",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "Подписано",
    "Согласовано Управление МКАСмарт": "График направлен в МКА 12.03.2025",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "6-24/237-26",
    "№": "3",
    "Вид работы": "Град. потенциал\nВЛЭП",
    "Наименование проекта": "Подготовка материалов предварительной оценки градостроительного потенциала освобождаемых от ВЛЭП территорий в городе Москве по адресу: \nТерритория ВЛЭП от Волжского бульвара вдоль Аллеи Кремлевских курсантов до улицы Чагинской, ЮВАО",
    "Курирующий зам. пред. МКА": "Ильин А.Ю.",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Белоусова Т.С.",
    "ГЗК/ГП/ЛД о подготовке": "Не требуется",
    "Ссылка на верхнеуровневый график": "https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271",
    "Ссылка на расширенный график": "https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1897185067#gid=1897185067",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "Иванова А.А.",
    "Руководительподразделения": "Глушко М.М.",
    "Рук проекта": "Цуканова И.Б.",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "Подписано",
    "Согласовано Управление МКАСмарт": "График направлен в МКА 12.03.2025",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "3-24/276-26",
    "№": "4",
    "Вид работы": "Град. потенциал\nВЛЭП",
    "Наименование проекта": "Подготовка материалов предварительной оценки градостроительного потенциала освобождаемых от ВЛЭП территорий в городе Москве по адресу: территория ВЛЭП вдоль Филевской линии метрополитена от станции «Фили» до бульвара Солдатенкова, ЗАО",
    "Курирующий зам. пред. МКА": "Ильин А.Ю.",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Белоусова Т.С.",
    "ГЗК/ГП/ЛД о подготовке": "Не требуется",
    "Ссылка на верхнеуровневый график": "https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271",
    "Ссылка на расширенный график": "https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=774182060#gid=774182060",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "Иванова А.А.",
    "Руководительподразделения": "Глушко М.М.",
    "Рук проекта": "Логинов А.Л.",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "Подписано",
    "Согласовано Управление МКАСмарт": "График направлен в МКА 12.03.2025",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "3-23/204-26",
    "№": "5",
    "Вид работы": "Град. потенциал\nТиНАО\nОбщая 2024",
    "Наименование проекта": "Подготовка материалов предварительной оценки градостроительного потенциала развития территории по адресу: г. Москва, пос. Михайлово-Ярцевское, вблизи пос. Шишкин лес (ТиНАО) ",
    "Курирующий зам. пред. МКА": "Ильин А.Ю.",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Смутчук Б.В.",
    "ГЗК/ГП/ЛД о подготовке": "Не требуется",
    "Ссылка на верхнеуровневый график": "https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271",
    "Ссылка на расширенный график": "None",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "Иванова А.А.",
    "Руководительподразделения": "Агафонкина А.В.",
    "Рук проекта": "Каземирова Л.Р.",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "Подписано",
    "Согласовано Управление МКАСмарт": "График направлен в МКА 12.03.2025",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "6-24/116-26",
    "№": "6",
    "Вид работы": "Град. потенциал\nТиНАО\nОбщая 2024",
    "Наименование проекта": "Подготовка материалов предварительной оценки градостроительного потенциала развития территории, ограниченной МКАД, Калужским шоссе, ул. Адмирала Корнилова и Троицким лесопарком ",
    "Курирующий зам. пред. МКА": "Ильин А.Ю.",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Смутчук Б.В.",
    "ГЗК/ГП/ЛД о подготовке": "Не требуется",
    "Ссылка на верхнеуровневый график": "https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271",
    "Ссылка на расширенный график": "Одобрено на Штабе КРТ",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "Иванова А.А.",
    "Руководительподразделения": "Агафонкина А.В.",
    "Рук проекта": "Каземирова Л.Р.",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "Подписано",
    "Согласовано Управление МКАСмарт": "None",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "6-24/180-26",
    "№": "7",
    "Вид работы": "Град. потенциал\nТиНАО\nОбщая 2024",
    "Наименование проекта": "Подготовка материалов предварительной оценки градостроительного потенциала развития территории, прилегающей к улице Адмирала Корнилова, ТиНАО",
    "Курирующий зам. пред. МКА": "Ильин А.Ю.",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Смутчук Б.В.",
    "ГЗК/ГП/ЛД о подготовке": "Не требуется",
    "Ссылка на верхнеуровневый график": "https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271",
    "Ссылка на расширенный график": "Одобрено на Штабе КРТ",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "Иванова А.А.",
    "Руководительподразделения": "Агафонкина А.В.",
    "Рук проекта": "Каземирова Л.Р.",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "Подписано",
    "Согласовано Управление МКАСмарт": "None",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "6-24/181-26",
    "№": "8",
    "Вид работы": "Град. потенциал\nТиНАО\nОбщая 2024",
    "Наименование проекта": "Разработка градостроительного потенциала развития территории напротив ТК «ФУД-СИТИ» у ст.м. «Корниловская»",
    "Курирующий зам. пред. МКА": "Ильин А.Ю.",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Смутчук Б.В.",
    "ГЗК/ГП/ЛД о подготовке": "Не требуется",
    "Ссылка на верхнеуровневый график": "https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271",
    "Ссылка на расширенный график": "Одобрено на Штабе КРТ",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "Иванова А.А.",
    "Руководительподразделения": "Агафонкина А.В.",
    "Рук проекта": "Каземирова Л.Р.",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "Подписано",
    "Согласовано Управление МКАСмарт": "None",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "3-24/191-26",
    "№": "6",
    "Вид работы": "Град. потенциал\nТиНАО\nОбщая 2024",
    "Наименование проекта": "Подготовка материалов предварительной оценки градостроительного потенциала комплексного развития территории по адресу: г. Москва, пос. Птичное, ул. Центральная, с определением границ и объемов подготовки градостроительного потенциала развития территории",
    "Курирующий зам. пред. МКА": "Ильин А.Ю.",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Смутчук Б.В.",
    "ГЗК/ГП/ЛД о подготовке": "Не требуется",
    "Ссылка на верхнеуровневый график": "https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271",

# Проход по ссылкам внутри первоначального документа и скачка всех файлов по ним

In [9]:
def download_file_stream(url, local_filename):
    with requests.get(url, stream=True) as r:
        r.raise_for_status()
        with open(local_filename, 'wb') as f:
            for chunk in r.iter_content(chunk_size=8192):
                f.write(chunk)
    print(f'Файл успешно сохранён как {local_filename}')

In [10]:
def download_files(source_doc):
    """
    Ищет ссылки внутри source (представляющий собой список из json) и скачивает файлы
    source_doc
    """
    doc_number = 0
    for obj in source_doc:
        doc_number += 1
        link_number = 0
        for k, v in obj.items():
            if v.startswith('http'): # определяем ссылки
                link_number += 1
                base = v.split('/edit')[0]
                link_for_download = base + "/export?format=xlsx"
                local_filename = f'./downloaded_all/{doc_number}_{link_number}.xlsx'
                download_file_stream(url=link_for_download, local_filename=local_filename)

In [11]:
# download_files(list_of_dicts)

# Обработка скачанных excel файлов
Оставляем только те, в которых есть поля:
1. "Разработка материалов утверждаемой части"
2. "Согласование утв. части в АИС СД, утверждение ППМ"

In [12]:
values_to_check = ["Разработка материалов утверждаемой части", "Согласование утв. части в АИС СД, утверждение ППМ"]
def check_values(df):
    value_1_found = False
    value_2_found = False
    for index, row in df.iterrows():
        for cell_value in row.values:
            cell_value = str(cell_value)
            if values_to_check[0] in cell_value:
                value_1_found = True
            if values_to_check[1] in cell_value:
                value_2_found = True
            # if (values_to_check[0] in cell_value) or (values_to_check[1] in cell_value):
            # if values_to_check[0] in row.values:
                # print(row.values)
            # if values_to_check[1] in row.values:
            #     print(f"Найдено! в строке {index}")
            #     pprint(df.iloc[index:])
            if value_1_found or value_2_found:
                return True
    return False

In [13]:
for file in Path('./downloaded_all').iterdir():
    xl = pd.ExcelFile(file)
    sheet_names = xl.sheet_names
    for sheet in sheet_names:
        df = xl.parse(sheet)
        if check_values(df):
            print(f"file = {file} , sheet_name = {sheet}")
        # print(df)

file = downloaded_all\24_1.xlsx , sheet_name = ППТ ТПУ сводный для Костина
file = downloaded_all\24_1.xlsx , sheet_name = ППТ ТПУ ВЕРХНЕУР Петров С.А. (к
file = downloaded_all\24_1.xlsx , sheet_name = ППТ ТПУ Карбышева
file = downloaded_all\24_1.xlsx , sheet_name = ППТ ТПУ СЕРБОР
file = downloaded_all\24_1.xlsx , sheet_name = ППТ ТПУ ЗИЛ
file = downloaded_all\24_1.xlsx , sheet_name = ППТ ТПУ КЕДРОВАЯ
file = downloaded_all\24_1.xlsx , sheet_name = ППТ ТПУ ОСТРОВ МЕЧТЫ
file = downloaded_all\24_1.xlsx , sheet_name = ППТ ТПУ НАР ОПОЛЧЕНИЕ
file = downloaded_all\24_1.xlsx , sheet_name = ППТ ТПУ СТРОГИНО
file = downloaded_all\24_1.xlsx , sheet_name = ППТ ТПУ ЛЕБЕДЯНСК
file = downloaded_all\24_1.xlsx , sheet_name = ППТ ТПУ КЛЕНОВЫЙ
file = downloaded_all\24_1.xlsx , sheet_name = ППТ ТПУ ТРОИЦКАЯ
file = downloaded_all\24_1.xlsx , sheet_name = ППТ ТПУ БИРЮЛЕВО
file = downloaded_all\24_1.xlsx , sheet_name = ППТ ТПУ СОСЕНКИ
file = downloaded_all\24_1.xlsx , sheet_name = ТИПОВОЙ ППТ ТПУ
file = downloaded_all\24_2.xlsx , sheet_name = ППТ ТПУ сводный для Костина
file = downloaded_all\24_2.xlsx , sheet_name = ППТ ТПУ ВЕРХНЕУР Петров С.А. (к
file = downloaded_all\24_2.xlsx , sheet_name = ППТ ТПУ Карбышева
file = downloaded_all\24_2.xlsx , sheet_name = ППТ ТПУ СЕРБОР
file = downloaded_all\24_2.xlsx , sheet_name = ППТ ТПУ ЗИЛ
file = downloaded_all\24_2.xlsx , sheet_name = ППТ ТПУ КЕДРОВАЯ
file = downloaded_all\24_2.xlsx , sheet_name = ППТ ТПУ ОСТРОВ МЕЧТЫ
file = downloaded_all\24_2.xlsx , sheet_name = ППТ ТПУ НАР ОПОЛЧЕНИЕ
file = downloaded_all\24_2.xlsx , sheet_name = ППТ ТПУ СТРОГИНО
file = downloaded_all\24_2.xlsx , sheet_name = ППТ ТПУ ЛЕБЕДЯНСК
file = downloaded_all\24_2.xlsx , sheet_name = ППТ ТПУ КЛЕНОВЫЙ
file = downloaded_all\24_2.xlsx , sheet_name = ППТ ТПУ ТРОИЦКАЯ
file = downloaded_all\24_2.xlsx , sheet_name = ППТ ТПУ БИРЮЛЕВО
file = downloaded_all\24_2.xlsx , sheet_name = ППТ ТПУ СОСЕНКИ
file = downloaded_all\24_2.xlsx , sheet_name = ТИПОВОЙ ППТ ТПУ
file = downloaded_all\25_1.xlsx , sheet_name = ППТ ТПУ сводный для Костина
file = downloaded_all\25_1.xlsx , sheet_name = ППТ ТПУ ВЕРХНЕУР Петров С.А. (к
file = downloaded_all\25_1.xlsx , sheet_name = ППТ ТПУ Карбышева
file = downloaded_all\25_1.xlsx , sheet_name = ППТ ТПУ СЕРБОР
file = downloaded_all\25_1.xlsx , sheet_name = ППТ ТПУ ЗИЛ
file = downloaded_all\25_1.xlsx , sheet_name = ППТ ТПУ КЕДРОВАЯ
file = downloaded_all\25_1.xlsx , sheet_name = ППТ ТПУ ОСТРОВ МЕЧТЫ
file = downloaded_all\25_1.xlsx , sheet_name = ППТ ТПУ НАР ОПОЛЧЕНИЕ
file = downloaded_all\25_1.xlsx , sheet_name = ППТ ТПУ СТРОГИНО
file = downloaded_all\25_1.xlsx , sheet_name = ППТ ТПУ ЛЕБЕДЯНСК
file = downloaded_all\25_1.xlsx , sheet_name = ППТ ТПУ КЛЕНОВЫЙ
file = downloaded_all\25_1.xlsx , sheet_name = ППТ ТПУ ТРОИЦКАЯ
file = downloaded_all\25_1.xlsx , sheet_name = ППТ ТПУ БИРЮЛЕВО
file = downloaded_all\25_1.xlsx , sheet_name = ППТ ТПУ СОСЕНКИ
file = downloaded_all\25_1.xlsx , sheet_name = ТИПОВОЙ ППТ ТПУ
file = downloaded_all\25_2.xlsx , sheet_name = ППТ ТПУ сводный для Костина
file = downloaded_all\25_2.xlsx , sheet_name = ППТ ТПУ ВЕРХНЕУР Петров С.А. (к
file = downloaded_all\25_2.xlsx , sheet_name = ППТ ТПУ Карбышева
file = downloaded_all\25_2.xlsx , sheet_name = ППТ ТПУ СЕРБОР
file = downloaded_all\25_2.xlsx , sheet_name = ППТ ТПУ ЗИЛ
file = downloaded_all\25_2.xlsx , sheet_name = ППТ ТПУ КЕДРОВАЯ
file = downloaded_all\25_2.xlsx , sheet_name = ППТ ТПУ ОСТРОВ МЕЧТЫ
file = downloaded_all\25_2.xlsx , sheet_name = ППТ ТПУ НАР ОПОЛЧЕНИЕ
file = downloaded_all\25_2.xlsx , sheet_name = ППТ ТПУ СТРОГИНО
file = downloaded_all\25_2.xlsx , sheet_name = ППТ ТПУ ЛЕБЕДЯНСК
file = downloaded_all\25_2.xlsx , sheet_name = ППТ ТПУ КЛЕНОВЫЙ
file = downloaded_all\25_2.xlsx , sheet_name = ППТ ТПУ ТРОИЦКАЯ
file = downloaded_all\25_2.xlsx , sheet_name = ППТ ТПУ БИРЮЛЕВО
file = downloaded_all\25_2.xlsx , sheet_name = ППТ ТПУ СОСЕНКИ
file = downloaded_all\25_2.xlsx , sheet_name = ТИПОВОЙ ППТ ТПУ
file = downloaded_all\26_1.xlsx , sheet_name = ППТ ТПУ сводный для Костина
file = downloaded_all\26_1.xlsx , sheet_name = ППТ ТПУ ВЕРХНЕУР Петров С.А. (к
file = downloaded_all\26_1.xlsx , sheet_name = ППТ ТПУ Карбышева
file = downloaded_all\26_1.xlsx , sheet_name = ППТ ТПУ СЕРБОР
file = downloaded_all\26_1.xlsx , sheet_name = ППТ ТПУ ЗИЛ
file = downloaded_all\26_1.xlsx , sheet_name = ППТ ТПУ КЕДРОВАЯ
file = downloaded_all\26_1.xlsx , sheet_name = ППТ ТПУ ОСТРОВ МЕЧТЫ
file = downloaded_all\26_1.xlsx , sheet_name = ППТ ТПУ НАР ОПОЛЧЕНИЕ
file = downloaded_all\26_1.xlsx , sheet_name = ППТ ТПУ СТРОГИНО
file = downloaded_all\26_1.xlsx , sheet_name = ППТ ТПУ ЛЕБЕДЯНСК
file = downloaded_all\26_1.xlsx , sheet_name = ППТ ТПУ КЛЕНОВЫЙ
file = downloaded_all\26_1.xlsx , sheet_name = ППТ ТПУ ТРОИЦКАЯ
file = downloaded_all\26_1.xlsx , sheet_name = ППТ ТПУ БИРЮЛЕВО
file = downloaded_all\26_1.xlsx , sheet_name = ППТ ТПУ СОСЕНКИ
file = downloaded_all\26_1.xlsx , sheet_name = ТИПОВОЙ ППТ ТПУ
file = downloaded_all\26_2.xlsx , sheet_name = ППТ ТПУ сводный для Костина
file = downloaded_all\26_2.xlsx , sheet_name = ППТ ТПУ ВЕРХНЕУР Петров С.А. (к
file = downloaded_all\26_2.xlsx , sheet_name = ППТ ТПУ Карбышева
file = downloaded_all\26_2.xlsx , sheet_name = ППТ ТПУ СЕРБОР
file = downloaded_all\26_2.xlsx , sheet_name = ППТ ТПУ ЗИЛ
file = downloaded_all\26_2.xlsx , sheet_name = ППТ ТПУ КЕДРОВАЯ
file = downloaded_all\26_2.xlsx , sheet_name = ППТ ТПУ ОСТРОВ МЕЧТЫ
file = downloaded_all\26_2.xlsx , sheet_name = ППТ ТПУ НАР ОПОЛЧЕНИЕ
file = downloaded_all\26_2.xlsx , sheet_name = ППТ ТПУ СТРОГИНО
file = downloaded_all\26_2.xlsx , sheet_name = ППТ ТПУ ЛЕБЕДЯНСК
file = downloaded_all\26_2.xlsx , sheet_name = ППТ ТПУ КЛЕНОВЫЙ
file = downloaded_all\26_2.xlsx , sheet_name = ППТ ТПУ ТРОИЦКАЯ
file = downloaded_all\26_2.xlsx , sheet_name = ППТ ТПУ БИРЮЛЕВО
file = downloaded_all\26_2.xlsx , sheet_name = ППТ ТПУ СОСЕНКИ
file = downloaded_all\26_2.xlsx , sheet_name = ТИПОВОЙ ППТ ТПУ
file = downloaded_all\27_1.xlsx , sheet_name = ППТ ТПУ сводный для Костина
file = downloaded_all\27_1.xlsx , sheet_name = ППТ ТПУ ВЕРХНЕУР Петров С.А. (к
file = downloaded_all\27_1.xlsx , sheet_name = ППТ ТПУ Карбышева
file = downloaded_all\27_1.xlsx , sheet_name = ППТ ТПУ СЕРБОР
file = downloaded_all\27_1.xlsx , sheet_name = ППТ ТПУ ЗИЛ
file = downloaded_all\27_1.xlsx , sheet_name = ППТ ТПУ КЕДРОВАЯ
file = downloaded_all\27_1.xlsx , sheet_name = ППТ ТПУ ОСТРОВ МЕЧТЫ
file = downloaded_all\27_1.xlsx , sheet_name = ППТ ТПУ НАР ОПОЛЧЕНИЕ
file = downloaded_all\27_1.xlsx , sheet_name = ППТ ТПУ СТРОГИНО
file = downloaded_all\27_1.xlsx , sheet_name = ППТ ТПУ ЛЕБЕДЯНСК
file = downloaded_all\27_1.xlsx , sheet_name = ППТ ТПУ КЛЕНОВЫЙ
file = downloaded_all\27_1.xlsx , sheet_name = ППТ ТПУ ТРОИЦКАЯ
file = downloaded_all\27_1.xlsx , sheet_name = ППТ ТПУ БИРЮЛЕВО
file = downloaded_all\27_1.xlsx , sheet_name = ППТ ТПУ СОСЕНКИ
file = downloaded_all\27_1.xlsx , sheet_name = ТИПОВОЙ ППТ ТПУ
file = downloaded_all\27_2.xlsx , sheet_name = ППТ ТПУ сводный для Костина
file = downloaded_all\27_2.xlsx , sheet_name = ППТ ТПУ ВЕРХНЕУР Петров С.А. (к
file = downloaded_all\27_2.xlsx , sheet_name = ППТ ТПУ Карбышева
file = downloaded_all\27_2.xlsx , sheet_name = ППТ ТПУ СЕРБОР
file = downloaded_all\27_2.xlsx , sheet_name = ППТ ТПУ ЗИЛ
file = downloaded_all\27_2.xlsx , sheet_name = ППТ ТПУ КЕДРОВАЯ
file = downloaded_all\27_2.xlsx , sheet_name = ППТ ТПУ ОСТРОВ МЕЧТЫ
file = downloaded_all\27_2.xlsx , sheet_name = ППТ ТПУ НАР ОПОЛЧЕНИЕ
file = downloaded_all\27_2.xlsx , sheet_name = ППТ ТПУ СТРОГИНО
file = downloaded_all\27_2.xlsx , sheet_name = ППТ ТПУ ЛЕБЕДЯНСК
file = downloaded_all\27_2.xlsx , sheet_name = ППТ ТПУ КЛЕНОВЫЙ
file = downloaded_all\27_2.xlsx , sheet_name = ППТ ТПУ ТРОИЦКАЯ
file = downloaded_all\27_2.xlsx , sheet_name = ППТ ТПУ БИРЮЛЕВО
file = downloaded_all\27_2.xlsx , sheet_name = ППТ ТПУ СОСЕНКИ
file = downloaded_all\27_2.xlsx , sheet_name = ТИПОВОЙ ППТ ТПУ
file = downloaded_all\28_1.xlsx , sheet_name = ППТ ТПУ сводный для Костина
file = downloaded_all\28_1.xlsx , sheet_name = ППТ ТПУ ВЕРХНЕУР Петров С.А. (к
file = downloaded_all\28_1.xlsx , sheet_name = ППТ ТПУ Карбышева
file = downloaded_all\28_1.xlsx , sheet_name = ППТ ТПУ СЕРБОР
file = downloaded_all\28_1.xlsx , sheet_name = ППТ ТПУ ЗИЛ
file = downloaded_all\28_1.xlsx , sheet_name = ППТ ТПУ КЕДРОВАЯ
file = downloaded_all\28_1.xlsx , sheet_name = ППТ ТПУ ОСТРОВ МЕЧТЫ
file = downloaded_all\28_1.xlsx , sheet_name = ППТ ТПУ НАР ОПОЛЧЕНИЕ
file = downloaded_all\28_1.xlsx , sheet_name = ППТ ТПУ СТРОГИНО
file = downloaded_all\28_1.xlsx , sheet_name = ППТ ТПУ ЛЕБЕДЯНСК
file = downloaded_all\28_1.xlsx , sheet_name = ППТ ТПУ КЛЕНОВЫЙ
file = downloaded_all\28_1.xlsx , sheet_name = ППТ ТПУ ТРОИЦКАЯ
file = downloaded_all\28_1.xlsx , sheet_name = ППТ ТПУ БИРЮЛЕВО
file = downloaded_all\28_1.xlsx , sheet_name = ППТ ТПУ СОСЕНКИ
file = downloaded_all\28_1.xlsx , sheet_name = ТИПОВОЙ ППТ ТПУ
file = downloaded_all\28_2.xlsx , sheet_name = ППТ ТПУ сводный для Костина
file = downloaded_all\28_2.xlsx , sheet_name = ППТ ТПУ ВЕРХНЕУР Петров С.А. (к
file = downloaded_all\28_2.xlsx , sheet_name = ППТ ТПУ Карбышева
file = downloaded_all\28_2.xlsx , sheet_name = ППТ ТПУ СЕРБОР
file = downloaded_all\28_2.xlsx , sheet_name = ППТ ТПУ ЗИЛ
file = downloaded_all\28_2.xlsx , sheet_name = ППТ ТПУ КЕДРОВАЯ
file = downloaded_all\28_2.xlsx , sheet_name = ППТ ТПУ ОСТРОВ МЕЧТЫ
file = downloaded_all\28_2.xlsx , sheet_name = ППТ ТПУ НАР ОПОЛЧЕНИЕ
file = downloaded_all\28_2.xlsx , sheet_name = ППТ ТПУ СТРОГИНО
file = downloaded_all\28_2.xlsx , sheet_name = ППТ ТПУ ЛЕБЕДЯНСК
file = downloaded_all\28_2.xlsx , sheet_name = ППТ ТПУ КЛЕНОВЫЙ
file = downloaded_all\28_2.xlsx , sheet_name = ППТ ТПУ ТРОИЦКАЯ
file = downloaded_all\28_2.xlsx , sheet_name = ППТ ТПУ БИРЮЛЕВО
file = downloaded_all\28_2.xlsx , sheet_name = ППТ ТПУ СОСЕНКИ
file = downloaded_all\28_2.xlsx , sheet_name = ТИПОВОЙ ППТ ТПУ
file = downloaded_all\29_1.xlsx , sheet_name = ППТ ТПУ сводный для Костина
file = downloaded_all\29_1.xlsx , sheet_name = ППТ ТПУ ВЕРХНЕУР Петров С.А. (к
file = downloaded_all\29_1.xlsx , sheet_name = ППТ ТПУ Карбышева
file = downloaded_all\29_1.xlsx , sheet_name = ППТ ТПУ СЕРБОР
file = downloaded_all\29_1.xlsx , sheet_name = ППТ ТПУ ЗИЛ
file = downloaded_all\29_1.xlsx , sheet_name = ППТ ТПУ КЕДРОВАЯ
file = downloaded_all\29_1.xlsx , sheet_name = ППТ ТПУ ОСТРОВ МЕЧТЫ
file = downloaded_all\29_1.xlsx , sheet_name = ППТ ТПУ НАР ОПОЛЧЕНИЕ
file = downloaded_all\29_1.xlsx , sheet_name = ППТ ТПУ СТРОГИНО
file = downloaded_all\29_1.xlsx , sheet_name = ППТ ТПУ ЛЕБЕДЯНСК
file = downloaded_all\29_1.xlsx , sheet_name = ППТ ТПУ КЛЕНОВЫЙ
file = downloaded_all\29_1.xlsx , sheet_name = ППТ ТПУ ТРОИЦКАЯ
file = downloaded_all\29_1.xlsx , sheet_name = ППТ ТПУ БИРЮЛЕВО
file = downloaded_all\29_1.xlsx , sheet_name = ППТ ТПУ СОСЕНКИ
file = downloaded_all\29_1.xlsx , sheet_name = ТИПОВОЙ ППТ ТПУ
file = downloaded_all\29_2.xlsx , sheet_name = ППТ ТПУ сводный для Костина
file = downloaded_all\29_2.xlsx , sheet_name = ППТ ТПУ ВЕРХНЕУР Петров С.А. (к
file = downloaded_all\29_2.xlsx , sheet_name = ППТ ТПУ Карбышева
file = downloaded_all\29_2.xlsx , sheet_name = ППТ ТПУ СЕРБОР
file = downloaded_all\29_2.xlsx , sheet_name = ППТ ТПУ ЗИЛ
file = downloaded_all\29_2.xlsx , sheet_name = ППТ ТПУ КЕДРОВАЯ
file = downloaded_all\29_2.xlsx , sheet_name = ППТ ТПУ ОСТРОВ МЕЧТЫ
file = downloaded_all\29_2.xlsx , sheet_name = ППТ ТПУ НАР ОПОЛЧЕНИЕ
file = downloaded_all\29_2.xlsx , sheet_name = ППТ ТПУ СТРОГИНО
file = downloaded_all\29_2.xlsx , sheet_name = ППТ ТПУ ЛЕБЕДЯНСК
file = downloaded_all\29_2.xlsx , sheet_name = ППТ ТПУ КЛЕНОВЫЙ
file = downloaded_all\29_2.xlsx , sheet_name = ППТ ТПУ ТРОИЦКАЯ
file = downloaded_all\29_2.xlsx , sheet_name = ППТ ТПУ БИРЮЛЕВО
file = downloaded_all\29_2.xlsx , sheet_name = ППТ ТПУ СОСЕНКИ
file = downloaded_all\29_2.xlsx , sheet_name = ТИПОВОЙ ППТ ТПУ
file = downloaded_all\30_1.xlsx , sheet_name = ППТ ТПУ сводный для Костина
file = downloaded_all\30_1.xlsx , sheet_name = ППТ ТПУ ВЕРХНЕУР Петров С.А. (к
file = downloaded_all\30_1.xlsx , sheet_name = ППТ ТПУ Карбышева
file = downloaded_all\30_1.xlsx , sheet_name = ППТ ТПУ СЕРБОР
file = downloaded_all\30_1.xlsx , sheet_name = ППТ ТПУ ЗИЛ
file = downloaded_all\30_1.xlsx , sheet_name = ППТ ТПУ КЕДРОВАЯ
file = downloaded_all\30_1.xlsx , sheet_name = ППТ ТПУ ОСТРОВ МЕЧТЫ
file = downloaded_all\30_1.xlsx , sheet_name = ППТ ТПУ НАР ОПОЛЧЕНИЕ
file = downloaded_all\30_1.xlsx , sheet_name = ППТ ТПУ СТРОГИНО
file = downloaded_all\30_1.xlsx , sheet_name = ППТ ТПУ ЛЕБЕДЯНСК
file = downloaded_all\30_1.xlsx , sheet_name = ППТ ТПУ КЛЕНОВЫЙ
file = downloaded_all\30_1.xlsx , sheet_name = ППТ ТПУ ТРОИЦКАЯ
file = downloaded_all\30_1.xlsx , sheet_name = ППТ ТПУ БИРЮЛЕВО
file = downloaded_all\30_1.xlsx , sheet_name = ППТ ТПУ СОСЕНКИ
file = downloaded_all\30_1.xlsx , sheet_name = ТИПОВОЙ ППТ ТПУ
file = downloaded_all\30_2.xlsx , sheet_name = ППТ ТПУ сводный для Костина
file = downloaded_all\30_2.xlsx , sheet_name = ППТ ТПУ ВЕРХНЕУР Петров С.А. (к
file = downloaded_all\30_2.xlsx , sheet_name = ППТ ТПУ Карбышева
file = downloaded_all\30_2.xlsx , sheet_name = ППТ ТПУ СЕРБОР
file = downloaded_all\30_2.xlsx , sheet_name = ППТ ТПУ ЗИЛ
file = downloaded_all\30_2.xlsx , sheet_name = ППТ ТПУ КЕДРОВАЯ
file = downloaded_all\30_2.xlsx , sheet_name = ППТ ТПУ ОСТРОВ МЕЧТЫ
file = downloaded_all\30_2.xlsx , sheet_name = ППТ ТПУ НАР ОПОЛЧЕНИЕ
file = downloaded_all\30_2.xlsx , sheet_name = ППТ ТПУ СТРОГИНО
file = downloaded_all\30_2.xlsx , sheet_name = ППТ ТПУ ЛЕБЕДЯНСК
file = downloaded_all\30_2.xlsx , sheet_name = ППТ ТПУ КЛЕНОВЫЙ
file = downloaded_all\30_2.xlsx , sheet_name = ППТ ТПУ ТРОИЦКАЯ
file = downloaded_all\30_2.xlsx , sheet_name = ППТ ТПУ БИРЮЛЕВО
file = downloaded_all\30_2.xlsx , sheet_name = ППТ ТПУ СОСЕНКИ
file = downloaded_all\30_2.xlsx , sheet_name = ТИПОВОЙ ППТ ТПУ
file = downloaded_all\31_1.xlsx , sheet_name = ППТ ТПУ сводный для Костина
file = downloaded_all\31_1.xlsx , sheet_name = ППТ ТПУ ВЕРХНЕУР Петров С.А. (к
file = downloaded_all\31_1.xlsx , sheet_name = ППТ ТПУ Карбышева
file = downloaded_all\31_1.xlsx , sheet_name = ППТ ТПУ СЕРБОР
file = downloaded_all\31_1.xlsx , sheet_name = ППТ ТПУ ЗИЛ
file = downloaded_all\31_1.xlsx , sheet_name = ППТ ТПУ КЕДРОВАЯ
file = downloaded_all\31_1.xlsx , sheet_name = ППТ ТПУ ОСТРОВ МЕЧТЫ
file = downloaded_all\31_1.xlsx , sheet_name = ППТ ТПУ НАР ОПОЛЧЕНИЕ
file = downloaded_all\31_1.xlsx , sheet_name = ППТ ТПУ СТРОГИНО
file = downloaded_all\31_1.xlsx , sheet_name = ППТ ТПУ ЛЕБЕДЯНСК
file = downloaded_all\31_1.xlsx , sheet_name = ППТ ТПУ КЛЕНОВЫЙ
file = downloaded_all\31_1.xlsx , sheet_name = ППТ ТПУ ТРОИЦКАЯ
file = downloaded_all\31_1.xlsx , sheet_name = ППТ ТПУ БИРЮЛЕВО
file = downloaded_all\31_1.xlsx , sheet_name = ППТ ТПУ СОСЕНКИ
file = downloaded_all\31_1.xlsx , sheet_name = ТИПОВОЙ ППТ ТПУ
file = downloaded_all\31_2.xlsx , sheet_name = ППТ ТПУ сводный для Костина
file = downloaded_all\31_2.xlsx , sheet_name = ППТ ТПУ ВЕРХНЕУР Петров С.А. (к
file = downloaded_all\31_2.xlsx , sheet_name = ППТ ТПУ Карбышева
file = downloaded_all\31_2.xlsx , sheet_name = ППТ ТПУ СЕРБОР
file = downloaded_all\31_2.xlsx , sheet_name = ППТ ТПУ ЗИЛ
file = downloaded_all\31_2.xlsx , sheet_name = ППТ ТПУ КЕДРОВАЯ
file = downloaded_all\31_2.xlsx , sheet_name = ППТ ТПУ ОСТРОВ МЕЧТЫ
file = downloaded_all\31_2.xlsx , sheet_name = ППТ ТПУ НАР ОПОЛЧЕНИЕ
file = downloaded_all\31_2.xlsx , sheet_name = ППТ ТПУ СТРОГИНО
file = downloaded_all\31_2.xlsx , sheet_name = ППТ ТПУ ЛЕБЕДЯНСК
file = downloaded_all\31_2.xlsx , sheet_name = ППТ ТПУ КЛЕНОВЫЙ
file = downloaded_all\31_2.xlsx , sheet_name = ППТ ТПУ ТРОИЦКАЯ
file = downloaded_all\31_2.xlsx , sheet_name = ППТ ТПУ БИРЮЛЕВО
file = downloaded_all\31_2.xlsx , sheet_name = ППТ ТПУ СОСЕНКИ
file = downloaded_all\31_2.xlsx , sheet_name = ТИПОВОЙ ППТ ТПУ
file = downloaded_all\32_1.xlsx , sheet_name = ППТ ТПУ сводный для Костина
file = downloaded_all\32_1.xlsx , sheet_name = ППТ ТПУ ВЕРХНЕУР Петров С.А. (к
file = downloaded_all\32_1.xlsx , sheet_name = ППТ ТПУ Карбышева
file = downloaded_all\32_1.xlsx , sheet_name = ППТ ТПУ СЕРБОР
file = downloaded_all\32_1.xlsx , sheet_name = ППТ ТПУ ЗИЛ
file = downloaded_all\32_1.xlsx , sheet_name = ППТ ТПУ КЕДРОВАЯ
file = downloaded_all\32_1.xlsx , sheet_name = ППТ ТПУ ОСТРОВ МЕЧТЫ
file = downloaded_all\32_1.xlsx , sheet_name = ППТ ТПУ НАР ОПОЛЧЕНИЕ
file = downloaded_all\32_1.xlsx , sheet_name = ППТ ТПУ СТРОГИНО
file = downloaded_all\32_1.xlsx , sheet_name = ППТ ТПУ ЛЕБЕДЯНСК
file = downloaded_all\32_1.xlsx , sheet_name = ППТ ТПУ КЛЕНОВЫЙ
file = downloaded_all\32_1.xlsx , sheet_name = ППТ ТПУ ТРОИЦКАЯ
file = downloaded_all\32_1.xlsx , sheet_name = ППТ ТПУ БИРЮЛЕВО
file = downloaded_all\32_1.xlsx , sheet_name = ППТ ТПУ СОСЕНКИ
file = downloaded_all\32_1.xlsx , sheet_name = ТИПОВОЙ ППТ ТПУ
file = downloaded_all\32_2.xlsx , sheet_name = ППТ ТПУ сводный для Костина
file = downloaded_all\32_2.xlsx , sheet_name = ППТ ТПУ ВЕРХНЕУР Петров С.А. (к
file = downloaded_all\32_2.xlsx , sheet_name = ППТ ТПУ Карбышева
file = downloaded_all\32_2.xlsx , sheet_name = ППТ ТПУ СЕРБОР
file = downloaded_all\32_2.xlsx , sheet_name = ППТ ТПУ ЗИЛ
file = downloaded_all\32_2.xlsx , sheet_name = ППТ ТПУ КЕДРОВАЯ
file = downloaded_all\32_2.xlsx , sheet_name = ППТ ТПУ ОСТРОВ МЕЧТЫ
file = downloaded_all\32_2.xlsx , sheet_name = ППТ ТПУ НАР ОПОЛЧЕНИЕ
file = downloaded_all\32_2.xlsx , sheet_name = ППТ ТПУ СТРОГИНО
file = downloaded_all\32_2.xlsx , sheet_name = ППТ ТПУ ЛЕБЕДЯНСК
file = downloaded_all\32_2.xlsx , sheet_name = ППТ ТПУ КЛЕНОВЫЙ
file = downloaded_all\32_2.xlsx , sheet_name = ППТ ТПУ ТРОИЦКАЯ
file = downloaded_all\32_2.xlsx , sheet_name = ППТ ТПУ БИРЮЛЕВО
file = downloaded_all\32_2.xlsx , sheet_name = ППТ ТПУ СОСЕНКИ
file = downloaded_all\32_2.xlsx , sheet_name = ТИПОВОЙ ППТ ТПУ
file = downloaded_all\33_1.xlsx , sheet_name = ППТ ТПУ сводный для Костина
file = downloaded_all\33_1.xlsx , sheet_name = ППТ ТПУ ВЕРХНЕУР Петров С.А. (к
file = downloaded_all\33_1.xlsx , sheet_name = ППТ ТПУ Карбышева
file = downloaded_all\33_1.xlsx , sheet_name = ППТ ТПУ СЕРБОР
file = downloaded_all\33_1.xlsx , sheet_name = ППТ ТПУ ЗИЛ
file = downloaded_all\33_1.xlsx , sheet_name = ППТ ТПУ КЕДРОВАЯ
file = downloaded_all\33_1.xlsx , sheet_name = ППТ ТПУ ОСТРОВ МЕЧТЫ
file = downloaded_all\33_1.xlsx , sheet_name = ППТ ТПУ НАР ОПОЛЧЕНИЕ
file = downloaded_all\33_1.xlsx , sheet_name = ППТ ТПУ СТРОГИНО
file = downloaded_all\33_1.xlsx , sheet_name = ППТ ТПУ ЛЕБЕДЯНСК
file = downloaded_all\33_1.xlsx , sheet_name = ППТ ТПУ КЛЕНОВЫЙ
file = downloaded_all\33_1.xlsx , sheet_name = ППТ ТПУ ТРОИЦКАЯ
file = downloaded_all\33_1.xlsx , sheet_name = ППТ ТПУ БИРЮЛЕВО
file = downloaded_all\33_1.xlsx , sheet_name = ППТ ТПУ СОСЕНКИ
file = downloaded_all\33_1.xlsx , sheet_name = ТИПОВОЙ ППТ ТПУ
file = downloaded_all\33_2.xlsx , sheet_name = ППТ ТПУ сводный для Костина
file = downloaded_all\33_2.xlsx , sheet_name = ППТ ТПУ ВЕРХНЕУР Петров С.А. (к
file = downloaded_all\33_2.xlsx , sheet_name = ППТ ТПУ Карбышева
file = downloaded_all\33_2.xlsx , sheet_name = ППТ ТПУ СЕРБОР
file = downloaded_all\33_2.xlsx , sheet_name = ППТ ТПУ ЗИЛ
file = downloaded_all\33_2.xlsx , sheet_name = ППТ ТПУ КЕДРОВАЯ
file = downloaded_all\33_2.xlsx , sheet_name = ППТ ТПУ ОСТРОВ МЕЧТЫ
file = downloaded_all\33_2.xlsx , sheet_name = ППТ ТПУ НАР ОПОЛЧЕНИЕ
file = downloaded_all\33_2.xlsx , sheet_name = ППТ ТПУ СТРОГИНО
file = downloaded_all\33_2.xlsx , sheet_name = ППТ ТПУ ЛЕБЕДЯНСК
file = downloaded_all\33_2.xlsx , sheet_name = ППТ ТПУ КЛЕНОВЫЙ
file = downloaded_all\33_2.xlsx , sheet_name = ППТ ТПУ ТРОИЦКАЯ
file = downloaded_all\33_2.xlsx , sheet_name = ППТ ТПУ БИРЮЛЕВО
file = downloaded_all\33_2.xlsx , sheet_name = ППТ ТПУ СОСЕНКИ
file = downloaded_all\33_2.xlsx , sheet_name = ТИПОВОЙ ППТ ТПУ
file = downloaded_all\34_1.xlsx , sheet_name = ППТ ТПУ сводный для Костина
file = downloaded_all\34_1.xlsx , sheet_name = ППТ ТПУ ВЕРХНЕУР Петров С.А. (к
file = downloaded_all\34_1.xlsx , sheet_name = ППТ ТПУ Карбышева

PermissionError: [Errno 13] Permission denied: 'downloaded_all\\~$25_2.xlsx'

In [367]:
# найденные файлы 'and': file = downloaded_all\8_1.xlsx , sheet_name = верхнеуровневый график - "Разработка материалов утверждаемой части"
# найденные файлы 'or':

In [368]:
# Assign spreadsheet filename to `file`
# file_2 = 'https://docs.google.com/spreadsheets/d/1yBQ6dCzx2W4jtxffRjmhDaw7MAjyeu06yGGHqbYHoiw/edit?gid=1991169065#gid=1991169065'
file = './data/График ППТ 10% Рябиновая.xlsx'

# Load spreadsheet
xl = pd.ExcelFile(file)

# Print the sheet names
sheet_names = xl.sheet_names
print(sheet_names)

# Load a sheet into a DataFrame by name: df1
df2 = xl.parse(sheet_names[0])

['верхнеуровневый график']

In [369]:
df2

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,Согласовано:,NaN,NaN,NaN,Согласовано:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Москомархитектура,NaN,NaN,NaN,ГАУ «Институт Генплана Москвы»,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Заместитель председателя,NaN,NaN,А.Ю.Ильин,Первый заместитель директора/\nКурирующий заме...,NaN,NaN,И.А. Бахирев,NaN,NaN,NaN,NaN,NaN,NaN
3,Начальник Управления,NaN,NaN,NaN,Руководитель НПО УДС,NaN,NaN,С.С. Сигаев,NaN,NaN,NaN,NaN,NaN,NaN
4,Ответственный исполнитель \nУправления,NaN,NaN,NaN,Ответственный исполнитель,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Проект внесения изменений в ППМ от 29.02.2024 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,1. Разработка материалов утверждаемой части,NaN,"2. Согласование утв. части в АИС СД, утвержден...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,Направление заявки,подготовка Утв. Части,Проверка УЧ в кур. Управлении и ПУ МКА,"Устранение замеч ПУ МКА, загрузка в АИС СД",АИС СД УКД,АИС СД ОИВ,Согласование с Росимуществом и ФАЖТ,Согласование с Мособластью,Прохождение МГЭ,Доработка материалов по замечаниям ОИВ,проверка в ПУ МКА,"Прохождение ПУ ПМ, корректировка по замеч., по...",ОАУ ПМ
10,NaN,8,30,7,7,14,14,0,0,0,14,3,30,7
11,Дата план,выполнено,выполнено,выполнено,2025-04-15 00:00:00,2025-04-29 00:00:00,2025-05-13 00:00:00,не требуется,не требуется,не требуется,2025-05-27 00:00:00,2025-05-30 00:00:00,2025-06-29 00:00:00,2025-07-06 00:00:00

In [370]:
check_values(df2)

True