In [1]:
# -*- coding: utf-8 -*-
import json
from itertools import count

import pandas as pd
import requests
from pathlib import Path
from tabulate import tabulate
from pprint import pprint

In [2]:
# Assign spreadsheet filename to `file`
file = './data/Сводный перечень текущих работ для графиков.xlsx'

# Load spreadsheet
xl = pd.ExcelFile(file)

# Print the sheet names
sheet_names = xl.sheet_names
print(sheet_names)

# Load a sheet into a DataFrame by name: df1
df1 = xl.parse(sheet_names[0])

['ПЕРЕЧЕНЬ ГЗ - 2025']

In [3]:
print(df1.shape)
df1

(207, 19)

,Шифр работы,№,Вид \nработы,Наименование проекта,Курирующий зам. пред. МКА,Руководитель отраслевого управления,Администрат\nУКПД,ГЗК/ГП/ЛД о подготовке,Ссылка на верхнеуровневый график,Ссылка на расширенный график,Месяц \nутверждения,Курирующий Зам. Директора,Руководитель\nподразделения,Рук проекта,СМАРТ,Согласовано Генплан\nСмарт,Согласовано Управление МКА\nСмарт,Согласовано Курирующим Зам\nСмарт,Unnamed: 18
0,6-20/133-26,NaN,ППТ,Подготовка проекта планировки территории по ад...,Ильин А.Ю.,Шабалдина Е.А.,Белоусова Т.С.,от 26 марта 2020 г. № 9 п. 5\nот 03 февраля 20...,Прииостановлено.\nГрафик будет подготовлен пос...,Прииостановлено.\nГрафик будет подготовлен пос...,NaT,Иванова А.А.,Агафонкина А.В.,Лапина О.И.,NaN,NaN,NaN,NaN,NaN
1,41-21/153-26,NaN,ППТ,"Проект планировки территории, ограниченной Пер...",Ильин А.Ю.,Шабалдина Е.А.,Белоусова Т.С.,п.4 №12 от 01.04.2021,Прииостановлено.\nГрафик будет подготовлен пос...,Прииостановлено.\nГрафик будет подготовлен пос...,NaT,Иванова А.А.,Агафонкина А.В.,Соловьянова Е.А.,NaN,NaN,NaN,NaN,NaN
2,6-22/162-26,1,ППТ,Подготовка проекта планировки территории Киевс...,Ильин А.Ю.,Шабалдина Е.А.,Белоусова Т.С.,Протокол № 8 п. 17 от 10.03.2022,https://docs.google.com/spreadsheets/d/1BIG1oo...,https://docs.google.com/spreadsheets/d/1BIG1oo...,NaT,Иванова А.А.,Глушко М.М.,Асатрян А.А.,NaN,Подписано,График направлен в МКА 12.03.2025,NaN,NaN
3,23/224-26,NaN,ППТ,Подготовка проекта планировки территории посел...,Ильин А.Ю.,Шабалдина Е.А.,Владимиров А.А.,Протокол от 26.10.2023 №32 п. 15,"Прииостановлено, нет согласовонного варианта\n...","Прииостановлено, нет согласовонного варианта\n...",NaT,Иванова А.А.,Агафонкина А.В.,Соловьянова Е.А.,NaN,NaN,NaN,NaN,NaN
4,6-24/196-26,2,ППТ,"Подготовка проекта планировки территории, огра...",Ильин А.Ю.,Шабалдина Е.А.,Владимиров А.А.,Протокол от 29.05.2024 № 18 п.72,https://docs.google.com/spreadsheets/d/1BIG1oo...,https://docs.google.com/spreadsheets/d/1BIG1oo...,NaT,Иванова А.А.,Агафонкина А.В.,Лапина О.И.,NaN,Подписано,График направлен в МКА 12.03.2025,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,NaN,6,ППТ ЛО,Подготовка проекта планировки территории линей...,NaN,Конюкова А.А.,Шпынев В.А.,от 14.11.2024 №39 п.10,https://docs.google.com/spreadsheets/d/1BwkwUa...,https://docs.google.com/spreadsheets/d/1BwkwUa...,NaT,И.А. Бахирев,НПО РУДС / С.С. Сигаев,Исмаилов А.А.,NaN,NaN,NaN,NaN,NaN
203,NaN,7,ППТ ЛО,Подготовка проекта планировки территории линей...,NaN,Конюкова А.А.,Шпынев В.А.,от 14.11.2024 №39 п.10,https://docs.google.com/spreadsheets/d/14gkaV3...,https://docs.google.com/spreadsheets/d/14gkaV3...,NaT,И.А. Бахирев,НПО РУДС / С.С. Сигаев,Исмаилов А.А.,NaN,NaN,NaN,NaN,NaN
204,NaN,NaN,10% ППТ ЛО УДС,Подготовка проекта внесения изменений в постан...,NaN,Конюкова А.А.,Иванова М.С.,NaN,Объекты ЛО (М.Е. Кандыбайло),"Делаем верхнеуровневый, \n объект на утверждении",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,NaN,NaN,10% ППТ ЛО УДС,Подготовка проекта внесения изменений в Постан...,NaN,Конюкова А.А.,Иванова М.С.,NaN,Объекты ЛО (М.Е. Кандыбайло),"Делаем верхнеуровневый, \n объект на утверждении",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,NaN,NaN,10% ППТ ЛО УДС,Подготовка проекта изменений в постановление П...,NaN,Конюкова А.А.,Иванова М.С.,NaN,Объекты ЛО (М.Е. Кандыбайло),"Делаем верхнеуровневый, \n объект на утверждении",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# удалим строки, в которых все значения NaN
df1.dropna(axis=0, how='all', inplace=True)
print(df1.shape)
print(df1.dtypes)
df1

(196, 19)
Шифр работы                                    object
№                                              object
Вид \nработы                                   object
Наименование проекта                           object
Курирующий зам. пред. МКА                      object
Руководитель отраслевого управления            object
Администрат\nУКПД                              object
ГЗК/ГП/ЛД о подготовке                         object
Ссылка на верхнеуровневый график               object
Ссылка на расширенный график                   object
Месяц \nутверждения                    datetime64[ns]
Курирующий Зам. Директора                      object
Руководитель\nподразделения                    object
Рук проекта                                    object
 СМАРТ                                        float64
Согласовано Генплан\nСмарт                     object
Согласовано Управление МКА\nСмарт              object
Согласовано Курирующим Зам\nСмарт              object
Unnamed: 18                                    object
dtype: object

,Шифр работы,№,Вид \nработы,Наименование проекта,Курирующий зам. пред. МКА,Руководитель отраслевого управления,Администрат\nУКПД,ГЗК/ГП/ЛД о подготовке,Ссылка на верхнеуровневый график,Ссылка на расширенный график,Месяц \nутверждения,Курирующий Зам. Директора,Руководитель\nподразделения,Рук проекта,СМАРТ,Согласовано Генплан\nСмарт,Согласовано Управление МКА\nСмарт,Согласовано Курирующим Зам\nСмарт,Unnamed: 18
0,6-20/133-26,NaN,ППТ,Подготовка проекта планировки территории по ад...,Ильин А.Ю.,Шабалдина Е.А.,Белоусова Т.С.,от 26 марта 2020 г. № 9 п. 5\nот 03 февраля 20...,Прииостановлено.\nГрафик будет подготовлен пос...,Прииостановлено.\nГрафик будет подготовлен пос...,NaT,Иванова А.А.,Агафонкина А.В.,Лапина О.И.,NaN,NaN,NaN,NaN,NaN
1,41-21/153-26,NaN,ППТ,"Проект планировки территории, ограниченной Пер...",Ильин А.Ю.,Шабалдина Е.А.,Белоусова Т.С.,п.4 №12 от 01.04.2021,Прииостановлено.\nГрафик будет подготовлен пос...,Прииостановлено.\nГрафик будет подготовлен пос...,NaT,Иванова А.А.,Агафонкина А.В.,Соловьянова Е.А.,NaN,NaN,NaN,NaN,NaN
2,6-22/162-26,1,ППТ,Подготовка проекта планировки территории Киевс...,Ильин А.Ю.,Шабалдина Е.А.,Белоусова Т.С.,Протокол № 8 п. 17 от 10.03.2022,https://docs.google.com/spreadsheets/d/1BIG1oo...,https://docs.google.com/spreadsheets/d/1BIG1oo...,NaT,Иванова А.А.,Глушко М.М.,Асатрян А.А.,NaN,Подписано,График направлен в МКА 12.03.2025,NaN,NaN
3,23/224-26,NaN,ППТ,Подготовка проекта планировки территории посел...,Ильин А.Ю.,Шабалдина Е.А.,Владимиров А.А.,Протокол от 26.10.2023 №32 п. 15,"Прииостановлено, нет согласовонного варианта\n...","Прииостановлено, нет согласовонного варианта\n...",NaT,Иванова А.А.,Агафонкина А.В.,Соловьянова Е.А.,NaN,NaN,NaN,NaN,NaN
4,6-24/196-26,2,ППТ,"Подготовка проекта планировки территории, огра...",Ильин А.Ю.,Шабалдина Е.А.,Владимиров А.А.,Протокол от 29.05.2024 № 18 п.72,https://docs.google.com/spreadsheets/d/1BIG1oo...,https://docs.google.com/spreadsheets/d/1BIG1oo...,NaT,Иванова А.А.,Агафонкина А.В.,Лапина О.И.,NaN,Подписано,График направлен в МКА 12.03.2025,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,NaN,6,ППТ ЛО,Подготовка проекта планировки территории линей...,NaN,Конюкова А.А.,Шпынев В.А.,от 14.11.2024 №39 п.10,https://docs.google.com/spreadsheets/d/1BwkwUa...,https://docs.google.com/spreadsheets/d/1BwkwUa...,NaT,И.А. Бахирев,НПО РУДС / С.С. Сигаев,Исмаилов А.А.,NaN,NaN,NaN,NaN,NaN
203,NaN,7,ППТ ЛО,Подготовка проекта планировки территории линей...,NaN,Конюкова А.А.,Шпынев В.А.,от 14.11.2024 №39 п.10,https://docs.google.com/spreadsheets/d/14gkaV3...,https://docs.google.com/spreadsheets/d/14gkaV3...,NaT,И.А. Бахирев,НПО РУДС / С.С. Сигаев,Исмаилов А.А.,NaN,NaN,NaN,NaN,NaN
204,NaN,NaN,10% ППТ ЛО УДС,Подготовка проекта внесения изменений в постан...,NaN,Конюкова А.А.,Иванова М.С.,NaN,Объекты ЛО (М.Е. Кандыбайло),"Делаем верхнеуровневый, \n объект на утверждении",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,NaN,NaN,10% ППТ ЛО УДС,Подготовка проекта внесения изменений в Постан...,NaN,Конюкова А.А.,Иванова М.С.,NaN,Объекты ЛО (М.Е. Кандыбайло),"Делаем верхнеуровневый, \n объект на утверждении",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,NaN,NaN,10% ППТ ЛО УДС,Подготовка проекта изменений в постановление П...,NaN,Конюкова А.А.,Иванова М.С.,NaN,Объекты ЛО (М.Е. Кандыбайло),"Делаем верхнеуровневый, \n объект на утверждении",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df1.columns

Index(['Шифр работы', '№', 'Вид \nработы', 'Наименование проекта',
       'Курирующий зам. пред. МКА', 'Руководитель отраслевого управления',
       'Администрат\nУКПД', 'ГЗК/ГП/ЛД о подготовке',
       'Ссылка на верхнеуровневый график', 'Ссылка на расширенный график',
       'Месяц \nутверждения', 'Курирующий Зам. Директора',
       'Руководитель\nподразделения', 'Рук проекта', ' СМАРТ',
       'Согласовано Генплан\nСмарт', 'Согласовано Управление МКА\nСмарт',
       'Согласовано Курирующим Зам\nСмарт', 'Unnamed: 18'],
      dtype='object')

In [6]:
list_of_dicts = df1.to_dict(orient='records')
print(type(list_of_dicts))
list_of_dicts
# for record in list_of_dicts:
#     print(json.dumps(obj=record, indent=4))

<class 'list'>

[{'Шифр работы': '6-20/133-26',
  '№': nan,
  'Вид \nработы': 'ППТ ',
  'Наименование проекта': 'Подготовка проекта планировки территории по адресу: \n3-й Силикатный пр., влд. 10',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'от 26 марта 2020 г. № 9 п. 5\nот 03 февраля 2022 г. № 4, п.2',
  'Ссылка на верхнеуровневый график': 'Прииостановлено.\nГрафик будет подготовлен после решения о продолжении работы ',
  'Ссылка на расширенный график': 'Прииостановлено.\nГрафик будет подготовлен после решения о продолжении работы',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Лапина О.И.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': nan,
  'Согласовано Управление МКА\nСмарт': nan,
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': '41-21/153-26',
  '№': nan,
  'Вид \nработы': 'ППТ ',
  'Наименование проекта': 'Проект планировки территории, ограниченной Пермской улицей, Тагильской улицей, улицей Николая Химушина, Монтажной улицей, Щелковским шоссе, Большой Черкизовской улицей, границей объекта природного комплекса Восточного административного округа города Москвы № 20 «Черкизовский парк», Тюменской улицей, Открытым шоссе, Малым кольцом Московской железной дороги',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'п.4 №12 от 01.04.2021',
  'Ссылка на верхнеуровневый график': 'Прииостановлено.\nГрафик будет подготовлен после решения о продолжении работы',
  'Ссылка на расширенный график': 'Прииостановлено.\nГрафик будет подготовлен после решения о продолжении работы',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Соловьянова Е.А.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': nan,
  'Согласовано Управление МКА\nСмарт': nan,
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': '6-22/162-26',
  '№': 1,
  'Вид \nработы': 'ППТ',
  'Наименование проекта': 'Подготовка проекта планировки территории Киевского вокзала',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'Протокол № 8 п. 17 от 10.03.2022',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=526740403#gid=526740403\nЖдем концепцию развития территории КРТ от Инвестора',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=569099005#gid=569099005\nЖдем концепцию развития территории КРТ от Инвестора',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Глушко М.М.',
  'Рук проекта': 'Асатрян А.А.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': 'Подписано',
  'Согласовано Управление МКА\nСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': '23/224-26',
  '№': nan,
  'Вид \nработы': 'ППТ',
  'Наименование проекта': 'Подготовка проекта планировки территории поселения Воскресенское, части поселка подсобного хозяйства Воскресенское',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Владимиров А.А.',
  'ГЗК/ГП/ЛД о подготовке': 'Протокол от 26.10.2023 №32 п. 15',
  'Ссылка на верхнеуровневый график': 'Прииостановлено, нет согласовонного варианта\nГрафик будет подготовлен после выбора варианта',
  'Ссылка на расширенный график': 'Прииостановлено, нет согласовонного варианта\nГрафик будет подготовлен после выбора варианта',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Соловьянова Е.А.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': nan,
  'Согласовано Управление МКА\nСмарт': nan,
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': '6-24/196-26',
  '№': 2,
  'Вид \nработы': 'ППТ',
  'Наименование проекта': 'Подготовка проекта планировки территории, ограниченной улицей Нижегородской, полосой отвода железной дороги, Южнопортовой улицей, Москвой рекой',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Владимиров А.А.',
  'ГЗК/ГП/ЛД о подготовке': 'Протокол от 29.05.2024 № 18 п.72',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=526740403#gid=526740403',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=670102455#gid=670102455',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Лапина О.И.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': 'Подписано',
  'Согласовано Управление МКА\nСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': '3-25/21-26',
  '№': 3,
  'Вид \nработы': 'ППТ',
  'Наименование проекта': 'Подготовка проекта планировки\nтерритории вблизи деревни\nКрасная Пахра района Троицк города Москвы',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'Протокол от 29.01.2025 № 3 п.3',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=526740403#gid=526740403',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=362904608#gid=362904608',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Глушко М.М.',
  'Рук проекта': 'Логинов А.Л.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': 'Подписано',
  'Согласовано Управление МКА\nСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': nan,
  '№': 3,
  'Вид \nработы': 'ППТ',
  'Наименование проекта': 'Подготовка проекта планировки территории, ограниченной шоссе Энтузиастов, шоссе Фрезер, Горьковским направлением железной дороги, улицей Подъемной',
  'Курирующий зам. пред. МКА': nan,
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Владимиров А.А.',
  'ГЗК/ГП/ЛД о подготовке': nan,
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=526740403#gid=526740403',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=1807994811#gid=1807994811',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Лапина О.И.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': 'Подписано',
  'Согласовано Управление МКА\nСмарт': 'График направлен в МКА 14.03.2025',
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': nan,
  '№': nan,
  'Вид \nработы': '10% ППТ',
  'Наименование проекта': 'Подготовка проекта внесения изменений в постановление Правительства Москвы \nот 29 февраля 2024 г. № 394-ПП «Об утверждении проекта планировки территории между Аминьевским шоссе и Рябиновой улицей»',
  'Курирующий зам. пред. МКА': nan,
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Ломакина Е.А,',
  'ГЗК/ГП/ЛД о подготовке': nan,
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1yBQ6dCzx2W4jtxffRjmhDaw7MAjyeu06yGGHqbYHoiw/edit?gid=1991169065#gid=1991169065',
  'Ссылка на расширенный график': nan,
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': nan,
  'Руководитель\nподразделения': nan,
  'Рук проекта': nan,
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': nan,
  'Согласовано Управление МКА\nСмарт': nan,
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': nan,
  '№': nan,
  'Вид \nработы': '10% ППТ',
  'Наименование проекта': 'Внесение изменений в ППМ от 28.09.2021 № 1501-ПП проект планировки территории, прилегающей к Московским центральным диаметрам: МЦД-1 "Одинцово-Лобня", участок от МКАД до границ города Москвы',
  'Курирующий зам. пред. МКА': nan,
  'Руководитель отраслевого управления': 'Петров С.А.',
  'Администрат\nУКПД': 'Иванова М.С.',
  'ГЗК/ГП/ЛД о подготовке': nan,
  'Ссылка на верхнеуровневый график': 'ГРАФИК 10% ППТ МЦД пеш.переход Одинцово-Лобня',
  'Ссылка на расширенный график': 'не требуется',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': nan,
  'Руководитель\nподразделения': nan,
  'Рук проекта': nan,
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': 'Дата заявки 08.04.\nГрафик в разработке. Идет согласование с генпроектировщиком.',
  'Согласовано Управление МКА\nСмарт': nan,
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': '3-24/218-26',
  '№': 1,
  'Вид \nработы': 'Град. потенциал\nВЛЭП',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала освобождаемых от ВЛЭП территорий в городе Москве по адресу: \nПятницкое шоссе, вл. 4-6, СЗАО',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=355278683#gid=355278683',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Глушко М.М.',
  'Рук проекта': 'Цуканова И.Б.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': 'Подписано',
  'Согласовано Управление МКА\nСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': '3-24/215-26',
  '№': 2,
  'Вид \nработы': 'Град. потенциал\nВЛЭП',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала освобождаемых от ВЛЭП территорий в городе Москве по адресу: \nТерритория ВЛЭП вдоль 2-го Нагатинского проезда, ЮАО',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=516568795#gid=516568795',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Глушко М.М.',
  'Рук проекта': 'Логинов А.Л.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': 'Подписано',
  'Согласовано Управление МКА\nСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': '6-24/237-26',
  '№': 3,
  'Вид \nработы': 'Град. потенциал\nВЛЭП',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала освобождаемых от ВЛЭП территорий в городе Москве по адресу: \nТерритория ВЛЭП от Волжского бульвара вдоль Аллеи Кремлевских курсантов до улицы Чагинской, ЮВАО',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1897185067#gid=1897185067',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Глушко М.М.',
  'Рук проекта': 'Цуканова И.Б.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': 'Подписано',
  'Согласовано Управление МКА\nСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': '3-24/276-26',
  '№': 4,
  'Вид \nработы': 'Град. потенциал\nВЛЭП',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала освобождаемых от ВЛЭП территорий в городе Москве по адресу: территория ВЛЭП вдоль Филевской линии метрополитена от станции «Фили» до бульвара Солдатенкова, ЗАО',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=774182060#gid=774182060',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Глушко М.М.',
  'Рук проекта': 'Логинов А.Л.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': 'Подписано',
  'Согласовано Управление МКА\nСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': '3-23/204-26',
  '№': 5,
  'Вид \nработы': 'Град. потенциал\nТиНАО\nОбщая 2024',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала развития территории по адресу: г. Москва, пос. Михайлово-Ярцевское, вблизи пос. Шишкин лес (ТиНАО) ',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Смутчук Б.В.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': nan,
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Каземирова Л.Р.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': 'Подписано',
  'Согласовано Управление МКА\nСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': '6-24/116-26',
  '№': 6,
  'Вид \nработы': 'Град. потенциал\nТиНАО\nОбщая 2024',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала развития территории, ограниченной МКАД, Калужским шоссе, ул. Адмирала Корнилова и Троицким лесопарком ',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Смутчук Б.В.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'Одобрено на Штабе КРТ',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Каземирова Л.Р.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': 'Подписано',
  'Согласовано Управление МКА\nСмарт': nan,
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': '6-24/180-26',
  '№': 7,
  'Вид \nработы': 'Град. потенциал\nТиНАО\nОбщая 2024',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала развития территории, прилегающей к улице Адмирала Корнилова, ТиНАО',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Смутчук Б.В.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'Одобрено на Штабе КРТ',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Каземирова Л.Р.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': 'Подписано',
  'Согласовано Управление МКА\nСмарт': nan,
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': '6-24/181-26',
  '№': 8,
  'Вид \nработы': 'Град. потенциал\nТиНАО\nОбщая 2024',
  'Наименование проекта': 'Разработка градостроительного потенциала развития территории напротив ТК «ФУД-СИТИ» у ст.м. «Корниловская»',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Смутчук Б.В.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'Одобрено на Штабе КРТ',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Каземирова Л.Р.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': 'Подписано',
  'Согласовано Управление МКА\nСмарт': nan,
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': '3-24/191-26',
  '№': 6,
  'Вид \nработы': 'Град. потенциал\nТиНАО\nОбщая 2024',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала комплексного развития территории по адресу: г. Москва, пос. Птичное, ул. Центральная, с определением границ и объемов подготовки градостроительного потенциала развития территории',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'Администрат\nУКПД': 'Смутчук Б.В.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=31303565#gid=31303565',
  'Месяц \nутверждения': NaT,
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководитель\nподразделения': 'Глушко М.М.',
  'Рук проекта': 'Логинов А.Л.',
  ' СМАРТ': nan,
  'Согласовано Генплан\nСмарт': 'Подписано',
  'Согласовано Управление МКА\nСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим Зам\nСмарт': nan,
  'Unnamed: 18': nan},
 {'Шифр работы': '3-24/224-26',
  '№': 7,
  'Вид \nработы': 'Град. потенциал\nТиНАО\nОбщая 2024',
  'Наименование проекта': 'Разработка материалов предварительной оценки градостроительного потенциала территории по адресу: г. Москва, пос. Вороновское, дер. Львово',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',

In [7]:
# преобразуем все колонки к строковому типу
df1 = df1.astype(str)
df1 = df1.replace({'nan': 'None', 'NaT': 'None'})
# df1 = df1.where('nan', 'None')
# df1 = df1.where('NaT', 'None')
# заменим nan значения на 'None' (или вовсе удалим?)
# df1.fillna('None', inplace=True)
# Убираем ведущие и завершающие пробелы из названий колонок
df1.columns = df1.columns.str.strip()
# Удаляем символы перехода на новую строку из названий колонок
df1.columns = df1.columns.str.replace('\n', '', regex=False)
list_of_dicts = df1.to_dict(orient='records')
list_of_dicts

[{'Шифр работы': '6-20/133-26',
  '№': 'None',
  'Вид работы': 'ППТ ',
  'Наименование проекта': 'Подготовка проекта планировки территории по адресу: \n3-й Силикатный пр., влд. 10',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'от 26 марта 2020 г. № 9 п. 5\nот 03 февраля 2022 г. № 4, п.2',
  'Ссылка на верхнеуровневый график': 'Прииостановлено.\nГрафик будет подготовлен после решения о продолжении работы ',
  'Ссылка на расширенный график': 'Прииостановлено.\nГрафик будет подготовлен после решения о продолжении работы',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Лапина О.И.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'None',
  'Согласовано Управление МКАСмарт': 'None',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': '41-21/153-26',
  '№': 'None',
  'Вид работы': 'ППТ ',
  'Наименование проекта': 'Проект планировки территории, ограниченной Пермской улицей, Тагильской улицей, улицей Николая Химушина, Монтажной улицей, Щелковским шоссе, Большой Черкизовской улицей, границей объекта природного комплекса Восточного административного округа города Москвы № 20 «Черкизовский парк», Тюменской улицей, Открытым шоссе, Малым кольцом Московской железной дороги',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'п.4 №12 от 01.04.2021',
  'Ссылка на верхнеуровневый график': 'Прииостановлено.\nГрафик будет подготовлен после решения о продолжении работы',
  'Ссылка на расширенный график': 'Прииостановлено.\nГрафик будет подготовлен после решения о продолжении работы',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Соловьянова Е.А.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'None',
  'Согласовано Управление МКАСмарт': 'None',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': '6-22/162-26',
  '№': '1',
  'Вид работы': 'ППТ',
  'Наименование проекта': 'Подготовка проекта планировки территории Киевского вокзала',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'Протокол № 8 п. 17 от 10.03.2022',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=526740403#gid=526740403\nЖдем концепцию развития территории КРТ от Инвестора',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=569099005#gid=569099005\nЖдем концепцию развития территории КРТ от Инвестора',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Глушко М.М.',
  'Рук проекта': 'Асатрян А.А.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'Подписано',
  'Согласовано Управление МКАСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': '23/224-26',
  '№': 'None',
  'Вид работы': 'ППТ',
  'Наименование проекта': 'Подготовка проекта планировки территории поселения Воскресенское, части поселка подсобного хозяйства Воскресенское',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Владимиров А.А.',
  'ГЗК/ГП/ЛД о подготовке': 'Протокол от 26.10.2023 №32 п. 15',
  'Ссылка на верхнеуровневый график': 'Прииостановлено, нет согласовонного варианта\nГрафик будет подготовлен после выбора варианта',
  'Ссылка на расширенный график': 'Прииостановлено, нет согласовонного варианта\nГрафик будет подготовлен после выбора варианта',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Соловьянова Е.А.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'None',
  'Согласовано Управление МКАСмарт': 'None',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': '6-24/196-26',
  '№': '2',
  'Вид работы': 'ППТ',
  'Наименование проекта': 'Подготовка проекта планировки территории, ограниченной улицей Нижегородской, полосой отвода железной дороги, Южнопортовой улицей, Москвой рекой',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Владимиров А.А.',
  'ГЗК/ГП/ЛД о подготовке': 'Протокол от 29.05.2024 № 18 п.72',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=526740403#gid=526740403',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=670102455#gid=670102455',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Лапина О.И.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'Подписано',
  'Согласовано Управление МКАСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': '3-25/21-26',
  '№': '3',
  'Вид работы': 'ППТ',
  'Наименование проекта': 'Подготовка проекта планировки\nтерритории вблизи деревни\nКрасная Пахра района Троицк города Москвы',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'Протокол от 29.01.2025 № 3 п.3',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=526740403#gid=526740403',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=362904608#gid=362904608',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Глушко М.М.',
  'Рук проекта': 'Логинов А.Л.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'Подписано',
  'Согласовано Управление МКАСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': 'None',
  '№': '3',
  'Вид работы': 'ППТ',
  'Наименование проекта': 'Подготовка проекта планировки территории, ограниченной шоссе Энтузиастов, шоссе Фрезер, Горьковским направлением железной дороги, улицей Подъемной',
  'Курирующий зам. пред. МКА': 'None',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Владимиров А.А.',
  'ГЗК/ГП/ЛД о подготовке': 'None',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=526740403#gid=526740403',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=1807994811#gid=1807994811',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Лапина О.И.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'Подписано',
  'Согласовано Управление МКАСмарт': 'График направлен в МКА 14.03.2025',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': 'None',
  '№': 'None',
  'Вид работы': '10% ППТ',
  'Наименование проекта': 'Подготовка проекта внесения изменений в постановление Правительства Москвы \nот 29 февраля 2024 г. № 394-ПП «Об утверждении проекта планировки территории между Аминьевским шоссе и Рябиновой улицей»',
  'Курирующий зам. пред. МКА': 'None',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Ломакина Е.А,',
  'ГЗК/ГП/ЛД о подготовке': 'None',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1yBQ6dCzx2W4jtxffRjmhDaw7MAjyeu06yGGHqbYHoiw/edit?gid=1991169065#gid=1991169065',
  'Ссылка на расширенный график': 'None',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'None',
  'Руководительподразделения': 'None',
  'Рук проекта': 'None',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'None',
  'Согласовано Управление МКАСмарт': 'None',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': 'None',
  '№': 'None',
  'Вид работы': '10% ППТ',
  'Наименование проекта': 'Внесение изменений в ППМ от 28.09.2021 № 1501-ПП проект планировки территории, прилегающей к Московским центральным диаметрам: МЦД-1 "Одинцово-Лобня", участок от МКАД до границ города Москвы',
  'Курирующий зам. пред. МКА': 'None',
  'Руководитель отраслевого управления': 'Петров С.А.',
  'АдминистратУКПД': 'Иванова М.С.',
  'ГЗК/ГП/ЛД о подготовке': 'None',
  'Ссылка на верхнеуровневый график': 'ГРАФИК 10% ППТ МЦД пеш.переход Одинцово-Лобня',
  'Ссылка на расширенный график': 'не требуется',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'None',
  'Руководительподразделения': 'None',
  'Рук проекта': 'None',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'Дата заявки 08.04.\nГрафик в разработке. Идет согласование с генпроектировщиком.',
  'Согласовано Управление МКАСмарт': 'None',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': '3-24/218-26',
  '№': '1',
  'Вид работы': 'Град. потенциал\nВЛЭП',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала освобождаемых от ВЛЭП территорий в городе Москве по адресу: \nПятницкое шоссе, вл. 4-6, СЗАО',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=355278683#gid=355278683',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Глушко М.М.',
  'Рук проекта': 'Цуканова И.Б.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'Подписано',
  'Согласовано Управление МКАСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': '3-24/215-26',
  '№': '2',
  'Вид работы': 'Град. потенциал\nВЛЭП',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала освобождаемых от ВЛЭП территорий в городе Москве по адресу: \nТерритория ВЛЭП вдоль 2-го Нагатинского проезда, ЮАО',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=516568795#gid=516568795',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Глушко М.М.',
  'Рук проекта': 'Логинов А.Л.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'Подписано',
  'Согласовано Управление МКАСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': '6-24/237-26',
  '№': '3',
  'Вид работы': 'Град. потенциал\nВЛЭП',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала освобождаемых от ВЛЭП территорий в городе Москве по адресу: \nТерритория ВЛЭП от Волжского бульвара вдоль Аллеи Кремлевских курсантов до улицы Чагинской, ЮВАО',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1897185067#gid=1897185067',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Глушко М.М.',
  'Рук проекта': 'Цуканова И.Б.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'Подписано',
  'Согласовано Управление МКАСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': '3-24/276-26',
  '№': '4',
  'Вид работы': 'Град. потенциал\nВЛЭП',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала освобождаемых от ВЛЭП территорий в городе Москве по адресу: территория ВЛЭП вдоль Филевской линии метрополитена от станции «Фили» до бульвара Солдатенкова, ЗАО',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Белоусова Т.С.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=774182060#gid=774182060',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Глушко М.М.',
  'Рук проекта': 'Логинов А.Л.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'Подписано',
  'Согласовано Управление МКАСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': '3-23/204-26',
  '№': '5',
  'Вид работы': 'Град. потенциал\nТиНАО\nОбщая 2024',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала развития территории по адресу: г. Москва, пос. Михайлово-Ярцевское, вблизи пос. Шишкин лес (ТиНАО) ',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Смутчук Б.В.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'None',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Каземирова Л.Р.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'Подписано',
  'Согласовано Управление МКАСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': '6-24/116-26',
  '№': '6',
  'Вид работы': 'Град. потенциал\nТиНАО\nОбщая 2024',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала развития территории, ограниченной МКАД, Калужским шоссе, ул. Адмирала Корнилова и Троицким лесопарком ',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Смутчук Б.В.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'Одобрено на Штабе КРТ',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Каземирова Л.Р.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'Подписано',
  'Согласовано Управление МКАСмарт': 'None',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': '6-24/180-26',
  '№': '7',
  'Вид работы': 'Град. потенциал\nТиНАО\nОбщая 2024',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала развития территории, прилегающей к улице Адмирала Корнилова, ТиНАО',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Смутчук Б.В.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'Одобрено на Штабе КРТ',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Каземирова Л.Р.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'Подписано',
  'Согласовано Управление МКАСмарт': 'None',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': '6-24/181-26',
  '№': '8',
  'Вид работы': 'Град. потенциал\nТиНАО\nОбщая 2024',
  'Наименование проекта': 'Разработка градостроительного потенциала развития территории напротив ТК «ФУД-СИТИ» у ст.м. «Корниловская»',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Смутчук Б.В.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'Одобрено на Штабе КРТ',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Агафонкина А.В.',
  'Рук проекта': 'Каземирова Л.Р.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'Подписано',
  'Согласовано Управление МКАСмарт': 'None',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': '3-24/191-26',
  '№': '6',
  'Вид работы': 'Град. потенциал\nТиНАО\nОбщая 2024',
  'Наименование проекта': 'Подготовка материалов предварительной оценки градостроительного потенциала комплексного развития территории по адресу: г. Москва, пос. Птичное, ул. Центральная, с определением границ и объемов подготовки градостроительного потенциала развития территории',
  'Курирующий зам. пред. МКА': 'Ильин А.Ю.',
  'Руководитель отраслевого управления': 'Шабалдина Е.А.',
  'АдминистратУКПД': 'Смутчук Б.В.',
  'ГЗК/ГП/ЛД о подготовке': 'Не требуется',
  'Ссылка на верхнеуровневый график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271',
  'Ссылка на расширенный график': 'https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=31303565#gid=31303565',
  'Месяц утверждения': 'None',
  'Курирующий Зам. Директора': 'Иванова А.А.',
  'Руководительподразделения': 'Глушко М.М.',
  'Рук проекта': 'Логинов А.Л.',
  'СМАРТ': 'None',
  'Согласовано ГенпланСмарт': 'Подписано',
  'Согласовано Управление МКАСмарт': 'График направлен в МКА 12.03.2025',
  'Согласовано Курирующим ЗамСмарт': 'None',
  'Unnamed: 18': 'None'},
 {'Шифр работы': '3-24/224-26',
  '№': '7',
  'Вид работы': 'Град. потенциал\nТиНАО\nОбщая 2024',
  'Наименование проекта': 'Разработка материалов предварительной оценки градостроительного потенциала территории по адресу: г. Москва, пос. Вороновское, дер. Львово',

In [8]:
for record in list_of_dicts:
    print(json.dumps(obj=record, indent=4, ensure_ascii=False))

{
    "Шифр работы": "6-20/133-26",
    "№": "None",
    "Вид работы": "ППТ ",
    "Наименование проекта": "Подготовка проекта планировки территории по адресу: \n3-й Силикатный пр., влд. 10",
    "Курирующий зам. пред. МКА": "Ильин А.Ю.",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Белоусова Т.С.",
    "ГЗК/ГП/ЛД о подготовке": "от 26 марта 2020 г. № 9 п. 5\nот 03 февраля 2022 г. № 4, п.2",
    "Ссылка на верхнеуровневый график": "Прииостановлено.\nГрафик будет подготовлен после решения о продолжении работы ",
    "Ссылка на расширенный график": "Прииостановлено.\nГрафик будет подготовлен после решения о продолжении работы",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "Иванова А.А.",
    "Руководительподразделения": "Агафонкина А.В.",
    "Рук проекта": "Лапина О.И.",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "None",
    "Согласовано Управление МКАСмарт": "None",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "41-21/153-26",
    "№": "None",
    "Вид работы": "ППТ ",
    "Наименование проекта": "Проект планировки территории, ограниченной Пермской улицей, Тагильской улицей, улицей Николая Химушина, Монтажной улицей, Щелковским шоссе, Большой Черкизовской улицей, границей объекта природного комплекса Восточного административного округа города Москвы № 20 «Черкизовский парк», Тюменской улицей, Открытым шоссе, Малым кольцом Московской железной дороги",
    "Курирующий зам. пред. МКА": "Ильин А.Ю.",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Белоусова Т.С.",
    "ГЗК/ГП/ЛД о подготовке": "п.4 №12 от 01.04.2021",
    "Ссылка на верхнеуровневый график": "Прииостановлено.\nГрафик будет подготовлен после решения о продолжении работы",
    "Ссылка на расширенный график": "Прииостановлено.\nГрафик будет подготовлен после решения о продолжении работы",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "Иванова А.А.",
    "Руководительподразделения": "Агафонкина А.В.",
    "Рук проекта": "Соловьянова Е.А.",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "None",
    "Согласовано Управление МКАСмарт": "None",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "6-22/162-26",
    "№": "1",
    "Вид работы": "ППТ",
    "Наименование проекта": "Подготовка проекта планировки территории Киевского вокзала",
    "Курирующий зам. пред. МКА": "Ильин А.Ю.",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Белоусова Т.С.",
    "ГЗК/ГП/ЛД о подготовке": "Протокол № 8 п. 17 от 10.03.2022",
    "Ссылка на верхнеуровневый график": "https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=526740403#gid=526740403\nЖдем концепцию развития территории КРТ от Инвестора",
    "Ссылка на расширенный график": "https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=569099005#gid=569099005\nЖдем концепцию развития территории КРТ от Инвестора",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "Иванова А.А.",
    "Руководительподразделения": "Глушко М.М.",
    "Рук проекта": "Асатрян А.А.",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "Подписано",
    "Согласовано Управление МКАСмарт": "График направлен в МКА 12.03.2025",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "23/224-26",
    "№": "None",
    "Вид работы": "ППТ",
    "Наименование проекта": "Подготовка проекта планировки территории поселения Воскресенское, части поселка подсобного хозяйства Воскресенское",
    "Курирующий зам. пред. МКА": "Ильин А.Ю.",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Владимиров А.А.",
    "ГЗК/ГП/ЛД о подготовке": "Протокол от 26.10.2023 №32 п. 15",
    "Ссылка на верхнеуровневый график": "Прииостановлено, нет согласовонного варианта\nГрафик будет подготовлен после выбора варианта",
    "Ссылка на расширенный график": "Прииостановлено, нет согласовонного варианта\nГрафик будет подготовлен после выбора варианта",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "Иванова А.А.",
    "Руководительподразделения": "Агафонкина А.В.",
    "Рук проекта": "Соловьянова Е.А.",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "None",
    "Согласовано Управление МКАСмарт": "None",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "6-24/196-26",
    "№": "2",
    "Вид работы": "ППТ",
    "Наименование проекта": "Подготовка проекта планировки территории, ограниченной улицей Нижегородской, полосой отвода железной дороги, Южнопортовой улицей, Москвой рекой",
    "Курирующий зам. пред. МКА": "Ильин А.Ю.",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Владимиров А.А.",
    "ГЗК/ГП/ЛД о подготовке": "Протокол от 29.05.2024 № 18 п.72",
    "Ссылка на верхнеуровневый график": "https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=526740403#gid=526740403",
    "Ссылка на расширенный график": "https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=670102455#gid=670102455",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "Иванова А.А.",
    "Руководительподразделения": "Агафонкина А.В.",
    "Рук проекта": "Лапина О.И.",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "Подписано",
    "Согласовано Управление МКАСмарт": "График направлен в МКА 12.03.2025",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "3-25/21-26",
    "№": "3",
    "Вид работы": "ППТ",
    "Наименование проекта": "Подготовка проекта планировки\nтерритории вблизи деревни\nКрасная Пахра района Троицк города Москвы",
    "Курирующий зам. пред. МКА": "Ильин А.Ю.",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Белоусова Т.С.",
    "ГЗК/ГП/ЛД о подготовке": "Протокол от 29.01.2025 № 3 п.3",
    "Ссылка на верхнеуровневый график": "https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=526740403#gid=526740403",
    "Ссылка на расширенный график": "https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=362904608#gid=362904608",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "Иванова А.А.",
    "Руководительподразделения": "Глушко М.М.",
    "Рук проекта": "Логинов А.Л.",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "Подписано",
    "Согласовано Управление МКАСмарт": "График направлен в МКА 12.03.2025",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "None",
    "№": "3",
    "Вид работы": "ППТ",
    "Наименование проекта": "Подготовка проекта планировки территории, ограниченной шоссе Энтузиастов, шоссе Фрезер, Горьковским направлением железной дороги, улицей Подъемной",
    "Курирующий зам. пред. МКА": "None",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Владимиров А.А.",
    "ГЗК/ГП/ЛД о подготовке": "None",
    "Ссылка на верхнеуровневый график": "https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=526740403#gid=526740403",
    "Ссылка на расширенный график": "https://docs.google.com/spreadsheets/d/1BIG1ooWR5VQH-oGDQa1OYnWY6bctOWnFQWcTdpToRes/edit?gid=1807994811#gid=1807994811",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "Иванова А.А.",
    "Руководительподразделения": "Агафонкина А.В.",
    "Рук проекта": "Лапина О.И.",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "Подписано",
    "Согласовано Управление МКАСмарт": "График направлен в МКА 14.03.2025",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "None",
    "№": "None",
    "Вид работы": "10% ППТ",
    "Наименование проекта": "Подготовка проекта внесения изменений в постановление Правительства Москвы \nот 29 февраля 2024 г. № 394-ПП «Об утверждении проекта планировки территории между Аминьевским шоссе и Рябиновой улицей»",
    "Курирующий зам. пред. МКА": "None",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Ломакина Е.А,",
    "ГЗК/ГП/ЛД о подготовке": "None",
    "Ссылка на верхнеуровневый график": "https://docs.google.com/spreadsheets/d/1yBQ6dCzx2W4jtxffRjmhDaw7MAjyeu06yGGHqbYHoiw/edit?gid=1991169065#gid=1991169065",
    "Ссылка на расширенный график": "None",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "None",
    "Руководительподразделения": "None",
    "Рук проекта": "None",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "None",
    "Согласовано Управление МКАСмарт": "None",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "None",
    "№": "None",
    "Вид работы": "10% ППТ",
    "Наименование проекта": "Внесение изменений в ППМ от 28.09.2021 № 1501-ПП проект планировки территории, прилегающей к Московским центральным диаметрам: МЦД-1 \"Одинцово-Лобня\", участок от МКАД до границ города Москвы",
    "Курирующий зам. пред. МКА": "None",
    "Руководитель отраслевого управления": "Петров С.А.",
    "АдминистратУКПД": "Иванова М.С.",
    "ГЗК/ГП/ЛД о подготовке": "None",
    "Ссылка на верхнеуровневый график": "ГРАФИК 10% ППТ МЦД пеш.переход Одинцово-Лобня",
    "Ссылка на расширенный график": "не требуется",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "None",
    "Руководительподразделения": "None",
    "Рук проекта": "None",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "Дата заявки 08.04.\nГрафик в разработке. Идет согласование с генпроектировщиком.",
    "Согласовано Управление МКАСмарт": "None",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "3-24/218-26",
    "№": "1",
    "Вид работы": "Град. потенциал\nВЛЭП",
    "Наименование проекта": "Подготовка материалов предварительной оценки градостроительного потенциала освобождаемых от ВЛЭП территорий в городе Москве по адресу: \nПятницкое шоссе, вл. 4-6, СЗАО",
    "Курирующий зам. пред. МКА": "Ильин А.Ю.",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Белоусова Т.С.",
    "ГЗК/ГП/ЛД о подготовке": "Не требуется",
    "Ссылка на верхнеуровневый график": "https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271",
    "Ссылка на расширенный график": "https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=355278683#gid=355278683",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "Иванова А.А.",
    "Руководительподразделения": "Глушко М.М.",
    "Рук проекта": "Цуканова И.Б.",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "Подписано",
    "Согласовано Управление МКАСмарт": "График направлен в МКА 12.03.2025",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "3-24/215-26",
    "№": "2",
    "Вид работы": "Град. потенциал\nВЛЭП",
    "Наименование проекта": "Подготовка материалов предварительной оценки градостроительного потенциала освобождаемых от ВЛЭП территорий в городе Москве по адресу: \nТерритория ВЛЭП вдоль 2-го Нагатинского проезда, ЮАО",
    "Курирующий зам. пред. МКА": "Ильин А.Ю.",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Белоусова Т.С.",
    "ГЗК/ГП/ЛД о подготовке": "Не требуется",
    "Ссылка на верхнеуровневый график": "https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271",
    "Ссылка на расширенный график": "https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=516568795#gid=516568795",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "Иванова А.А.",
    "Руководительподразделения": "Глушко М.М.",
    "Рук проекта": "Логинов А.Л.",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "Подписано",
    "Согласовано Управление МКАСмарт": "График направлен в МКА 12.03.2025",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "6-24/237-26",
    "№": "3",
    "Вид работы": "Град. потенциал\nВЛЭП",
    "Наименование проекта": "Подготовка материалов предварительной оценки градостроительного потенциала освобождаемых от ВЛЭП территорий в городе Москве по адресу: \nТерритория ВЛЭП от Волжского бульвара вдоль Аллеи Кремлевских курсантов до улицы Чагинской, ЮВАО",
    "Курирующий зам. пред. МКА": "Ильин А.Ю.",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Белоусова Т.С.",
    "ГЗК/ГП/ЛД о подготовке": "Не требуется",
    "Ссылка на верхнеуровневый график": "https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271",
    "Ссылка на расширенный график": "https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1897185067#gid=1897185067",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "Иванова А.А.",
    "Руководительподразделения": "Глушко М.М.",
    "Рук проекта": "Цуканова И.Б.",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "Подписано",
    "Согласовано Управление МКАСмарт": "График направлен в МКА 12.03.2025",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "3-24/276-26",
    "№": "4",
    "Вид работы": "Град. потенциал\nВЛЭП",
    "Наименование проекта": "Подготовка материалов предварительной оценки градостроительного потенциала освобождаемых от ВЛЭП территорий в городе Москве по адресу: территория ВЛЭП вдоль Филевской линии метрополитена от станции «Фили» до бульвара Солдатенкова, ЗАО",
    "Курирующий зам. пред. МКА": "Ильин А.Ю.",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Белоусова Т.С.",
    "ГЗК/ГП/ЛД о подготовке": "Не требуется",
    "Ссылка на верхнеуровневый график": "https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271",
    "Ссылка на расширенный график": "https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=774182060#gid=774182060",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "Иванова А.А.",
    "Руководительподразделения": "Глушко М.М.",
    "Рук проекта": "Логинов А.Л.",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "Подписано",
    "Согласовано Управление МКАСмарт": "График направлен в МКА 12.03.2025",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "3-23/204-26",
    "№": "5",
    "Вид работы": "Град. потенциал\nТиНАО\nОбщая 2024",
    "Наименование проекта": "Подготовка материалов предварительной оценки градостроительного потенциала развития территории по адресу: г. Москва, пос. Михайлово-Ярцевское, вблизи пос. Шишкин лес (ТиНАО) ",
    "Курирующий зам. пред. МКА": "Ильин А.Ю.",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Смутчук Б.В.",
    "ГЗК/ГП/ЛД о подготовке": "Не требуется",
    "Ссылка на верхнеуровневый график": "https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271",
    "Ссылка на расширенный график": "None",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "Иванова А.А.",
    "Руководительподразделения": "Агафонкина А.В.",
    "Рук проекта": "Каземирова Л.Р.",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "Подписано",
    "Согласовано Управление МКАСмарт": "График направлен в МКА 12.03.2025",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "6-24/116-26",
    "№": "6",
    "Вид работы": "Град. потенциал\nТиНАО\nОбщая 2024",
    "Наименование проекта": "Подготовка материалов предварительной оценки градостроительного потенциала развития территории, ограниченной МКАД, Калужским шоссе, ул. Адмирала Корнилова и Троицким лесопарком ",
    "Курирующий зам. пред. МКА": "Ильин А.Ю.",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Смутчук Б.В.",
    "ГЗК/ГП/ЛД о подготовке": "Не требуется",
    "Ссылка на верхнеуровневый график": "https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271",
    "Ссылка на расширенный график": "Одобрено на Штабе КРТ",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "Иванова А.А.",
    "Руководительподразделения": "Агафонкина А.В.",
    "Рук проекта": "Каземирова Л.Р.",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "Подписано",
    "Согласовано Управление МКАСмарт": "None",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "6-24/180-26",
    "№": "7",
    "Вид работы": "Град. потенциал\nТиНАО\nОбщая 2024",
    "Наименование проекта": "Подготовка материалов предварительной оценки градостроительного потенциала развития территории, прилегающей к улице Адмирала Корнилова, ТиНАО",
    "Курирующий зам. пред. МКА": "Ильин А.Ю.",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Смутчук Б.В.",
    "ГЗК/ГП/ЛД о подготовке": "Не требуется",
    "Ссылка на верхнеуровневый график": "https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271",
    "Ссылка на расширенный график": "Одобрено на Штабе КРТ",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "Иванова А.А.",
    "Руководительподразделения": "Агафонкина А.В.",
    "Рук проекта": "Каземирова Л.Р.",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "Подписано",
    "Согласовано Управление МКАСмарт": "None",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "6-24/181-26",
    "№": "8",
    "Вид работы": "Град. потенциал\nТиНАО\nОбщая 2024",
    "Наименование проекта": "Разработка градостроительного потенциала развития территории напротив ТК «ФУД-СИТИ» у ст.м. «Корниловская»",
    "Курирующий зам. пред. МКА": "Ильин А.Ю.",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Смутчук Б.В.",
    "ГЗК/ГП/ЛД о подготовке": "Не требуется",
    "Ссылка на верхнеуровневый график": "https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271",
    "Ссылка на расширенный график": "Одобрено на Штабе КРТ",
    "Месяц утверждения": "None",
    "Курирующий Зам. Директора": "Иванова А.А.",
    "Руководительподразделения": "Агафонкина А.В.",
    "Рук проекта": "Каземирова Л.Р.",
    "СМАРТ": "None",
    "Согласовано ГенпланСмарт": "Подписано",
    "Согласовано Управление МКАСмарт": "None",
    "Согласовано Курирующим ЗамСмарт": "None",
    "Unnamed: 18": "None"
}
{
    "Шифр работы": "3-24/191-26",
    "№": "6",
    "Вид работы": "Град. потенциал\nТиНАО\nОбщая 2024",
    "Наименование проекта": "Подготовка материалов предварительной оценки градостроительного потенциала комплексного развития территории по адресу: г. Москва, пос. Птичное, ул. Центральная, с определением границ и объемов подготовки градостроительного потенциала развития территории",
    "Курирующий зам. пред. МКА": "Ильин А.Ю.",
    "Руководитель отраслевого управления": "Шабалдина Е.А.",
    "АдминистратУКПД": "Смутчук Б.В.",
    "ГЗК/ГП/ЛД о подготовке": "Не требуется",
    "Ссылка на верхнеуровневый график": "https://docs.google.com/spreadsheets/d/1gZF2b1AVZ3YhogsB1_Q5LhtThX3qa7HwJhndpSzij3I/edit?gid=1197715271#gid=1197715271",

# Проход по ссылкам

In [9]:
def download_file_stream(url, local_filename):
    """
    Скачивает файл по ссылке
    :param url: ссылка
    :param local_filename: имя сохраняемого файла
    :return: 
    """
    with requests.get(url, stream=True) as r:
        r.raise_for_status()
        with open(local_filename, 'wb') as f:
            for chunk in r.iter_content(chunk_size=8192):
                f.write(chunk)
    print(f'Файл успешно сохранён как {local_filename}')

In [10]:
def parse_excel(local_filename):
    """Парсинг excel файла в json"""
    inner_df = pd.ExcelFile(local_filename)
    inner_df = inner_df.parse(inner_df.sheet_names[0])
    inner_df = inner_df.astype(str)
    inner_df.dropna(axis=0, how='all', inplace=True)
    inner_df = inner_df.iloc[3:]
    inner_df.columns = inner_df.iloc[0]
    inner_df = inner_df.drop(3).reset_index(drop=True)
    inner_df.columns.values[3] = 'Дата'
    inner_df.columns.values[-1] = 'Статус'
    inner_df.columns = inner_df.columns.str.replace('\n', '', regex=False)
    inner_df.columns = inner_df.columns.str.strip()
    inner_df = inner_df.replace(r'\n',' ', regex=True)
    inner_df = inner_df.replace(r'\t',' ', regex=True)
    result_list = []
    i = 0
    while i < len(inner_df):
        result = dict()
        if (inner_df["Наименование работы"][i] != 'nan') and (inner_df["Наименование работы"][i+1] == 'nan'):
            step = 2
        else:
            step = 1
        part_df = inner_df.iloc[i:i+step]  # Получаем одну/две строки
        result = part_df.iloc[0,:3].to_dict() # попробовать dict
        result.update(part_df[["Статус"]].iloc[[0]].to_dict(orient='records')[0])
        i+=step
        part_df = part_df.set_index('Дата').iloc[:,3:-1].to_dict()
        result.update(part_df)
        result_list.append(result)

    return result_list

In [11]:
columns_to_be_matched = ['Разработка материалов существующего положения + эскизы', 'Рассмотрение эскизов, выбор рекомендуемого варианта', 'Разработка обосновывающих материалов проектного предложения', 'Расмотрение обосновывающих материалов, получение замечаний', 'Корректировка обосновывающих материалов по замечаниям ОИВ, повторная рассылка', 'Корректировка материалов по замечаниям ОИВ, Подготовка и согласование макета и НПМ, получение согласований ОИВ', 'Подготовка презентации на ГЗК', 'Проведение РГ ГЗК И ГЗК', 'Подготовка Утв . Части', 'ПУ МКА', 'АИС СД УКД', 'АИС СД ОИВ', 'Доработка материалов по замч ОИВ', 'ПУ ПМ', 'ОАУ ПМ']
def check_excel(local_filename):
    """
    Прооверяет что это подходящий excel документ
    """
    df = pd.ExcelFile(local_filename)
    df = df.parse(df.sheet_names[0])
    df = df.astype(str)
    df.dropna(axis=0, how='all', inplace=True)
    df = df.iloc[3:]
    df.columns = df.iloc[0]
    df.columns = df.columns.str.replace('\n', '', regex=False)
    df.columns = df.columns.str.strip()
    df = df.replace(r'\n',' ', regex=True)
    df = df.replace(r'\t',' ', regex=True)
    df = df.drop(3).reset_index(drop=True)
    matched_columns = 0
    for column in columns_to_be_matched:
        if column in df.columns:
            matched_columns += 1
    if matched_columns == len(columns_to_be_matched):
        return True
    else:
        return False

In [12]:
# множество посещённых ссылок
visited_links = []

In [13]:
def follow_links(source_doc):
    """
    Ищет ссылки внутри source (представляющий собой список из json) и скачивает файлы
    source_doc
    """
    json_number = 0
    for obj in source_doc:
        json_number+=1
        obj["links"] = dict()
        for k, v in obj.items():
            if isinstance(v, str) and v.startswith('http'): # определяем ссылки
                
                base = v.split('/edit')[0]
                link_for_download = base + "/export?format=xlsx"
                
                if link_for_download not in visited_links:
                    visited_links.append(link_for_download)
                    link_number = visited_links.index(link_for_download)
                    local_filename = f'./downloaded_all/{link_number}.xlsx'
                    download_file_stream(url=link_for_download, local_filename=local_filename)
                else:
                    link_number = visited_links.index(link_for_download)
                    local_filename = f'./downloaded_all/{link_number}.xlsx'
                    
                if check_excel(local_filename):
                    print(f"{local_filename}")
                    parsed_data = parse_excel(local_filename)
                    obj["links"].update({k:parsed_data})
                    with open(f'./saved_jsons/{json_number}.json', 'w',encoding='utf-8') as f:
                        json.dump(obj, f, ensure_ascii=False, indent=4)
                # фильтровать excel файлы

In [14]:
follow_links(list_of_dicts)

Файл успешно сохранён как ./downloaded_all/0.xlsx
Файл успешно сохранён как ./downloaded_all/1.xlsx
Файл успешно сохранён как ./downloaded_all/2.xlsx
Файл успешно сохранён как ./downloaded_all/3.xlsx
./downloaded_all/3.xlsx
./downloaded_all/3.xlsx
./downloaded_all/3.xlsx
./downloaded_all/3.xlsx
./downloaded_all/3.xlsx
./downloaded_all/3.xlsx
./downloaded_all/3.xlsx
./downloaded_all/3.xlsx
./downloaded_all/3.xlsx
./downloaded_all/3.xlsx
./downloaded_all/3.xlsx
./downloaded_all/3.xlsx
./downloaded_all/3.xlsx
./downloaded_all/3.xlsx
./downloaded_all/3.xlsx
./downloaded_all/3.xlsx
./downloaded_all/3.xlsx
./downloaded_all/3.xlsx
./downloaded_all/3.xlsx
./downloaded_all/3.xlsx
./downloaded_all/3.xlsx
./downloaded_all/3.xlsx
./downloaded_all/3.xlsx
./downloaded_all/3.xlsx
Файл успешно сохранён как ./downloaded_all/4.xlsx
Файл успешно сохранён как ./downloaded_all/5.xlsx

KeyboardInterrupt:

In [165]:
inner_file = './data/ППТ ТПУ Петров С.А..xlsx'
inner_df = pd.ExcelFile(inner_file)
inner_df = inner_df.parse(inner_df.sheet_names[0])
inner_df = inner_df.astype(str)
inner_df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,nan,nan,nan,nan,nan,СВОДНЫЙ ГРАФИК УТВЕРЖДЕНИЯ ППТ ТПУ,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
1,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
2,nan,nan,nan,nan,nan,Подготовка обосновывающих материалов \nсуществ...,nan,Согласование обосновывающих \nматериалов,nan,nan,nan,"Разработка презентационных материалов для ГЗК,...",nan,nan,nan,nan,"Согласование утв. части в АИС СД, утверждение ППМ",nan,nan,Статус
3,№,Наименование работы,Квартал утверждения ППТ,nan,Разработка материалов существующего положения ...,"Рассмотрение эскизов, выбор рекомендуемого вар...",Разработка обосновывающих материалов проектног...,"Расмотрение обосновывающих материалов, получен...",Корректировка обосновывающих материалов по зам...,"Корректировка материалов по замечаниям ОИВ, По...",Подготовка презентации на ГЗК,Проведение \nРГ ГЗК И ГЗК,Подготовка \nУтв . Части,ПУ МКА,АИС СД \nУКД,АИС СД \nОИВ,Доработка материалов по замч ОИВ,ПУ ПМ,ОАУ ПМ,nan
4,1,Подготовка проекта планировки территории транс...,3 кв 2025,Дата окончания,nan,nan,nan,2025-01-27 00:00:00,2025-03-21 00:00:00,2025-04-21 00:00:00,2025-03-19 00:00:00,(26.03.2025)\n09.04.2025,(28.03.2025)\n02.04.2025,2025-05-19 00:00:00,2025-06-02 00:00:00,2025-06-16 00:00:00,2025-06-30 00:00:00,2025-07-28 00:00:00,2025-08-04 00:00:00,Повторное рассмотрение на штабе метро у ЕВВ 22...
5,nan,nan,nan,Дата окончания факт,Выполнено,2024-11-19 00:00:00,2024-12-28 00:00:00,2025-02-10 00:00:00,2025-03-21 00:00:00,nan,2025-03-19 00:00:00,nan,2025-04-02 00:00:00,nan,nan,nan,nan,nan,nan,nan
6,2,Подготовка проекта планировки территории транс...,3 кв 2025,Дата окончания,nan,nan,nan,2025-02-27 00:00:00,2025-03-31 00:00:00,2025-04-27 00:00:00,2025-03-26 00:00:00,(09.04.2025)\n16.04.2025,2025-04-25 00:00:00,2025-05-30 00:00:00,2025-06-13 00:00:00,2025-06-27 00:00:00,2025-07-11 00:00:00,2025-08-08 00:00:00,2025-08-15 00:00:00,Повторное рассмотрение на штабе метро у ЕВВ 22...
7,nan,nan,nan,Дата окончания факт,Выполнено,2024-12-10 00:00:00,2025-01-28 00:00:00,2025-02-28 00:00:00,2025-03-31 00:00:00,nan,2025-04-03 00:00:00,nan,nan,nan,nan,nan,nan,nan,nan,nan
8,3,Подготовка проекта планировки территории транс...,3 кв 2025,Дата окончания,nan,nan,nan,2025-03-07 00:00:00,(07.04.25)\n28.04.2025,2025-05-07 00:00:00,2025-03-19 00:00:00,(27.03.2025)\n16.04.2025,2025-04-28 00:00:00,2025-06-09 00:00:00,2025-06-23 00:00:00,2025-07-07 00:00:00,2025-07-21 00:00:00,2025-08-18 00:00:00,2025-08-25 00:00:00,Повторное рассмотрение на штабе метро у ЕВВ 22...
9,nan,nan,nan,Дата окончания факт,Выполнено,2024-12-10 00:00:00,2025-02-05 00:00:00,2025-03-17 00:00:00,nan,nan,2025-03-20 00:00:00,nan,nan,nan,nan,nan,nan,nan,nan,nan
10,4,Подготовка проекта планировки территории транс...,3 кв 2025,Дата окончания,nan,nan,nan,2025-01-27 00:00:00,(04.04.2025)\n11.04.2025,2025-05-04 00:00:00,2025-04-16 00:00:00,2025-04-23 00:00:00,2025-04-25 00:00:00,2025-06-06 00:00:00,2025-06-16 00:00:00,2025-06-26 00:00:00,2025-07-03 00:00:00,2025-07-22 00:00:00,2025-07-29 00:00:00,Повторное рассмотрение на штабе метро у ЕВВ 22...
11,nan,nan,nan,Дата окончания факт,Выполнено,2024-11-19 00:00:00,2024-12-28 00:00:00,2025-02-10 00:00:00,2025-04-10 00:00:00,nan,2025-04-16 00:00:00,nan,nan,nan,nan,nan,nan,nan,nan,nan
12,5,Подготовка проекта планировки территории транс...,3 кв 2025,Дата окончания,nan,nan,nan,2025-04-10 00:00:00,2025-04-03 00:00:00,2025-05-03 00:00:00,2025-04-16 00:00:00,2025-04-24 00:00:00,2025-05-31 00:00:00,2025-06-21 00:00:00,2025-07-05 00:00:00,2025-07-19 00:00:00,2025-08-02 00:00:00,2025-08-30 00:00:00,2025-09-06 00:00:00,Материалы с жилой застройко были подготовлены ...
13,nan,nan,nan,Дата окончания факт,Выполнено,2024-12-10 00:00:00,2025-02-11 00:00:00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
14,6,Подготовка проекта планировки территории транс...,4 кв 2025,Дата окончания,nan,nan,2025-03-10 00:00:00,2025-04-09 00:00:00,2025-04-23 00:00:00,2025-05-23 00:00:00,2025-04-30 00:00:00,2025-06-13 00:00:00,2025-06-06 00:00:00,2025-07-04 00:00:00,2025-07-18 00:00:00,2025-08-01 00:00:00,2025-08-15 00:00:00,2025-09-12 00:00:00,2025-09-19 00:00:00,"Отработка замечаний ОИВ, готовится повторная р..."
15,nan,nan,nan,Дата окончания факт,Выполнено,2025-01-29 00:00:00,2025-03-10 00:00:00,2025-04-09 00:00:00,2025-04-24 00:00:00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
16,7,Подготовка проекта планировки территории транс...,4 кв 2025,Дата окончания,Выполнено,2025-05-27 00:00:00,2025-04-17 00:00:00,2025-05-17 00:00:00,2025-05-31 00:00:00,2025-06-30 00:00:00,2025-07-07 00:00:00,2025-07-15 00:00:00,2025-07-28 00:00:00,2025-08-18 00:00:00,2025-09-01 00:00:00,2025-09-15 00:00:00,2025-09-29 00:00:00,2025-10-27 00:00:00,2025-11-03 00:00:00,ОМ на согласовании в ОИВ
17,nan,nan,nan,Дата окончания факт,nan,2025-04-17 00:00:00,2025-04-17 00:00:00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
18,8,Подготовка проекта планировки территории транс...,4 кв 2025,Дата окончания,Выполнено,2025-04-11 00:00:00,2025-05-05 00:00:00,2025-06-04 00:00:00,2025-06-18 00:00:00,2025-07-18 00:00:00,2025-08-01 00:00:00,2025-08-15 00:00:00,2025-08-01 00:00:00,2025-09-05 00:00:00,2025-09-19 00:00:00,2025-10-03 00:00:00,2025-10-17 00:00:00,2025-11-14 00:00:00,2025-11-21 00:00:00,"Приоритетный эскиз не выбран, идет отработка м..."
19,nan,nan,nan,Дата окончания факт,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
20,9,Подготовка проекта планировки территории транс...,4 кв 2025,Дата окончания,2025-04-14 00:00:00,2025-04-21 00:00:00,2025-05-21 00:00:00,2025-06-17 00:00:00,2025-07-01 00:00:00,2025-07-31 00:00:00,2025-07-24 00:00:00,2025-08-03 00:00:00,2025-08-22 00:00:00,2025-08-29 00:00:00,2025-09-12 00:00:00,2025-10-10 00:00:00,2025-10-24 00:00:00,2025-10-27 00:00:00,2025-11-28 00:00:00,1. Подготовлено 2 вар эскиза \n2. план пересел...
21,nan,nan,nan,Дата окончания факт,2025-04-15 00:00:00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
22,10,Подготовка проекта планировки территории транс...,1 кв 2026,Дата окончания,Выполнено,2025-05-30 00:00:00,2025-06-30 00:00:00,2025-07-30 00:00:00,2025-08-13 00:00:00,2025-09-12 00:00:00,2025-09-19 00:00:00,2025-09-27 00:00:00,2025-10-10 00:00:00,2025-10-31 00:00:00,2025-11-14 00:00:00,2025-11-28 00:00:00,2025-12-12 00:00:00,2026-01-09 00:00:00,2026-01-16 00:00:00,1.\tЭскиз рассмотрен на штабе метро ЕВВ 25.03....
23,nan,nan,nan,Дата окончания факт,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
24,11,Подготовка проекта планировки территории транс...,1 кв 2026,Дата окончания,Выполнено,2025-05-31 00:00:00,2025-07-01 00:00:00,2025-07-31 00:00:00,2025-08-14 00:00:00,2025-09-13 00:00:00,2025-09-27 00:00:00,2025-10-11 00:00:00,2025-09-27 00:00:00,2025-11-01 00:00:00,2025-11-15 00:00:00,2025-11-29 00:00:00,2025-12-13 00:00:00,2026-01-10 00:00:00,2026-01-17 00:00:00,"1.\tЭскиз направлен на доработку, предложено р..."
25,nan,nan,nan,Дата окончания факт,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
26,12,Подготовка проекта планировки территории транс...,1 кв 2026,Дата окончания,Выполнено,2025-06-06 00:00:00,2025-07-07 00:00:00,2025-08-06 00:00:00,2025-08-20 00:00:00,2025-08-20 00:00:00,2025-09-26 00:00:00,2025-10-04 00:00:00,2025-10-03 00:00:00,2025-11-07 00:00:00,2025-11-21 00:00:00,2025-12-05 00:00:00,2025-12-19 00:00:00,2026-01-16 00:00:00,2026-01-23 00:00:00,"1.\tЭскиз направлен на доработку, предложено р..."
27,nan,nan,nan,Дата окончания факт,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
28,13,Подготовка проект планировки территории трансп...,4 кв 2025,Дата окончания,Выполнено,Выполнено,2025-04-25 00:00:00,2025-05-25 00:00:00,2025-06-08 00:00:00,2025-07-08 00:00:00,2025-07-15 00:00:00,2025-07-23 00:00:00,2025-08-07 00:00:00,2025-08-14 00:00:00,2025-09-11 00:00:00,2025-09-25 00:00:00,2025-11-14 00:00:00,2025-12-17 00:00:00,2025-12-24 00:00:00,1. Обосновывающие материалы готовятся к рассыл...
29,nan,nan,nan,Дата окончания факт,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
30,14,Проект планировки территории линейного объекта...,4 кв 2025,Дата окончания,Выполнено,Выполнено,2025-04-29 00:00:00,2025-05-28 00:00:00,2025-06-18 00:00:00,2025-06-18 00:00:00,2025-07-03 00:00:00,2025-07-03 00:00:00,2025-07-18 00:00:00,2025-07-25 00:00:00,2025-08-08 00:00:00,2025-08-15 00:00:00,2025-09-17 00:00:00,2025-09-30 00:00:00,2025-10-10 00:00:00,Обосновывающие материалы в рассылке в ОИВ с 16...
31,15,"Подготовка ППТ, ограниченной Промышленным прое...",4 кв 2025,Дата окончания факт,nan,nan,2025-07-02 00:00:00,2025-07-29 00:00:00,2025-08-11 00:00:00,2025-09-08 00:00:00,2025-09-15 00:00:00,2025-09-29 00:00:00,2025-10-08 00:00:00,2025-10-28 00:00:00,2025-11-13 00:00:00,2025-11-27 00:00:00,2025-12-11 00:00:00,2026-01-13 00:00:00,2026-01-20 00:00:00,nan
32,16,Подготовка материалов предварительной оценки г...,nan,Дата окончания,nan,nan,2025-06-27 00:00:00,-,-,-,штаб Мертро ЕВВ 01.04.25,Градполитика 17.04.25,nan,nan,nan,nan,nan,nan,nan,1. Градпотенциал поддержан на Градполитике 17....
33,nan,nan,nan,Дата окончания факт,Выполнено,Выполнено,nan,-,-,-,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan

In [166]:
inner_df.dropna(axis=0, how='all', inplace=True)
inner_df = inner_df.iloc[3:]
inner_df.columns = inner_df.iloc[0]
inner_df = inner_df.drop(3).reset_index(drop=True)

In [167]:
inner_df

3,№,Наименование работы,Квартал утверждения ППТ,nan,Разработка материалов существующего положения + эскизы,"Рассмотрение эскизов, выбор рекомендуемого варианта",Разработка обосновывающих материалов проектного предложения,"Расмотрение обосновывающих материалов, получение замечаний","Корректировка обосновывающих материалов по замечаниям ОИВ, повторная рассылка","Корректировка материалов по замечаниям ОИВ, Подготовка и согласование макета и НПМ, получение согласований ОИВ",Подготовка презентации на ГЗК,Проведение \nРГ ГЗК И ГЗК,Подготовка \nУтв . Части,ПУ МКА,АИС СД \nУКД,АИС СД \nОИВ,Доработка материалов по замч ОИВ,ПУ ПМ,ОАУ ПМ,nan
0,1,Подготовка проекта планировки территории транс...,3 кв 2025,Дата окончания,nan,nan,nan,2025-01-27 00:00:00,2025-03-21 00:00:00,2025-04-21 00:00:00,2025-03-19 00:00:00,(26.03.2025)\n09.04.2025,(28.03.2025)\n02.04.2025,2025-05-19 00:00:00,2025-06-02 00:00:00,2025-06-16 00:00:00,2025-06-30 00:00:00,2025-07-28 00:00:00,2025-08-04 00:00:00,Повторное рассмотрение на штабе метро у ЕВВ 22...
1,nan,nan,nan,Дата окончания факт,Выполнено,2024-11-19 00:00:00,2024-12-28 00:00:00,2025-02-10 00:00:00,2025-03-21 00:00:00,nan,2025-03-19 00:00:00,nan,2025-04-02 00:00:00,nan,nan,nan,nan,nan,nan,nan
2,2,Подготовка проекта планировки территории транс...,3 кв 2025,Дата окончания,nan,nan,nan,2025-02-27 00:00:00,2025-03-31 00:00:00,2025-04-27 00:00:00,2025-03-26 00:00:00,(09.04.2025)\n16.04.2025,2025-04-25 00:00:00,2025-05-30 00:00:00,2025-06-13 00:00:00,2025-06-27 00:00:00,2025-07-11 00:00:00,2025-08-08 00:00:00,2025-08-15 00:00:00,Повторное рассмотрение на штабе метро у ЕВВ 22...
3,nan,nan,nan,Дата окончания факт,Выполнено,2024-12-10 00:00:00,2025-01-28 00:00:00,2025-02-28 00:00:00,2025-03-31 00:00:00,nan,2025-04-03 00:00:00,nan,nan,nan,nan,nan,nan,nan,nan,nan
4,3,Подготовка проекта планировки территории транс...,3 кв 2025,Дата окончания,nan,nan,nan,2025-03-07 00:00:00,(07.04.25)\n28.04.2025,2025-05-07 00:00:00,2025-03-19 00:00:00,(27.03.2025)\n16.04.2025,2025-04-28 00:00:00,2025-06-09 00:00:00,2025-06-23 00:00:00,2025-07-07 00:00:00,2025-07-21 00:00:00,2025-08-18 00:00:00,2025-08-25 00:00:00,Повторное рассмотрение на штабе метро у ЕВВ 22...
5,nan,nan,nan,Дата окончания факт,Выполнено,2024-12-10 00:00:00,2025-02-05 00:00:00,2025-03-17 00:00:00,nan,nan,2025-03-20 00:00:00,nan,nan,nan,nan,nan,nan,nan,nan,nan
6,4,Подготовка проекта планировки территории транс...,3 кв 2025,Дата окончания,nan,nan,nan,2025-01-27 00:00:00,(04.04.2025)\n11.04.2025,2025-05-04 00:00:00,2025-04-16 00:00:00,2025-04-23 00:00:00,2025-04-25 00:00:00,2025-06-06 00:00:00,2025-06-16 00:00:00,2025-06-26 00:00:00,2025-07-03 00:00:00,2025-07-22 00:00:00,2025-07-29 00:00:00,Повторное рассмотрение на штабе метро у ЕВВ 22...
7,nan,nan,nan,Дата окончания факт,Выполнено,2024-11-19 00:00:00,2024-12-28 00:00:00,2025-02-10 00:00:00,2025-04-10 00:00:00,nan,2025-04-16 00:00:00,nan,nan,nan,nan,nan,nan,nan,nan,nan
8,5,Подготовка проекта планировки территории транс...,3 кв 2025,Дата окончания,nan,nan,nan,2025-04-10 00:00:00,2025-04-03 00:00:00,2025-05-03 00:00:00,2025-04-16 00:00:00,2025-04-24 00:00:00,2025-05-31 00:00:00,2025-06-21 00:00:00,2025-07-05 00:00:00,2025-07-19 00:00:00,2025-08-02 00:00:00,2025-08-30 00:00:00,2025-09-06 00:00:00,Материалы с жилой застройко были подготовлены ...
9,nan,nan,nan,Дата окончания факт,Выполнено,2024-12-10 00:00:00,2025-02-11 00:00:00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
10,6,Подготовка проекта планировки территории транс...,4 кв 2025,Дата окончания,nan,nan,2025-03-10 00:00:00,2025-04-09 00:00:00,2025-04-23 00:00:00,2025-05-23 00:00:00,2025-04-30 00:00:00,2025-06-13 00:00:00,2025-06-06 00:00:00,2025-07-04 00:00:00,2025-07-18 00:00:00,2025-08-01 00:00:00,2025-08-15 00:00:00,2025-09-12 00:00:00,2025-09-19 00:00:00,"Отработка замечаний ОИВ, готовится повторная р..."
11,nan,nan,nan,Дата окончания факт,Выполнено,2025-01-29 00:00:00,2025-03-10 00:00:00,2025-04-09 00:00:00,2025-04-24 00:00:00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
12,7,Подготовка проекта планировки территории транс...,4 кв 2025,Дата окончания,Выполнено,2025-05-27 00:00:00,2025-04-17 00:00:00,2025-05-17 00:00:00,2025-05-31 00:00:00,2025-06-30 00:00:00,2025-07-07 00:00:00,2025-07-15 00:00:00,2025-07-28 00:00:00,2025-08-18 00:00:00,2025-09-01 00:00:00,2025-09-15 00:00:00,2025-09-29 00:00:00,2025-10-27 00:00:00,2025-11-03 00:00:00,ОМ на согласовании в ОИВ
13,nan,nan,nan,Дата окончания факт,nan,2025-04-17 00:00:00,2025-04-17 00:00:00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
14,8,Подготовка проекта планировки территории транс...,4 кв 2025,Дата окончания,Выполнено,2025-04-11 00:00:00,2025-05-05 00:00:00,2025-06-04 00:00:00,2025-06-18 00:00:00,2025-07-18 00:00:00,2025-08-01 00:00:00,2025-08-15 00:00:00,2025-08-01 00:00:00,2025-09-05 00:00:00,2025-09-19 00:00:00,2025-10-03 00:00:00,2025-10-17 00:00:00,2025-11-14 00:00:00,2025-11-21 00:00:00,"Приоритетный эскиз не выбран, идет отработка м..."
15,nan,nan,nan,Дата окончания факт,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
16,9,Подготовка проекта планировки территории транс...,4 кв 2025,Дата окончания,2025-04-14 00:00:00,2025-04-21 00:00:00,2025-05-21 00:00:00,2025-06-17 00:00:00,2025-07-01 00:00:00,2025-07-31 00:00:00,2025-07-24 00:00:00,2025-08-03 00:00:00,2025-08-22 00:00:00,2025-08-29 00:00:00,2025-09-12 00:00:00,2025-10-10 00:00:00,2025-10-24 00:00:00,2025-10-27 00:00:00,2025-11-28 00:00:00,1. Подготовлено 2 вар эскиза \n2. план пересел...
17,nan,nan,nan,Дата окончания факт,2025-04-15 00:00:00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
18,10,Подготовка проекта планировки территории транс...,1 кв 2026,Дата окончания,Выполнено,2025-05-30 00:00:00,2025-06-30 00:00:00,2025-07-30 00:00:00,2025-08-13 00:00:00,2025-09-12 00:00:00,2025-09-19 00:00:00,2025-09-27 00:00:00,2025-10-10 00:00:00,2025-10-31 00:00:00,2025-11-14 00:00:00,2025-11-28 00:00:00,2025-12-12 00:00:00,2026-01-09 00:00:00,2026-01-16 00:00:00,1.\tЭскиз рассмотрен на штабе метро ЕВВ 25.03....
19,nan,nan,nan,Дата окончания факт,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
20,11,Подготовка проекта планировки территории транс...,1 кв 2026,Дата окончания,Выполнено,2025-05-31 00:00:00,2025-07-01 00:00:00,2025-07-31 00:00:00,2025-08-14 00:00:00,2025-09-13 00:00:00,2025-09-27 00:00:00,2025-10-11 00:00:00,2025-09-27 00:00:00,2025-11-01 00:00:00,2025-11-15 00:00:00,2025-11-29 00:00:00,2025-12-13 00:00:00,2026-01-10 00:00:00,2026-01-17 00:00:00,"1.\tЭскиз направлен на доработку, предложено р..."
21,nan,nan,nan,Дата окончания факт,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
22,12,Подготовка проекта планировки территории транс...,1 кв 2026,Дата окончания,Выполнено,2025-06-06 00:00:00,2025-07-07 00:00:00,2025-08-06 00:00:00,2025-08-20 00:00:00,2025-08-20 00:00:00,2025-09-26 00:00:00,2025-10-04 00:00:00,2025-10-03 00:00:00,2025-11-07 00:00:00,2025-11-21 00:00:00,2025-12-05 00:00:00,2025-12-19 00:00:00,2026-01-16 00:00:00,2026-01-23 00:00:00,"1.\tЭскиз направлен на доработку, предложено р..."
23,nan,nan,nan,Дата окончания факт,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
24,13,Подготовка проект планировки территории трансп...,4 кв 2025,Дата окончания,Выполнено,Выполнено,2025-04-25 00:00:00,2025-05-25 00:00:00,2025-06-08 00:00:00,2025-07-08 00:00:00,2025-07-15 00:00:00,2025-07-23 00:00:00,2025-08-07 00:00:00,2025-08-14 00:00:00,2025-09-11 00:00:00,2025-09-25 00:00:00,2025-11-14 00:00:00,2025-12-17 00:00:00,2025-12-24 00:00:00,1. Обосновывающие материалы готовятся к рассыл...
25,nan,nan,nan,Дата окончания факт,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
26,14,Проект планировки территории линейного объекта...,4 кв 2025,Дата окончания,Выполнено,Выполнено,2025-04-29 00:00:00,2025-05-28 00:00:00,2025-06-18 00:00:00,2025-06-18 00:00:00,2025-07-03 00:00:00,2025-07-03 00:00:00,2025-07-18 00:00:00,2025-07-25 00:00:00,2025-08-08 00:00:00,2025-08-15 00:00:00,2025-09-17 00:00:00,2025-09-30 00:00:00,2025-10-10 00:00:00,Обосновывающие материалы в рассылке в ОИВ с 16...
27,15,"Подготовка ППТ, ограниченной Промышленным прое...",4 кв 2025,Дата окончания факт,nan,nan,2025-07-02 00:00:00,2025-07-29 00:00:00,2025-08-11 00:00:00,2025-09-08 00:00:00,2025-09-15 00:00:00,2025-09-29 00:00:00,2025-10-08 00:00:00,2025-10-28 00:00:00,2025-11-13 00:00:00,2025-11-27 00:00:00,2025-12-11 00:00:00,2026-01-13 00:00:00,2026-01-20 00:00:00,nan
28,16,Подготовка материалов предварительной оценки г...,nan,Дата окончания,nan,nan,2025-06-27 00:00:00,-,-,-,штаб Мертро ЕВВ 01.04.25,Градполитика 17.04.25,nan,nan,nan,nan,nan,nan,nan,1. Градпотенциал поддержан на Градполитике 17....
29,nan,nan,nan,Дата окончания факт,Выполнено,Выполнено,nan,-,-,-,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan

In [168]:
inner_df.columns.values[3] = 'Дата'
inner_df.columns.values[-1] = 'Статус'
inner_df.columns = inner_df.columns.str.replace('\n', '', regex=False)
inner_df.columns = inner_df.columns.str.strip()
inner_df = inner_df.replace(r'\n',' ', regex=True)
inner_df = inner_df.replace(r'\t',' ', regex=True)
inner_df

3,№,Наименование работы,Квартал утверждения ППТ,Дата,Разработка материалов существующего положения + эскизы,"Рассмотрение эскизов, выбор рекомендуемого варианта",Разработка обосновывающих материалов проектного предложения,"Расмотрение обосновывающих материалов, получение замечаний","Корректировка обосновывающих материалов по замечаниям ОИВ, повторная рассылка","Корректировка материалов по замечаниям ОИВ, Подготовка и согласование макета и НПМ, получение согласований ОИВ",Подготовка презентации на ГЗК,Проведение РГ ГЗК И ГЗК,Подготовка Утв . Части,ПУ МКА,АИС СД УКД,АИС СД ОИВ,Доработка материалов по замч ОИВ,ПУ ПМ,ОАУ ПМ,Статус
0,1,Подготовка проекта планировки территории транс...,3 кв 2025,Дата окончания,nan,nan,nan,2025-01-27 00:00:00,2025-03-21 00:00:00,2025-04-21 00:00:00,2025-03-19 00:00:00,(26.03.2025) 09.04.2025,(28.03.2025) 02.04.2025,2025-05-19 00:00:00,2025-06-02 00:00:00,2025-06-16 00:00:00,2025-06-30 00:00:00,2025-07-28 00:00:00,2025-08-04 00:00:00,Повторное рассмотрение на штабе метро у ЕВВ 22...
1,nan,nan,nan,Дата окончания факт,Выполнено,2024-11-19 00:00:00,2024-12-28 00:00:00,2025-02-10 00:00:00,2025-03-21 00:00:00,nan,2025-03-19 00:00:00,nan,2025-04-02 00:00:00,nan,nan,nan,nan,nan,nan,nan
2,2,Подготовка проекта планировки территории транс...,3 кв 2025,Дата окончания,nan,nan,nan,2025-02-27 00:00:00,2025-03-31 00:00:00,2025-04-27 00:00:00,2025-03-26 00:00:00,(09.04.2025) 16.04.2025,2025-04-25 00:00:00,2025-05-30 00:00:00,2025-06-13 00:00:00,2025-06-27 00:00:00,2025-07-11 00:00:00,2025-08-08 00:00:00,2025-08-15 00:00:00,Повторное рассмотрение на штабе метро у ЕВВ 22...
3,nan,nan,nan,Дата окончания факт,Выполнено,2024-12-10 00:00:00,2025-01-28 00:00:00,2025-02-28 00:00:00,2025-03-31 00:00:00,nan,2025-04-03 00:00:00,nan,nan,nan,nan,nan,nan,nan,nan,nan
4,3,Подготовка проекта планировки территории транс...,3 кв 2025,Дата окончания,nan,nan,nan,2025-03-07 00:00:00,(07.04.25) 28.04.2025,2025-05-07 00:00:00,2025-03-19 00:00:00,(27.03.2025) 16.04.2025,2025-04-28 00:00:00,2025-06-09 00:00:00,2025-06-23 00:00:00,2025-07-07 00:00:00,2025-07-21 00:00:00,2025-08-18 00:00:00,2025-08-25 00:00:00,Повторное рассмотрение на штабе метро у ЕВВ 22...
5,nan,nan,nan,Дата окончания факт,Выполнено,2024-12-10 00:00:00,2025-02-05 00:00:00,2025-03-17 00:00:00,nan,nan,2025-03-20 00:00:00,nan,nan,nan,nan,nan,nan,nan,nan,nan
6,4,Подготовка проекта планировки территории транс...,3 кв 2025,Дата окончания,nan,nan,nan,2025-01-27 00:00:00,(04.04.2025) 11.04.2025,2025-05-04 00:00:00,2025-04-16 00:00:00,2025-04-23 00:00:00,2025-04-25 00:00:00,2025-06-06 00:00:00,2025-06-16 00:00:00,2025-06-26 00:00:00,2025-07-03 00:00:00,2025-07-22 00:00:00,2025-07-29 00:00:00,Повторное рассмотрение на штабе метро у ЕВВ 22...
7,nan,nan,nan,Дата окончания факт,Выполнено,2024-11-19 00:00:00,2024-12-28 00:00:00,2025-02-10 00:00:00,2025-04-10 00:00:00,nan,2025-04-16 00:00:00,nan,nan,nan,nan,nan,nan,nan,nan,nan
8,5,Подготовка проекта планировки территории транс...,3 кв 2025,Дата окончания,nan,nan,nan,2025-04-10 00:00:00,2025-04-03 00:00:00,2025-05-03 00:00:00,2025-04-16 00:00:00,2025-04-24 00:00:00,2025-05-31 00:00:00,2025-06-21 00:00:00,2025-07-05 00:00:00,2025-07-19 00:00:00,2025-08-02 00:00:00,2025-08-30 00:00:00,2025-09-06 00:00:00,Материалы с жилой застройко были подготовлены ...
9,nan,nan,nan,Дата окончания факт,Выполнено,2024-12-10 00:00:00,2025-02-11 00:00:00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
10,6,Подготовка проекта планировки территории транс...,4 кв 2025,Дата окончания,nan,nan,2025-03-10 00:00:00,2025-04-09 00:00:00,2025-04-23 00:00:00,2025-05-23 00:00:00,2025-04-30 00:00:00,2025-06-13 00:00:00,2025-06-06 00:00:00,2025-07-04 00:00:00,2025-07-18 00:00:00,2025-08-01 00:00:00,2025-08-15 00:00:00,2025-09-12 00:00:00,2025-09-19 00:00:00,"Отработка замечаний ОИВ, готовится повторная р..."
11,nan,nan,nan,Дата окончания факт,Выполнено,2025-01-29 00:00:00,2025-03-10 00:00:00,2025-04-09 00:00:00,2025-04-24 00:00:00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
12,7,Подготовка проекта планировки территории транс...,4 кв 2025,Дата окончания,Выполнено,2025-05-27 00:00:00,2025-04-17 00:00:00,2025-05-17 00:00:00,2025-05-31 00:00:00,2025-06-30 00:00:00,2025-07-07 00:00:00,2025-07-15 00:00:00,2025-07-28 00:00:00,2025-08-18 00:00:00,2025-09-01 00:00:00,2025-09-15 00:00:00,2025-09-29 00:00:00,2025-10-27 00:00:00,2025-11-03 00:00:00,ОМ на согласовании в ОИВ
13,nan,nan,nan,Дата окончания факт,nan,2025-04-17 00:00:00,2025-04-17 00:00:00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
14,8,Подготовка проекта планировки территории транс...,4 кв 2025,Дата окончания,Выполнено,2025-04-11 00:00:00,2025-05-05 00:00:00,2025-06-04 00:00:00,2025-06-18 00:00:00,2025-07-18 00:00:00,2025-08-01 00:00:00,2025-08-15 00:00:00,2025-08-01 00:00:00,2025-09-05 00:00:00,2025-09-19 00:00:00,2025-10-03 00:00:00,2025-10-17 00:00:00,2025-11-14 00:00:00,2025-11-21 00:00:00,"Приоритетный эскиз не выбран, идет отработка м..."
15,nan,nan,nan,Дата окончания факт,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
16,9,Подготовка проекта планировки территории транс...,4 кв 2025,Дата окончания,2025-04-14 00:00:00,2025-04-21 00:00:00,2025-05-21 00:00:00,2025-06-17 00:00:00,2025-07-01 00:00:00,2025-07-31 00:00:00,2025-07-24 00:00:00,2025-08-03 00:00:00,2025-08-22 00:00:00,2025-08-29 00:00:00,2025-09-12 00:00:00,2025-10-10 00:00:00,2025-10-24 00:00:00,2025-10-27 00:00:00,2025-11-28 00:00:00,1. Подготовлено 2 вар эскиза 2. план переселе...
17,nan,nan,nan,Дата окончания факт,2025-04-15 00:00:00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
18,10,Подготовка проекта планировки территории транс...,1 кв 2026,Дата окончания,Выполнено,2025-05-30 00:00:00,2025-06-30 00:00:00,2025-07-30 00:00:00,2025-08-13 00:00:00,2025-09-12 00:00:00,2025-09-19 00:00:00,2025-09-27 00:00:00,2025-10-10 00:00:00,2025-10-31 00:00:00,2025-11-14 00:00:00,2025-11-28 00:00:00,2025-12-12 00:00:00,2026-01-09 00:00:00,2026-01-16 00:00:00,1. Эскиз рассмотрен на штабе метро ЕВВ 25.03.2...
19,nan,nan,nan,Дата окончания факт,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
20,11,Подготовка проекта планировки территории транс...,1 кв 2026,Дата окончания,Выполнено,2025-05-31 00:00:00,2025-07-01 00:00:00,2025-07-31 00:00:00,2025-08-14 00:00:00,2025-09-13 00:00:00,2025-09-27 00:00:00,2025-10-11 00:00:00,2025-09-27 00:00:00,2025-11-01 00:00:00,2025-11-15 00:00:00,2025-11-29 00:00:00,2025-12-13 00:00:00,2026-01-10 00:00:00,2026-01-17 00:00:00,"1. Эскиз направлен на доработку, предложено ра..."
21,nan,nan,nan,Дата окончания факт,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
22,12,Подготовка проекта планировки территории транс...,1 кв 2026,Дата окончания,Выполнено,2025-06-06 00:00:00,2025-07-07 00:00:00,2025-08-06 00:00:00,2025-08-20 00:00:00,2025-08-20 00:00:00,2025-09-26 00:00:00,2025-10-04 00:00:00,2025-10-03 00:00:00,2025-11-07 00:00:00,2025-11-21 00:00:00,2025-12-05 00:00:00,2025-12-19 00:00:00,2026-01-16 00:00:00,2026-01-23 00:00:00,"1. Эскиз направлен на доработку, предложено ра..."
23,nan,nan,nan,Дата окончания факт,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
24,13,Подготовка проект планировки территории трансп...,4 кв 2025,Дата окончания,Выполнено,Выполнено,2025-04-25 00:00:00,2025-05-25 00:00:00,2025-06-08 00:00:00,2025-07-08 00:00:00,2025-07-15 00:00:00,2025-07-23 00:00:00,2025-08-07 00:00:00,2025-08-14 00:00:00,2025-09-11 00:00:00,2025-09-25 00:00:00,2025-11-14 00:00:00,2025-12-17 00:00:00,2025-12-24 00:00:00,1. Обосновывающие материалы готовятся к рассыл...
25,nan,nan,nan,Дата окончания факт,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
26,14,Проект планировки территории линейного объекта...,4 кв 2025,Дата окончания,Выполнено,Выполнено,2025-04-29 00:00:00,2025-05-28 00:00:00,2025-06-18 00:00:00,2025-06-18 00:00:00,2025-07-03 00:00:00,2025-07-03 00:00:00,2025-07-18 00:00:00,2025-07-25 00:00:00,2025-08-08 00:00:00,2025-08-15 00:00:00,2025-09-17 00:00:00,2025-09-30 00:00:00,2025-10-10 00:00:00,Обосновывающие материалы в рассылке в ОИВ с 16...
27,15,"Подготовка ППТ, ограниченной Промышленным прое...",4 кв 2025,Дата окончания факт,nan,nan,2025-07-02 00:00:00,2025-07-29 00:00:00,2025-08-11 00:00:00,2025-09-08 00:00:00,2025-09-15 00:00:00,2025-09-29 00:00:00,2025-10-08 00:00:00,2025-10-28 00:00:00,2025-11-13 00:00:00,2025-11-27 00:00:00,2025-12-11 00:00:00,2026-01-13 00:00:00,2026-01-20 00:00:00,nan
28,16,Подготовка материалов предварительной оценки г...,nan,Дата окончания,nan,nan,2025-06-27 00:00:00,-,-,-,штаб Мертро ЕВВ 01.04.25,Градполитика 17.04.25,nan,nan,nan,nan,nan,nan,nan,1. Градпотенциал поддержан на Градполитике 17....
29,nan,nan,nan,Дата окончания факт,Выполнено,Выполнено,nan,-,-,-,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan

In [173]:
result_list = []
i = 0
while i < len(inner_df):
    result = dict()
    if (inner_df["Наименование работы"][i] != 'nan') and (inner_df["Наименование работы"][i+1] == 'nan'):
        step = 2
    else:
        step = 1
    part_df = inner_df.iloc[i:i+step]  # Получаем одну/две строки
    result = part_df.iloc[0,:3].to_dict() # попробовать dict
    result.update(part_df[["Статус"]].iloc[[0]].to_dict(orient='records')[0])
    i+=step
    part_df = part_df.set_index('Дата').iloc[:,3:-1].to_dict()
    result.update(part_df)
    # result.update(part_df)
    # print(part_df.to_dict())
    # print(result)
    # print(json.dumps(result, indent=4, ensure_ascii=False))
    # print(part_df.keys())
    result_list.append(result)
    # line = inner_df.iloc[i:i+1]
    # result = line.iloc[0,:3].to_dict() # попробовать dict
    # # result.update(pair[["Статус"]].iloc[[0]].to_dict(orient='records')[0])
    # # result.update(pair.loc[0, "Статус"].to_dict())
    # print(json.dumps(result, indent=4, ensure_ascii=False))
print(json.dumps(result_list, indent=4, ensure_ascii=False))

dict_keys(['Разработка материалов существующего положения + эскизы', 'Рассмотрение эскизов, выбор рекомендуемого варианта', 'Разработка обосновывающих материалов проектного предложения', 'Расмотрение обосновывающих материалов, получение замечаний', 'Корректировка обосновывающих материалов по замечаниям ОИВ, повторная рассылка', 'Корректировка материалов по замечаниям ОИВ, Подготовка и согласование макета и НПМ, получение согласований ОИВ', 'Подготовка презентации на ГЗК', 'Проведение РГ ГЗК И ГЗК', 'Подготовка Утв . Части', 'ПУ МКА', 'АИС СД УКД', 'АИС СД ОИВ', 'Доработка материалов по замч ОИВ', 'ПУ ПМ', 'ОАУ ПМ'])
dict_keys(['Разработка материалов существующего положения + эскизы', 'Рассмотрение эскизов, выбор рекомендуемого варианта', 'Разработка обосновывающих материалов проектного предложения', 'Расмотрение обосновывающих материалов, получение замечаний', 'Корректировка обосновывающих материалов по замечаниям ОИВ, повторная рассылка', 'Корректировка материалов по замечаниям ОИВ, Подготовка и согласование макета и НПМ, получение согласований ОИВ', 'Подготовка презентации на ГЗК', 'Проведение РГ ГЗК И ГЗК', 'Подготовка Утв . Части', 'ПУ МКА', 'АИС СД УКД', 'АИС СД ОИВ', 'Доработка материалов по замч ОИВ', 'ПУ ПМ', 'ОАУ ПМ'])
dict_keys(['Разработка материалов существующего положения + эскизы', 'Рассмотрение эскизов, выбор рекомендуемого варианта', 'Разработка обосновывающих материалов проектного предложения', 'Расмотрение обосновывающих материалов, получение замечаний', 'Корректировка обосновывающих материалов по замечаниям ОИВ, повторная рассылка', 'Корректировка материалов по замечаниям ОИВ, Подготовка и согласование макета и НПМ, получение согласований ОИВ', 'Подготовка презентации на ГЗК', 'Проведение РГ ГЗК И ГЗК', 'Подготовка Утв . Части', 'ПУ МКА', 'АИС СД УКД', 'АИС СД ОИВ', 'Доработка материалов по замч ОИВ', 'ПУ ПМ', 'ОАУ ПМ'])
dict_keys(['Разработка материалов существующего положения + эскизы', 'Рассмотрение эскизов, выбор рекомендуемого варианта', 'Разработка обосновывающих материалов проектного предложения', 'Расмотрение обосновывающих материалов, получение замечаний', 'Корректировка обосновывающих материалов по замечаниям ОИВ, повторная рассылка', 'Корректировка материалов по замечаниям ОИВ, Подготовка и согласование макета и НПМ, получение согласований ОИВ', 'Подготовка презентации на ГЗК', 'Проведение РГ ГЗК И ГЗК', 'Подготовка Утв . Части', 'ПУ МКА', 'АИС СД УКД', 'АИС СД ОИВ', 'Доработка материалов по замч ОИВ', 'ПУ ПМ', 'ОАУ ПМ'])
dict_keys(['Разработка материалов существующего положения + эскизы', 'Рассмотрение эскизов, выбор рекомендуемого варианта', 'Разработка обосновывающих материалов проектного предложения', 'Расмотрение обосновывающих материалов, получение замечаний', 'Корректировка обосновывающих материалов по замечаниям ОИВ, повторная рассылка', 'Корректировка материалов по замечаниям ОИВ, Подготовка и согласование макета и НПМ, получение согласований ОИВ', 'Подготовка презентации на ГЗК', 'Проведение РГ ГЗК И ГЗК', 'Подготовка Утв . Части', 'ПУ МКА', 'АИС СД УКД', 'АИС СД ОИВ', 'Доработка материалов по замч ОИВ', 'ПУ ПМ', 'ОАУ ПМ'])
dict_keys(['Разработка материалов существующего положения + эскизы', 'Рассмотрение эскизов, выбор рекомендуемого варианта', 'Разработка обосновывающих материалов проектного предложения', 'Расмотрение обосновывающих материалов, получение замечаний', 'Корректировка обосновывающих материалов по замечаниям ОИВ, повторная рассылка', 'Корректировка материалов по замечаниям ОИВ, Подготовка и согласование макета и НПМ, получение согласований ОИВ', 'Подготовка презентации на ГЗК', 'Проведение РГ ГЗК И ГЗК', 'Подготовка Утв . Части', 'ПУ МКА', 'АИС СД УКД', 'АИС СД ОИВ', 'Доработка материалов по замч ОИВ', 'ПУ ПМ', 'ОАУ ПМ'])
dict_keys(['Разработка материалов существующего положения + эскизы', 'Рассмотрение эскизов, выбор рекомендуемого варианта', 'Разработка обосновывающих материалов проектного предложения', 'Расмотрение обосновывающих материалов, получение замечаний', 'Корректировка обосновывающих материалов по замечаниям ОИВ, повторная рассылка', 'Корректировка материалов по замечаниям ОИВ, Подготовка и согласование макета и НПМ, получение согласований ОИВ', 'Подготовка презентации на ГЗК', 'Проведение РГ ГЗК И ГЗК', 'Подготовка Утв . Части', 'ПУ МКА', 'АИС СД УКД', 'АИС СД ОИВ', 'Доработка материалов по замч ОИВ', 'ПУ ПМ', 'ОАУ ПМ'])
dict_keys(['Разработка материалов существующего положения + эскизы', 'Рассмотрение эскизов, выбор рекомендуемого варианта', 'Разработка обосновывающих материалов проектного предложения', 'Расмотрение обосновывающих материалов, получение замечаний', 'Корректировка обосновывающих материалов по замечаниям ОИВ, повторная рассылка', 'Корректировка материалов по замечаниям ОИВ, Подготовка и согласование макета и НПМ, получение согласований ОИВ', 'Подготовка презентации на ГЗК', 'Проведение РГ ГЗК И ГЗК', 'Подготовка Утв . Части', 'ПУ МКА', 'АИС СД УКД', 'АИС СД ОИВ', 'Доработка материалов по замч ОИВ', 'ПУ ПМ', 'ОАУ ПМ'])
dict_keys(['Разработка материалов существующего положения + эскизы', 'Рассмотрение эскизов, выбор рекомендуемого варианта', 'Разработка обосновывающих материалов проектного предложения', 'Расмотрение обосновывающих материалов, получение замечаний', 'Корректировка обосновывающих материалов по замечаниям ОИВ, повторная рассылка', 'Корректировка материалов по замечаниям ОИВ, Подготовка и согласование макета и НПМ, получение согласований ОИВ', 'Подготовка презентации на ГЗК', 'Проведение РГ ГЗК И ГЗК', 'Подготовка Утв . Части', 'ПУ МКА', 'АИС СД УКД', 'АИС СД ОИВ', 'Доработка материалов по замч ОИВ', 'ПУ ПМ', 'ОАУ ПМ'])
dict_keys(['Разработка материалов существующего положения + эскизы', 'Рассмотрение эскизов, выбор рекомендуемого варианта', 'Разработка обосновывающих материалов проектного предложения', 'Расмотрение обосновывающих материалов, получение замечаний', 'Корректировка обосновывающих материалов по замечаниям ОИВ, повторная рассылка', 'Корректировка материалов по замечаниям ОИВ, Подготовка и согласование макета и НПМ, получение согласований ОИВ', 'Подготовка презентации на ГЗК', 'Проведение РГ ГЗК И ГЗК', 'Подготовка Утв . Части', 'ПУ МКА', 'АИС СД УКД', 'АИС СД ОИВ', 'Доработка материалов по замч ОИВ', 'ПУ ПМ', 'ОАУ ПМ'])
dict_keys(['Разработка материалов существующего положения + эскизы', 'Рассмотрение эскизов, выбор рекомендуемого варианта', 'Разработка обосновывающих материалов проектного предложения', 'Расмотрение обосновывающих материалов, получение замечаний', 'Корректировка обосновывающих материалов по замечаниям ОИВ, повторная рассылка', 'Корректировка материалов по замечаниям ОИВ, Подготовка и согласование макета и НПМ, получение согласований ОИВ', 'Подготовка презентации на ГЗК', 'Проведение РГ ГЗК И ГЗК', 'Подготовка Утв . Части', 'ПУ МКА', 'АИС СД УКД', 'АИС СД ОИВ', 'Доработка материалов по замч ОИВ', 'ПУ ПМ', 'ОАУ ПМ'])
dict_keys(['Разработка материалов существующего положения + эскизы', 'Рассмотрение эскизов, выбор рекомендуемого варианта', 'Разработка обосновывающих материалов проектного предложения', 'Расмотрение обосновывающих материалов, получение замечаний', 'Корректировка обосновывающих материалов по замечаниям ОИВ, повторная рассылка', 'Корректировка материалов по замечаниям ОИВ, Подготовка и согласование макета и НПМ, получение согласований ОИВ', 'Подготовка презентации на ГЗК', 'Проведение РГ ГЗК И ГЗК', 'Подготовка Утв . Части', 'ПУ МКА', 'АИС СД УКД', 'АИС СД ОИВ', 'Доработка материалов по замч ОИВ', 'ПУ ПМ', 'ОАУ ПМ'])
dict_keys(['Разработка материалов существующего положения + эскизы', 'Рассмотрение эскизов, выбор рекомендуемого варианта', 'Разработка обосновывающих материалов проектного предложения', 'Расмотрение обосновывающих материалов, получение замечаний', 'Корректировка обосновывающих материалов по замечаниям ОИВ, повторная рассылка', 'Корректировка материалов по замечаниям ОИВ, Подготовка и согласование макета и НПМ, получение согласований ОИВ', 'Подготовка презентации на ГЗК', 'Проведение РГ ГЗК И ГЗК', 'Подготовка Утв . Части', 'ПУ МКА', 'АИС СД УКД', 'АИС СД ОИВ', 'Доработка материалов по замч ОИВ', 'ПУ ПМ', 'ОАУ ПМ'])
dict_keys(['Разработка материалов существующего положения + эскизы', 'Рассмотрение эскизов, выбор рекомендуемого варианта', 'Разработка обосновывающих материалов проектного предложения', 'Расмотрение обосновывающих материалов, получение замечаний', 'Корректировка обосновывающих материалов по замечаниям ОИВ, повторная рассылка', 'Корректировка материалов по замечаниям ОИВ, Подготовка и согласование макета и НПМ, получение согласований ОИВ', 'Подготовка презентации на ГЗК', 'Проведение РГ ГЗК И ГЗК', 'Подготовка Утв . Части', 'ПУ МКА', 'АИС СД УКД', 'АИС СД ОИВ', 'Доработка материалов по замч ОИВ', 'ПУ ПМ', 'ОАУ ПМ'])
dict_keys(['Разработка материалов существующего положения + эскизы', 'Рассмотрение эскизов, выбор рекомендуемого варианта', 'Разработка обосновывающих материалов проектного предложения', 'Расмотрение обосновывающих материалов, получение замечаний', 'Корректировка обосновывающих материалов по замечаниям ОИВ, повторная рассылка', 'Корректировка материалов по замечаниям ОИВ, Подготовка и согласование макета и НПМ, получение согласований ОИВ', 'Подготовка презентации на ГЗК', 'Проведение РГ ГЗК И ГЗК', 'Подготовка Утв . Части', 'ПУ МКА', 'АИС СД УКД', 'АИС СД ОИВ', 'Доработка материалов по замч ОИВ', 'ПУ ПМ', 'ОАУ ПМ'])
dict_keys(['Разработка материалов существующего положения + эскизы', 'Рассмотрение эскизов, выбор рекомендуемого варианта', 'Разработка обосновывающих материалов проектного предложения', 'Расмотрение обосновывающих материалов, получение замечаний', 'Корректировка обосновывающих материалов по замечаниям ОИВ, повторная рассылка', 'Корректировка материалов по замечаниям ОИВ, Подготовка и согласование макета и НПМ, получение согласований ОИВ', 'Подготовка презентации на ГЗК', 'Проведение РГ ГЗК И ГЗК', 'Подготовка Утв . Части', 'ПУ МКА', 'АИС СД УКД', 'АИС СД ОИВ', 'Доработка материалов по замч ОИВ', 'ПУ ПМ', 'ОАУ ПМ'])
[
    {
        "№": "1",
        "Наименование работы": "Подготовка проекта планировки территории транспортно-пересадочного узла \"ЗИЛ\"",
        "Квартал утверждения ППТ": "3 кв 2025",
        "Статус": "Повторное рассмотрение на штабе метро у ЕВВ 22.04.25 (возможность утверждения на ГЗК без НПМ. НПМ готовит инвестор)",
        "Разработка материалов существующего положения + эскизы": {
            "Дата окончания": "nan",
            "Дата окончания факт": "Выполнено"
        },
        "Рассмотрение эскизов, выбор рекомендуемого варианта": {
            "Дата окончания": "nan",
            "Дата окончания факт": "2024-11-19 00:00:00"
        },
        "Разработка обосновывающих материалов проектного предложения": {
            "Дата окончания": "nan",
            "Дата окончания факт": "2024-12-28 00:00:00"
        },
        "Расмотрение обосновывающих материалов, получение замечаний": {
            "Дата окончания": "2025-01-27 00:00:00",
            "Дата окончания факт": "2025-02-10 00:00:00"
        },
        "Корректировка обосновывающих материалов по замечаниям ОИВ, повторная рассылка": {
            "Дата окончания": "2025-03-21 00:00:00",
            "Дата окончания факт": "2025-03-21 00:00:00"
        },
        "Корректировка материалов по замечаниям ОИВ, Подготовка и согласование макета и НПМ, получение согласований ОИВ": {
            "Дата окончания": "2025-04-21 00:00:00",
            "Дата окончания факт": "nan"
        },
        "Подготовка презентации на ГЗК": {
            "Дата окончания": "2025-03-19 00:00:00",
            "Дата окончания факт": "2025-03-19 00:00:00"
        },
        "Проведение РГ ГЗК И ГЗК": {
            "Дата окончания": "(26.03.2025) 09.04.2025",
            "Дата окончания факт": "nan"
        },
        "Подготовка Утв . Части": {
            "Дата окончания": "(28.03.2025) 02.04.2025",
            "Дата окончания факт": "2025-04-02 00:00:00"
        },
        "ПУ МКА": {
            "Дата окончания": "2025-05-19 00:00:00",
            "Дата окончания факт": "nan"
        },
        "АИС СД УКД": {
            "Дата окончания": "2025-06-02 00:00:00",
            "Дата окончания факт": "nan"
        },
        "АИС СД ОИВ": {
            "Дата окончания": "2025-06-16 00:00:00",
            "Дата окончания факт": "nan"
        },
        "Доработка материалов по замч ОИВ": {
            "Дата окончания": "2025-06-30 00:00:00",
            "Дата окончания факт": "nan"
        },
        "ПУ ПМ": {
            "Дата окончания": "2025-07-28 00:00:00",
            "Дата окончания факт": "nan"
        },
        "ОАУ ПМ": {
            "Дата окончания": "2025-08-04 00:00:00",
            "Дата окончания факт": "nan"
        }
    },
    {
        "№": "2",
        "Наименование работы": "Подготовка проекта планировки территории транспортно-пересадочного узла \"Остров мечты\"",
        "Квартал утверждения ППТ": "3 кв 2025",
        "Статус": "Повторное рассмотрение на штабе метро у ЕВВ 22.04.25 (возможность утверждения на ГЗК без НПМ. НПМ готовит инвестор)",
        "Разработка материалов существующего положения + эскизы": {
            "Дата окончания": "nan",
            "Дата окончания факт": "Выполнено"
        },
        "Рассмотрение эскизов, выбор рекомендуемого варианта": {
            "Дата окончания": "nan",
            "Дата окончания факт": "2024-12-10 00:00:00"
        },
        "Разработка обосновывающих материалов проектного предложения": {
            "Дата окончания": "nan",
            "Дата окончания факт": "2025-01-28 00:00:00"
        },
        "Расмотрение обосновывающих материалов, получение замечаний": {
            "Дата окончания": "2025-02-27 00:00:00",
            "Дата окончания факт": "2025-02-28 00:00:00"
        },
        "Корректировка обосновывающих материалов по замечаниям ОИВ, повторная рассылка": {
            "Дата окончания": "2025-03-31 00:00:00",
            "Дата окончания факт": "2025-03-31 00:00:00"
        },
        "Корректировка материалов по замечаниям ОИВ, Подготовка и согласование макета и НПМ, получение согласований ОИВ": {
            "Дата окончания": "2025-04-27 00:00:00",
            "Дата окончания факт": "nan"
        },
        "Подготовка презентации на ГЗК": {
            "Дата окончания": "2025-03-26 00:00:00",
            "Дата окончания факт": "2025-04-03 00:00:00"
        },
        "Проведение РГ ГЗК И ГЗК": {
            "Дата окончания": "(09.04.2025) 16.04.2025",
            "Дата окончания факт": "nan"
        },
        "Подготовка Утв . Части": {
            "Дата окончания": "2025-04-25 00:00:00",
            "Дата окончания факт": "nan"
        },
        "ПУ МКА": {
            "Дата окончания": "2025-05-30 00:00:00",
            "Дата окончания факт": "nan"
        },
        "АИС СД УКД": {
            "Дата окончания": "2025-06-13 00:00:00",
            "Дата окончания факт": "nan"
        },
        "АИС СД ОИВ": {
            "Дата окончания": "2025-06-27 00:00:00",
            "Дата окончания факт": "nan"
        },
        "Доработка материалов по замч ОИВ": {
            "Дата окончания": "2025-07-11 00:00:00",
            "Дата окончания факт": "nan"
        },
        "ПУ ПМ": {
            "Дата окончания": "2025-08-08 00:00:00",
            "Дата окончания факт": "nan"
        },
        "ОАУ ПМ": {
            "Дата окончания": "2025-08-15 00:00:00",
            "Дата окончания факт": "nan"
        }
    },
    {
        "№": "3",
        "Наименование работы": "Подготовка проекта планировки территории транспортно-пересадочного узла \"Народное ополчение\"",
        "Квартал утверждения ППТ": "3 кв 2025",
        "Статус": "Повторное рассмотрение на штабе метро у ЕВВ 22.04.25 (возможность утверждения на ГЗК без НПМ. НПМ готовит инвестор)",
        "Разработка материалов существующего положения + эскизы": {
            "Дата окончания": "nan",
            "Дата окончания факт": "Выполнено"
        },
        "Рассмотрение эскизов, выбор рекомендуемого варианта": {
            "Дата окончания": "nan",
            "Дата окончания факт": "2024-12-10 00:00:00"
        },
        "Разработка обосновывающих материалов проектного предложения": {
            "Дата окончания": "nan",
            "Дата окончания факт": "2025-02-05 00:00:00"
        },
        "Расмотрение обосновывающих материалов, получение замечаний": {
            "Дата окончания": "2025-03-07 00:00:00",
            "Дата окончания факт": "2025-03-17 00:00:00"
        },
        "Корректировка обосновывающих материалов по замечаниям ОИВ, повторная рассылка": {
            "Дата окончания": "(07.04.25) 28.04.2025",
            "Дата окончания факт": "nan"
        },
        "Корректировка материалов по замечаниям ОИВ, Подготовка и согласование макета и НПМ, получение согласований ОИВ": {
            "Дата окончания": "2025-05-07 00:00:00",
            "Дата окончания факт": "nan"
        },
        "Подготовка презентации на ГЗК": {
            "Дата окончания": "2025-03-19 00:00:00",
            "Дата окончания факт": "2025-03-20 00:00:00"
        },
        "Проведение РГ ГЗК И ГЗК": {
            "Дата окончания": "(27.03.2025) 16.04.2025",
            "Дата окончания факт": "nan"
        },
        "Подготовка Утв . Части": {
            "Дата окончания": "2025-04-28 00:00:00",
            "Дата окончания факт": "nan"
        },
        "ПУ МКА": {
            "Дата окончания": "2025-06-09 00:00:00",
            "Дата окончания факт": "nan"
        },
        "АИС СД УКД": {
            "Дата окончания": "2025-06-23 00:00:00",
            "Дата окончания факт": "nan"
        },
        "АИС СД ОИВ": {
            "Дата окончания": "2025-07-07 00:00:00",
            "Дата окончания факт": "nan"
        },
        "Доработка материалов по замч ОИВ": {
            "Дата окончания": "2025-07-21 00:00:00",
            "Дата окончания факт": "nan"
        },
        "ПУ ПМ": {
            "Дата окончания": "2025-08-18 00:00:00",
            "Дата окончания факт": "nan"
        },
        "ОАУ ПМ": {
            "Дата окончания": "2025-08-25 00:00:00",
            "Дата окончания факт": "nan"
        }
    },
    {
        "№": "4",
        "Наименование работы": "Подготовка проекта планировки территории транспортно-пересадочного узла \"Строгино\"",
        "Квартал утверждения ППТ": "3 кв 2025",
        "Статус": "Повторное рассмотрение на штабе метро у ЕВВ 22.04.25 (возможность утверждения на ГЗК без НПМ)",
        "Разработка материалов существующего положения + эскизы": {
            "Дата окончания": "nan",
            "Дата окончания факт": "Выполнено"
        },
        "Рассмотрение эскизов, выбор рекомендуемого варианта": {
            "Дата окончания": "nan",
            "Дата окончания факт": "2024-11-19 00:00:00"
        },
        "Разработка обосновывающих материалов проектного предложения": {
            "Дата окончания": "nan",
            "Дата окончания факт": "2024-12-28 00:00:00"
        },
        "Расмотрение обосновывающих материалов, получение замечаний": {
            "Дата окончания": "2025-01-27 00:00:00",
            "Дата окончания факт": "2025-02-10 00:00:00"
        },
        "Корректировка обосновывающих материалов по замечаниям ОИВ, повторная рассылка": {
            "Дата окончания": "(04.04.2025) 11.04.2025",
            "Дата окончания факт": "2025-04-10 00:00:00"
        },
        "Корректировка материалов по замечаниям ОИВ, Подготовка и согласование макета и НПМ, получение согласований ОИВ": {
            "Дата окончания": "2025-05-04 00:00:00",
            "Дата окончания факт": "nan"
        },
        "Подготовка презентации на ГЗК": {
            "Дата окончания": "2025-04-16 00:00:00",
            "Дата окончания факт": "2025-04-16 00:00:00"
        },
        "Проведение РГ ГЗК И ГЗК": {
            "Дата окончания": "2025-04-23 00:00:00",
            "Дата окончания факт": "nan"
        },
        "Подготовка Утв . Части": {
            "Дата окончания": "2025-04-25 00:00:00",

In [91]:
for i in range(0, len(inner_df), 2):
    pair = inner_df.iloc[i:i+2]  # Получаем срез из двух строк
    result = pair.iloc[0,:3].to_dict() # попробовать dict
    # result.update(pair[["Статус"]].iloc[[0]].to_dict(orient='records')[0])
    # result.update(pair.loc[0, "Статус"].to_dict())
    print(json.dumps(result, indent=4, ensure_ascii=False))

{
    "№": "1",
    "Наименование работы": "Подготовка проекта планировки территории транспортно-пересадочного узла \"ЗИЛ\"",
    "Квартал утверждения ППТ": "3 кв 2025"
}
{
    "№": "2",
    "Наименование работы": "Подготовка проекта планировки территории транспортно-пересадочного узла \"Остров мечты\"",
    "Квартал утверждения ППТ": "3 кв 2025"
}
{
    "№": "3",
    "Наименование работы": "Подготовка проекта планировки территории транспортно-пересадочного узла \"Народное ополчение\"",
    "Квартал утверждения ППТ": "3 кв 2025"
}
{
    "№": "4",
    "Наименование работы": "Подготовка проекта планировки территории транспортно-пересадочного узла \"Строгино\"",
    "Квартал утверждения ППТ": "3 кв 2025"
}
{
    "№": "5",
    "Наименование работы": "Подготовка проекта планировки территории транспортно-пересадочного узла \"Лебедянская\"",
    "Квартал утверждения ППТ": "3 кв 2025"
}
{
    "№": "6",
    "Наименование работы": "Подготовка проекта планировки территории транспортно-пересадочного узла \"Серебряный бор\"",
    "Квартал утверждения ППТ": "4 кв 2025"
}
{
    "№": "7",
    "Наименование работы": "Подготовка проекта планировки территории транспортно-пересадочного узла \"Кленовый бульвар\"",
    "Квартал утверждения ППТ": "4 кв 2025"
}
{
    "№": "8",
    "Наименование работы": "Подготовка проекта планировки территории транспортно-пересадочного узла \"Бирюлево\"",
    "Квартал утверждения ППТ": "4 кв 2025"
}
{
    "№": "9",
    "Наименование работы": "Подготовка проекта планировки территории транспортно-пересадочного узла \"Бульвар Адмирала Карбышева\"",
    "Квартал утверждения ППТ": "4 кв 2025"
}
{
    "№": "10",
    "Наименование работы": "Подготовка проекта планировки территории транспортно-пересадочного узла \"Кедровая\"",
    "Квартал утверждения ППТ": "1 кв 2026"
}
{
    "№": "11",
    "Наименование работы": "Подготовка проекта планировки территории транспортно-пересадочного узла \"Троицкая\"",
    "Квартал утверждения ППТ": "1 кв 2026"
}
{
    "№": "12",
    "Наименование работы": "Подготовка проекта планировки территории транспортно-пересадочного узла \"Сосенки\"",
    "Квартал утверждения ППТ": "1 кв 2026"
}
{
    "№": "13",
    "Наименование работы": "Подготовка проект планировки территории транспортно-пересадочного узла «Ильинская»",
    "Квартал утверждения ППТ": "4 кв 2025"
}
{
    "№": "14",
    "Наименование работы": "Проект планировки территории линейного объекта - пешеходный переход через МЦД-4 в районе Кетчерской улицы",
    "Квартал утверждения ППТ": "4 кв 2025"
}
{
    "№": "16",
    "Наименование работы": "Подготовка материалов предварительной оценки градостроительного потенциала территории  ТПУ «Ватутинки»",
    "Квартал утверждения ППТ": "nan"
}

In [73]:
inner_df[["Статус"]].iloc[[0]]

3                                             Статус
0  Повторное рассмотрение на штабе метро у ЕВВ 22...

In [81]:
inner_df[["Статус"]].iloc[[0]].to_dict(orient='records')[0]

{'Статус': 'Повторное рассмотрение на штабе метро у ЕВВ 22.04.25 (возможность утверждения на ГЗК без НПМ. НПМ готовит инвестор)'}

In [175]:
for df in inner_df.itertuples():
    result = df.to_dict(orient='records')
    print(json.dumps(result, indent=4, ensure_ascii=False))

AttributeError: 'Pandas' object has no attribute 'to_dict'

In [274]:
a = dict()
a["a_key"] = dict()
a["a_key"].update({"b_key_1":"value_1"})
a["a_key"].update({"b_key_2":"value_2"})
a

{'a_key': {'b_key_1': 'value_1', 'b_key_2': 'value_2'}}